all_phi – SIESTA
all_phi Subroutine
70 statements
Source File
public subroutine all_phi(is, it, r, nphi, phi, grphi)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
integer, intent(in) :: it
real(kind=dp), intent(in) :: r(3)
integer, intent(out) :: nphi
real(kind=dp), intent(out) :: phi(:)
real(kind=dp), intent(out), optional :: grphi(:,:)
Calls
Contents
Source Code
all_phi
Source Code
      subroutine all_phi( is, it, r, nphi, phi, grphi )
      integer,   intent(in) :: is     ! Species index
      integer,   intent(in) :: it     ! Orbital-type switch:
                                      ! IT > 0 => Basis orbitals
                                      ! IT < 0 => KB projectors
      real(dp),  intent(in) :: r(3)   ! Point vector, relative to atom
      integer,  intent(out) :: nphi   ! Number of phi's
      real(dp), intent(out) :: phi(:) ! Basis orbital, KB projector, or
                                      !  local pseudopotential
      real(dp), optional, intent(out) :: grphi(:,:) ! Gradient of phi
C  Returns Kleynman-Bylander local pseudopotential, nonlocal projectors,
C  and atomic basis orbitals (and their gradients).
C  Same as phiatm but returns all orbitals or KB projectors of the atom
C  Written by D.Sanchez-Portal and J.M.Soler. Jan. 2000
C Distances in Bohr
C 1) Each projector and basis function has a well defined total
C    angular momentum (quantum number l).
C 2) Basis functions are normalized and mutually orthogonal
C 3) Projection functions are normalized and mutually orthogonal
C 4) Normalization of KB projectors |Phi_lm> is such that
C     <Psi|V_KB|Psi'> = <Psi|V_local|Psi'> +
C                   Sum_lm(epsKB_l * <Psi|Phi_lm> * <Phi_lm|Psi'>)
C    where epsKB_l is returned by function EPSKB
C 5) Prints a message and stops when no data exits for IS
C 6) Returns exactly zero when |R| > RCUT(IS,IO)
C 8) If arrays phi or grphi are too small, returns with the required
C    value of nphi
      integer i, jlm, l, lmax, m, maxlm, n
      double precision  rmod, phir, dphidr
      real(dp) rly(max_ilm), grly(3,max_ilm)
      integer, parameter :: maxphi=100
      integer :: ilm(maxphi)
      double precision :: rmax(maxphi)
      logical :: within(maxphi)
      call chk('all_phi',is)
      spp => species(is)
!     Find number of orbitals
      if (it.gt.0) then
        nphi=spp%norbs
      elseif (it.lt.0) then
        nphi=spp%nprojs
      else
         call die("all_phi: Please use phiatm to get Vna...")
      endif
      if (nphi.gt.maxphi) call die('all_phi: maxphi too small')
      if (it.gt.0) then
         do i = 1, nphi
            l = spp%orb_l(i)
            m = spp%orb_m(i)
            ilm(i) = l*(l+1)+m+1
            op => spp%orbnl(spp%orb_index(i))
            rmax(i) = op%cutoff
         enddo
      else
         do i = 1, nphi
            pp => spp%pjnl(spp%pj_index(i))
            rmax(i) = pp%cutoff
            l = spp%pj_l(i)
            m = spp%pj_m(i)
            ilm(i) = l*(l+1)+m+1
         enddo
      endif
!     Check size of output arrays
      if (present(grphi)) then
        if (size(grphi,1).ne.3)
     .    call die('all_phi: incorrect first dimension of grphi')
        n = min( size(phi), size(grphi,2) )
      else
        n = size(phi)
      endif
!     Return if the caller did not provide arrays large enough...
      if (n.lt.nphi) return
!     Initialize orbital values
      phi(1:nphi) = 0._dp
      if (present(grphi)) grphi(:,1:nphi) = 0._dp
      if ((it.lt.0) .and. floating(is)) return
!     Find for which orbitals rmod < rmax and test for quick return
      rmod = sqrt(sum(r*r)) + tiny20
      within(1:nphi) = ( rmax(1:nphi) > rmod )
      if (.not.any(within(1:nphi))) return
!     Find spherical harmonics
      maxlm = maxval( ilm(1:nphi), mask=within(1:nphi) )
      lmax=nint(sqrt(real(maxlm,dp)))-1
      call rlylm(lmax,r,rly,grly)
!     Find values
      i_loop: do i=1,nphi
!       Check if rmod > rmax
        if (.not.within(i)) cycle i_loop
!       Find radial part
        if (it.gt.0) then
           func => spp%orbnl(spp%orb_index(i))
        else
           func => spp%pjnl(spp%pj_index(i))
        endif
        call rad_get(func,rmod,phir,dphidr)
!       Multiply radial and angular parts
        jlm = ilm(i)
        phi(i) = phir * rly(jlm)
        if (present(grphi))
     .    grphi(:,i) = dphidr * rly(jlm) * r(:) / rmod +
     .                 phir * grly(:,jlm)
      enddo i_loop
      end subroutine all_phi
Call graph
all_phi calls chk, rlylm, die, floating, rad_get
chk calls die
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush
floating calls izofis
rad_get calls splint
izofis calls chk