allocASynBuffer – SIESTA
allocASynBuffer Subroutine
31 statements
Source File
public subroutine allocASynBuffer(ndistr)
Uses
mesh
Allocate memory buffers for asynchronous communications. It does nothing for synchronous communications.
The output values are stored in the current module:
tBuff1 : Buffer for distribution 1
tBuff2 : Buffer for other distributions
Arguments
Type Intent Optional Attributes Name
integer :: ndistr
Total number of distributions
Calls
Contents
Source Code
allocASynBuffer
Source Code
      subroutine allocASynBuffer( ndistr )
!! Allocate memory buffers for asynchronous communications.
!! It does nothing for synchronous communications.
!! The output values are stored in the current module:
!! `[[moreMeshSubs(module):tBuff1(variable)]]` : Buffer for distribution 1
!! `[[moreMeshSubs(module):tBuff2(variable)]]` : Buffer for other distributions
      use mesh,    only : nsm
      implicit none
      integer                     :: ndistr
        !! Total number of distributions
      integer          :: ii, jj, imax1, imax2, lsize, nsp, Lbox(2,3)
      integer, pointer :: box1(:,:), box2(:,:), nsize(:)
      logical          :: inters
#ifdef ASYNCHRONOUS
!     Allocate local memory
      nsp  = nsm*nsm*nsm
      call re_alloc( nsize, 1, ndistr, 'nsize', moduName )
!     Check the size of the local box for every data distribution
      do ii= 1, ndistr
        box1 => meshDistr(ii)%box(:,:,node+1)
        nsize(ii) = (box1(2,1)-box1(1,1)+1)*
     &              (box1(2,2)-box1(1,2)+1)*
     &              (box1(2,3)-box1(1,3)+1)*nsp
      enddo
!     Check the size of the intersections between the first data distributions
!     and the others data distributions.
!     Buffers don't need to store intersections
      imax1 = 0
      imax2 = 0
      box1 => meshDistr(1)%box(:,:,node+1)
      do ii= 2, ndistr
        box2 => meshDistr(ii)%box(:,:,node+1)
        call boxIntersection( box1, box2, Lbox, inters )
        if (inters) then
          lsize = (Lbox(2,1)-Lbox(1,1)+1)*
     &            (Lbox(2,2)-Lbox(1,2)+1)*
     &            (Lbox(2,3)-Lbox(1,3)+1)*nsp
        else
          lsize = 0
        endif
        imax1 = max(imax1,nsize(1)-lsize)
        imax2 = max(imax2,nsize(ii)-lsize)
      enddo
!     Deallocate local memory
      call de_alloc( nsize, 'nsize', moduName )
!     Allocate memory for asynchronous communications
      call re_alloc( tBuff1, 1, imax1, 'tBuff1', moduName )
      call re_alloc( tBuff2, 1, imax2, 'tBuff2', moduName )
#endif
      end subroutine allocASynBuffer
Call graph
allocasynbuffer calls re_alloc, boxintersection, de_alloc