ATMPOPFIO – SIESTA
ATMPOPFIO Function
8 statements
Source File
public function ATMPOPFIO(is, io) result(atmpopfio)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
integer, intent(in) :: io
Return Value real(kind=dp)
Calls
Contents
Source Code
ATMPOPFIO
Source Code
      FUNCTION ATMPOPFIO (IS,IO)
      real(dp) atmpopfio
      integer, intent(in) :: is    ! Species index
      integer, intent(in) :: io    ! Orbital index (within atom)
C Returns the population of the atomic basis orbitals in the atomic
C ground state configuration.
      call chk('atmpopfio',is)
      if ( (io .gt. species(is)%norbs) .or.
     $     (io .lt. 1))   call die("atmpopfio: Wrong io")
      atmpopfio = species(is)%orb_pop(io)
      end function atmpopfio
Call graph
atmpopfio calls chk
chk calls die
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush