boxIntersection – SIESTA
boxIntersection Subroutine
13 statements
Source File
private subroutine boxIntersection(ibox1, ibox2, obox, inters)
Checks the three axis of the input boxes to see if there is intersection between the input boxes. If it exists, returns the resulting box.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ibox1(2,3)
Input box
integer, intent(in) :: ibox2(2,3)
Input box
integer, intent(out) :: obox(2,3)
Intersection between ibox1 and ibox2
logical, intent(out) :: inters
TRUE, if there is an intersection. Otherwise FALSE.
Called by
Contents
Source Code
boxIntersection
Source Code
      subroutine boxIntersection( ibox1, ibox2, obox, inters )
!! Checks the three axis of the input boxes to see if there is
!! intersection between the input boxes. If it exists, returns
!! the resulting box.
      implicit none
!     Passed arguments
      integer,  intent(in) :: ibox1(2,3), ibox2(2,3)
        !! Input box
      integer, intent(out) :: obox(2,3)
        !! Intersection between `ibox1` and `ibox2`
      logical, intent(out) :: inters
        !! `TRUE`, if there is an intersection. Otherwise `FALSE`.
!     Local variables
      integer              :: iaxis
      inters = .true.
      do iaxis= 1, 3
        obox(1,iaxis) = max(ibox1(1,iaxis),ibox2(1,iaxis))
        obox(2,iaxis) = min(ibox1(2,iaxis),ibox2(2,iaxis))
        if (obox(2,iaxis).lt.obox(1,iaxis)) inters = .false.
      enddo
      end subroutine boxIntersection
Call graph
reordmeshnumbering calls boxintersection
distmeshdata_rea calls boxintersection
distextmeshdata calls boxintersection
compmeshcomm calls boxintersection
allocasynbuffer calls boxintersection
gathextmeshdata calls boxintersection
splitwload calls boxintersection
distmeshdata_int calls boxintersection
initmeshextencil calls boxintersection
distmeshdata calls distmeshdata_rea, distmeshdata_int
dhscf_init calls distmeshdata
dhscf calls distmeshdata, forhar
forhar calls distmeshdata
siesta_analysis calls dhscf
setup_hamiltonian calls dhscf
setup_h0 calls dhscf_init
siesta_forces calls setup_hamiltonian