bye – SIESTA
bye Subroutine
20 statements
Source File
public subroutine bye(str)
Uses
parallel
siesta_cml
mpi_siesta
Prints an error message and calls MPI_Finalize
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: str
Calls
Called by
Contents
Source Code
bye
Source Code
      subroutine bye(str)
        !! Prints an error message and calls MPI_Finalize
      use parallel, only : Node
      use siesta_cml
#ifdef MPI
      use mpi_siesta
#endif
      character(len=*), intent(in), optional   :: str
#ifdef MPI
      integer rc
#endif
      if (Node.eq.0) then
         if (present(str)) then
            write(6,'(a)') trim(str)
         endif
         write(6,'(a)') 'Requested End of Run. Bye!!'
         call pxfflush(6)
         If (cml_p) Then
            Call cmlFinishFile(mainXML)
         Endif                  !cml_p
      endif
#ifdef MPI
      call MPI_Finalize(rc)
      stop
#else
      stop
#endif
      end subroutine bye
Call graph
bye calls pxfflush, mpi_finalize, cmlfinishfile
dhscf calls bye
state_init calls bye
setup_hamiltonian calls bye, dhscf
siesta_forces calls bye, state_init, setup_hamiltonian, compute_dm
compute_dm calls bye
siesta_analysis calls dhscf