chcore_sub – SIESTA
chcore_sub Subroutine
17 statements
Source File
public subroutine chcore_sub(is, r, ch, grch)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
real(kind=dp), intent(in) :: r(3)
real(kind=dp), intent(out) :: ch
real(kind=dp), intent(out) :: grch(3)
Calls
Contents
Source Code
chcore_sub
Source Code
      subroutine chcore_sub(is,r,ch,grch)
      integer, intent(in) :: is      ! Species index
      real(dp), intent(in)  :: r(3)    ! Point vector, relative to atom
      real(dp), intent(out) :: ch      ! Value of pseudo-core charge dens.
      real(dp), intent(out) :: grch(3) ! Gradient of pseudo-core ch. dens.
C Returns returns pseudo-core charge density for non-linear core correction
C in the xc potential.
C Distances in Bohr, Energies in Rydbergs, Density in electrons/Bohr**3
C  2) Returns exactly zero when |R| > Rcore
      real(dp) rmod, dchdr
      call chk('chcore_sub',is)
      ch=0.0_dp
      grch(1:3)=0.0_dp
      if (floating(is)) return
      func => species(is)%core
      rmod = sqrt(sum(r*r))
      rmod=rmod+tiny20                   ! Moved here. JMS, Dec.2012
      if (rmod .gt. func%cutoff) return
      call rad_get(func,rmod,ch,dchdr)
!      rmod=rmod+tiny20                   ! Removed. JMS, Dec.2012
      grch(1:3) = dchdr * r(1:3)/rmod
      end subroutine chcore_sub
Call graph
chcore_sub calls chk, floating, rad_get
chk calls die
floating calls izofis
rad_get calls splint
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush
izofis calls chk