check_rho – SIESTA
check_rho Subroutine
51 statements
Source File
public subroutine check_rho(fname, maxp, nspin, nsm, found, overflow)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fname
integer, intent(inout) :: maxp
Required first dimension of array rho,
equal to mesh(1)*mesh(2)*mesh(3)
integer, intent(inout) :: nspin
Number of spin polarizations (1 or 2)
integer, intent(in) :: nsm
Number of sub-mesh points per mesh point
(not used in this version)
logical, intent(out) :: found
Were data found?
logical, intent(out) :: overflow
True if maxp or nspin were changed
Calls
Contents
Source Code
check_rho
Source Code
      subroutine check_rho(fname,maxp,nspin,nsm,found,overflow)
      character(len=*), intent(in) ::     fname
      integer, intent(in)          ::     nsm
        !! Number of sub-mesh points per mesh point
        !! (not used in this version)
      integer, intent(inout)       ::     maxp
        !! Required first dimension of array rho,
        !! equal to `mesh(1)*mesh(2)*mesh(3)`
      integer, intent(inout)       ::     nspin
        !! Number of spin polarizations (1 or 2)
      logical, intent(out)         ::     found
        !! Were data found?
      logical, intent(out)         ::     overflow
        !! True if `maxp` or `nspin` were changed
      real(dp) :: cell(3,3)
      integer  :: mesh(3)
      integer  :: meshnsm(3), npl, ns, iu, np, npmax
#ifdef MPI
      integer  :: meshl(3)
      logical  :: ltmp
      integer  :: MPIerror
#endif
! Check if input file exists
        if (Node.eq.0) then
          inquire( file=fname, exist=found )
        endif
#ifdef MPI
        call MPI_Bcast(found,1,MPI_logical,0,MPI_Comm_World,MPIerror)
#endif
        if (.not. found) return
! Open file
          if (Node.eq.0) then
            call io_assign( iu )
            open( iu, file=fname, form=fform, status='old' )
! Read cell vectors and number of points
            if (fform .eq. 'formatted') then
              read(iu,*) cell
              read(iu,*) mesh, ns
            else
              read(iu) cell
              read(iu) mesh, ns
            endif
          endif
#ifdef MPI
          call MPI_Bcast(cell(1,1),9,MPI_double_precision,0,
     .      MPI_Comm_World,MPIerror)
          call MPI_Bcast(mesh,3,MPI_integer,0,MPI_Comm_World,MPIerror)
          call MPI_Bcast(ns,1,MPI_integer,0,MPI_Comm_World,MPIerror)
#endif
          np = mesh(1) * mesh(2) * mesh(3)
! Get local dimensions
          meshnsm(1) = mesh(1)/nsm
          meshnsm(2) = mesh(2)/nsm
          meshnsm(3) = mesh(3)/nsm
#ifdef MPI
          call HowManyMeshPerNode(meshnsm,Node,Nodes,npl,meshl)
#else
          npl = np
#endif
! Check dimensions
          overflow = .false.
          if (ns .gt. nspin) overflow = .true.
          if (npl .gt. maxp) overflow = .true.
#ifdef MPI
! Globalise dimension check
          call MPI_AllReduce(overflow,ltmp,1,MPI_logical,MPI_Lor,
     .      MPI_Comm_World,MPIerror)
          overflow = ltmp
#endif
          if (overflow) then    ! Some processor has npl > maxp ...
#ifdef MPI
! Find largest value of npl
            call MPI_AllReduce(npl,npmax,1,MPI_integer,MPI_Max,
     .        MPI_Comm_World,MPIerror)
#else
            npmax = np
#endif
            maxp = npmax
            nspin = ns
          endif
          if (Node.eq.0) call io_close( iu )
          end subroutine check_rho
Call graph
check_rho calls io_assign, mpi_allreduce, mpi_bcast, howmanymeshpernode