check_cohp – SIESTA
check_cohp Subroutine
9 statements
Source File
private subroutine check_cohp()
Uses
siesta_options
sys
Arguments
None
Calls
Called by
Contents
Source Code
check_cohp
Source Code
      subroutine check_cohp()
      use siesta_options, only: write_coop
      use sys,            only: message
      if (write_coop) then
         call message("WARNING","There are multiply-connected "//
     $                          "orbitals.")
         call message("WARNING","Your COOP/COHP analysis might " //
     $                          "be affected by folding.")
         call message("WARNING",'Use "force-aux-cell T "' //
     $                          'or k-point sampling')
      endif
      end subroutine check_cohp
Call graph
check_cohp calls message
message calls io_assign, pxfflush, io_close
state_init calls check_cohp
siesta_forces calls state_init