chk – SIESTA
chk Subroutine
8 statements
Source File
private subroutine chk(name, is)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
integer, intent(in) :: is
Calls
Called by
Contents
Source Code
chk
Source Code
      subroutine chk(name,is)
      character(len=*), intent(in) :: name
      integer, intent(in) :: is
      if ((is.lt.1).or.(is.gt.nspecies)) then
         write(message,'(2a,i3,a,i3)')
     $           name, ": Wrong species", is, ". Have", nspecies
         call die(message)
      endif
      end subroutine chk
Call graph
chk calls die
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush
nkbfis calls chk
psch calls chk, floating
uion calls chk
labelfis calls chk
zetafio calls chk
kbproj_gindex calls chk
zvalfis calls chk
nkbl_func calls chk
atmpopfio calls chk
rcore calls chk
lmxkbfis calls chk
cnfigfio calls chk
massfis calls chk
lofio calls chk
lomaxfis calls chk
nztfl calls chk
vna_sub calls chk, floating
ldau_gindex calls chk
chcore_sub calls chk, floating
mofio calls chk
psover calls chk, floating
nofis calls chk
orb_gindex calls chk
izofis calls chk
vna_gindex calls chk
symfio calls chk, lofio, mofio
rcut calls chk
rchlocal calls chk
all_phi calls chk, floating
dhscf_init calls rcore, rcut, rhooda
setup_h0 calls uion, dhscf_init
dfscf calls rcut
vmat calls rcut
rhooda calls rcut, phiatm
rhoofd calls rcut
delk calls rcut
floating calls izofis
dhscf calls dfscf, vmat, rhoofd
phiatm calls floating
delk_wrapper calls delk
rphiatm calls floating
siesta_analysis calls dhscf
setup_hamiltonian calls dhscf
siesta_forces calls setup_hamiltonian