compMeshComm – SIESTA
compMeshComm Subroutine
56 statements
Source File
private subroutine compMeshComm(distr1, distr2, mcomm)
Uses
scheComm
Find the communications needed to transform one array that uses distribution distr1 to distribution distr2
Count the number of intersections between the source distribution and the destiny distribution. Every intersection represents a communication. Then we call scheduleComm to optimize the order of these communications. Finally, we save the communications that belongs to the current process in the variable mcomm
Arguments
Type Intent Optional Attributes Name
type(meshDisType), intent(in) :: distr1
Source distribution
type(meshDisType), intent(in) :: distr2
Destination distribution
type(meshCommType), intent(out) :: mcomm
Communications needed
Calls
Contents
Source Code
compMeshComm
Source Code
      subroutine compMeshComm( distr1, distr2, mcomm )
!! Find the communications needed to transform one array that uses
!! distribution `distr1` to distribution `distr2`
!!
!! Count the number of intersections between the source distribution
!! and the destiny distribution. Every intersection represents a
!! communication. Then we call [[scheduleComm(proc)]]
!! to optimize the order of these
!! communications. Finally, we save the communications that belongs to
!! the current process in the variable `mcomm`
      use scheComm
      implicit none
      type(meshDisType),   intent(in) :: distr1
        !! Source distribution
      type(meshDisType),   intent(in) :: distr2
        !! Destination distribution
      type(meshCommType), intent(out) :: mcomm
        !! Communications needed
!     Local variables
      integer                         :: P1, P2, ncom, Gcom, Lcom,
     &                                   Lind, Lbox(2,3)
      integer,                pointer :: src(:), dst(:)
      logical                         :: inters
      type(COMM_T)                    :: comm
!     count the number of intersections between Source distribution and
!     destiny distribution. Every intersection represents a communication.
      ncom = 0
      do P1= 1, Nodes
        do P2= 1, Nodes
          call boxIntersection( distr1%box(:,:,P1),
     &                          distr2%box(:,:,P2), Lbox, inters )
          if (inters) ncom = ncom + 1
        enddo
      enddo
      Gcom = ncom
!     Allocate local arrays
      nullify( src, dst )
      call re_alloc( src, 1, Gcom, 'src', 'moreMeshSubs' )
      call re_alloc( dst, 1, Gcom, 'dst', 'moreMeshSubs' )
!     Make a list of communications
      ncom = 0
      do P1= 1, Nodes
        do P2= 1, Nodes
          call boxIntersection( distr1%box(:,:,P1),
     &                          distr2%box(:,:,P2), Lbox, inters )
          if (inters) then
            ncom      = ncom + 1
            src(ncom) = P1
            dst(ncom) = P2
          endif
        enddo
      enddo
      comm%np = Nodes
!     reschedule the communications in order to minimize the time
      call scheduleComm( Gcom, src, dst, comm )
!     Count the number of communications of the current process
      ncom = 0
      do P1= 1, comm%ncol
        if (comm%ind(P1,Node+1).ne.0) ncom = ncom + 1
      enddo
      Lcom = ncom
!     Allocate memory to store data of the communications of the
!     current process.
      nullify( mcomm%src, mcomm%dst )
      call re_alloc( mcomm%src, 1, Lcom, 'mcomm%src', 'moreMeshSubs' )
      call re_alloc( mcomm%dst, 1, Lcom, 'mcomm%dst', 'moreMeshSubs' )
!     Save the list of communications for the current process
      ncom = 0
      do P1= 1, comm%ncol
        Lind = comm%ind(P1,Node+1)
        if (Lind.ne.0) then
          ncom            = ncom + 1
          mcomm%src(ncom) = src(Lind)
          mcomm%dst(ncom) = dst(Lind)
        endif
      enddo
      mcomm%ncom = ncom
      call de_alloc( comm%ind, 'comm%ind', 'scheComm' )
      call de_alloc( dst,      'dst',      'moreMeshSubs' )
      call de_alloc( src,      'src',      'moreMeshSubs' )
      end subroutine compMeshComm
Call graph
compmeshcomm calls re_alloc, boxintersection, de_alloc, schedulecomm