current_itt – SIESTA
current_itt Function
5 statements
Source File
private function current_itt(mix) result(itt)
Get current iteration count
This is abstracted because the initial iteration and the current iteration may be uniquely defined.
Arguments
Type Intent Optional Attributes Name
type(tMixer), intent(in) :: mix
Return Value integer
Called by
Source Code
current_itt
Source Code
  function current_itt(mix) result(itt)
    type(tMixer), intent(in) :: mix
    integer :: itt
    itt = mix%cur_itt - mix%start_itt
  end function current_itt
All Procedures
compute_dm current_itt getstackval inverse is_next mix_method mix_method_variant mixer_init mixers_history_init mixers_init mixers_print mixers_print_block mixers_reset mixers_scf_history_init mixers_scf_init mixers_scf_print mixers_scf_print_block mixers_scf_reset mixing mixing_1d mixing_2d mixing_calc_next mixing_coeff mixing_finalize mixing_init mixing_ncoeff mixing_scf_converged mixing_step norm push_diff push_F push_stack_data setup_H0 setup_hamiltonian siesta_analysis siesta_forces stack_check state_analysis state_init svd update_F
Call graph
mixers_history_init calls current_itt
mixing_finalize calls current_itt
mixing_init calls current_itt
mixers_scf_history_init calls mixers_history_init
mixers_init calls mixers_history_init
mixers_scf_init calls mixers_history_init, mixers_init
state_init calls mixers_history_init
mixing_1d calls mixing_finalize, mixing_init
siesta_forces calls mixers_scf_history_init, state_init
mixing calls mixing_1d