delk_wrapper – SIESTA
delk_wrapper Subroutine
17 statements
Source File
public subroutine delk_wrapper(isigneikr, norb, maxnd, numd, listdptr, listd, nuo, nuotot, iaorb, iphorb, isa)
Uses
m_delk
moreMeshSubs
moreMeshSubs
parallel
mesh
This is a wrapper to call delk, using some of the module variables of m_dhscf, but from outside dhscf itself.
The dhscf module variables used are:
nmpl
dvol
nml
nmpl
ntml
ntpl
Some of them might be put somewhere else (mesh?) to allow some of the kitchen-sink functionality of dhscf to be made more modular. For example, this wrapper might live independently if enough mesh information is made available to it.
Arguments
Type Intent Optional Attributes Name
integer :: isigneikr
integer :: norb
integer :: maxnd
integer :: numd(nuo)
integer :: listdptr(nuo)
integer :: listd(maxnd)
integer :: nuo
integer :: nuotot
integer :: iaorb(*)
integer :: iphorb(*)
integer :: isa(*)
Calls
Contents
Source Code
delk_wrapper
Source Code
      subroutine delk_wrapper(isigneikr, norb, maxnd,
     &                        numd, listdptr, listd,
     &                        nuo,  nuotot, iaorb, iphorb, isa )
!! This is a wrapper to call [[delk(proc)]], using some of the module
!! variables of `m_dhscf`, but from outside `dhscf` itself.
!!
!! The dhscf module variables used are:
!!
!! * nmpl
!! * dvol
!! * nml
!! * nmpl
!! * ntml
!! * ntpl
!!
!! Some of them might be put somewhere else (mesh?) to allow some
!! of the kitchen-sink functionality of dhscf to be made more modular.
!! For example, this wrapper might live independently if enough mesh
!! information is made available to it.
      use m_delk,  only  : delk  ! The real workhorse, similar to vmat
      use moreMeshSubs,   only : setMeshDistr
      use moreMeshSubs,   only : UNIFORM, QUADRATIC
      use parallel,       only : Nodes
      use mesh,           only : nsm, nsp
      integer                  :: isigneikr,
     &                            norb, nuo, nuotot, maxnd,
     &                            iaorb(*), iphorb(*), isa(*),
     &                            numd(nuo),
     &                            listdptr(nuo), listd(maxnd)
! ----------------------------------------------------------------------
! Calculate matrix elements of exp(i \vec{k} \cdot \vec{r})
! ----------------------------------------------------------------------
        if (isigneikr .eq. 1 .or. isigneikr .eq. -1) then
          if (nodes.gt.1) then
            call setMeshDistr( QUADRATIC, nsm, nsp,
     &                         nml, nmpl, ntml, ntpl )
          endif
          call delk( isigneikr, norb, nmpl, dvol, maxnd,
     &               numd, listdptr, listd,
     &               nuo,  nuotot, iaorb, iphorb, isa )
          if (nodes.gt.1) then
!           Everything back to UNIFORM, sequential
            call setMeshDistr( UNIFORM, nsm, nsp,
     &                         nml, nmpl, ntml, ntpl )
          endif
        endif
      end subroutine delk_wrapper
Call graph
delk_wrapper calls setmeshdistr, delk
delk calls phi, indxuo, listsc, dsin, matrixmtooc, endpht, re_alloc, xa, listp2, indxua, timer, needdscfl, dcos, globaltolocalorb, de_alloc, numdl, lstpht, rcut, listdlptr, ipack, listdl
rcut calls chk
chk calls die
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush