dhscf_init – SIESTA
dhscf_init Subroutine
210 statements
Source File
public subroutine dhscf_init(nspin, norb, iaorb, iphorb, nuo, nuotot, nua, na, isa, xa, indxua, ucell, mscell, g2max, ntm, maxnd, numd, listdptr, listd, datm, Fal, stressl)
Uses
precision
parallel
atmfuncs
fdf
sys
mesh
parsing
siestaXC
bsc_xcmod
alloc
siesta_options
meshsubs
meshsubs
meshsubs
meshsubs
meshsubs
meshsubs
meshsubs
moreMeshSubs
moreMeshSubs
moreMeshSubs
meshdscf
iogrid_netcdf
m_ncdf_io
cellxc_mod
m_efield
m_efield
m_efield
m_efield
m_doping_uniform
m_doping_uniform
m_rhog
m_rhog
siesta_options
mpi_siesta
m_mesh_node
m_charge_add
m_hartree_add
m_ts_global_vars
m_ts_options
m_ts_voltage
m_ts_hartree
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nspin
integer, intent(in) :: norb
integer, intent(in) :: iaorb(norb)
integer, intent(in) :: iphorb(norb)
integer, intent(in) :: nuo
integer, intent(in) :: nuotot
integer, intent(in) :: nua
integer, intent(in) :: na
integer, intent(in) :: isa(na)
real(kind=dp), intent(in) :: xa(3,na)
integer, intent(in) :: indxua(na)
real(kind=dp), intent(in) :: ucell(3,3)
integer, intent(in) :: mscell(3,3)
real(kind=dp), intent(inout) :: g2max
integer, intent(inout) :: ntm(3)
integer, intent(in) :: maxnd
integer, intent(in) :: numd(nuo)
integer, intent(in) :: listdptr(nuo)
integer, intent(in) :: listd(maxnd)
real(kind=dp), intent(in) :: datm(norb)
real(kind=dp), intent(inout) :: Fal(3,nua)
real(kind=dp), intent(inout) :: stressl(3,3)
Calls
Called by
Contents
Source Code
dhscf_init
Source Code
      subroutine dhscf_init(nspin, norb, iaorb, iphorb,
     &                      nuo, nuotot, nua, na,
     &                      isa, xa, indxua, ucell,
     &                      mscell, G2max, ntm,
     &                      maxnd, numd, listdptr, listd, datm,
     &                      Fal, stressl)
      use precision,      only : dp, grid_p
      use parallel,       only : Node, Nodes
      use atmfuncs,       only : rcut, rcore
      use fdf
      use sys,            only : die
      use mesh,           only : xdsp, nsm, nsp, meshLim
      use parsing
#ifndef BSC_CELLXC
      use siestaXC, only : getXC        ! Returns the XC functional used
#else /* BSC_CELLXC */
      use bsc_xcmod,          only : nXCfunc, XCauth
#endif /* BSC_CELLXC */
      use alloc,          only : re_alloc, de_alloc
      use siesta_options, only : harrisfun
      use meshsubs,       only : PartialCoreOnMesh
      use meshsubs,       only : NeutralAtomOnMesh
      use meshsubs,       only : PhiOnMesh
      use meshsubs,       only : InitMesh
      use meshsubs,       only : InitAtomMesh
      use meshsubs,       only : setupExtMesh
      use meshsubs,       only : distriPhiOnMesh
      use moreMeshSubs,   only : setMeshDistr, distMeshData
      use moreMeshSubs,   only : UNIFORM, QUADRATIC, LINEAR
      use moreMeshSubs,   only : TO_SEQUENTIAL, TO_CLUSTER, KEEP
      use meshdscf,       only : createLocalDscfPointers
      use iogrid_netcdf, only: set_box_limits
#ifdef NCDF_4
      use m_ncdf_io, only : cdf_init_mesh
#endif
#ifdef BSC_CELLXC
      use cellxc_mod,     only : setGGA
#endif /* BSC_CELLXC */
      use m_efield,       only : initialize_efield, acting_efield
      use m_efield,       only : get_field_from_dipole
      use m_efield,       only : dipole_correction
      use m_efield,       only : user_specified_field
      use m_doping_uniform,       only: initialize_doping_uniform
      use m_doping_uniform,       only: compute_doping_structs_uniform,
     $                                  doping_active
      use m_rhog,                 only: rhog, rhog_in
      use m_rhog,                 only: order_rhog
      use siesta_options,         only: mix_charge
#ifdef MPI
      use mpi_siesta
#endif
      use m_mesh_node,   only: init_mesh_node
      use m_charge_add,  only: init_charge_add
      use m_hartree_add, only: init_hartree_add
      use m_ts_global_vars,only: TSmode
      use m_ts_options,   only : IsVolt, N_Elec, Elecs
      use m_ts_voltage,   only : ts_init_voltage
      use m_ts_hartree,   only : ts_init_hartree_fix
      implicit none
      integer, intent(in)     :: nspin, norb, iaorb(norb), iphorb(norb),
     &                           nuo, nuotot, nua, na, isa(na),
     &                           indxua(na), mscell(3,3), maxnd,
     &                           numd(nuo), listdptr(nuo), listd(maxnd)
      real(dp), intent(in)    :: xa(3,na), ucell(3,3), datm(norb)
      real(dp), intent(inout) :: g2max
      integer, intent(inout)  :: ntm(3)
      real(dp), intent(inout) :: Fal(3,nua), stressl(3,3)
      real(dp), parameter     :: tiny  = 1.e-12_dp
      integer                 :: io, ia, iphi, is, n, i, j
      integer                 :: nsc(3), nbcell, nsd
      real(dp)                :: DStres(3,3), volume
      real(dp), external      :: volcel, ddot
      real(grid_p)            :: dummy_Drho(1,1), dummy_Vaux(1),
     &                           dummy_Vscf(1)
      logical, save           :: frstme = .true.   ! Keeps state
      real(grid_p),   pointer :: Vscf(:,:), rhoatm_par(:)
      integer,        pointer :: numphi(:), numphi_par(:)
      integer                 :: nm(3)   ! For call to initMesh
#ifndef BSC_CELLXC
      integer                 :: nXCfunc
      character(len=20)       :: XCauth(10), XCfunc(10)
#endif /* ! BSC_CELLXC */
      ! Transport direction (unit-cell aligned)
      integer                 :: iE
      real(dp)                :: ortho, field(3), field2(3)
!--------------------------------------------------------------------- BEGIN
#ifdef DEBUG
      call write_debug( '    PRE dhscf_init' )
#endif
! ----------------------------------------------------------------------
!     General initialisation
! ----------------------------------------------------------------------
!     Start time counter
      call timer( 'DHSCF_Init', 1 )
      nsd = min(nspin,2)
      nullify(Vscf,rhoatm_par)
      if (frstme) then
        debug_dhscf = fdf_get('Debug.DHSCF', .false.)
        nullify( xdsp, rhopcc, Vna, rhoatm )
!       nsm lives in module m_dhscf now    !! AG**
        nsm = fdf_integer( 'MeshSubDivisions', 2 )
        nsm = max( nsm, 1 )
!       Set mesh sub-division variables & perform one off allocation
        nsp = nsm*nsm*nsm
        call re_alloc( xdsp, 1, 3, 1, nsp, 'xdsp', 'dhscf_init' )
!       Check spin-spiral wavevector (if defined)
        if (spiral .and. nspin.lt.4)
     &    call die('dhscf: ERROR: spiral defined but nspin < 4')
      endif   ! First time
#ifndef BSC_CELLXC
! Get functional(s) being used
      call getXC( nXCfunc, XCfunc, XCauth )
#endif /* ! BSC_CELLXC */
      if (harrisfun) then
        do n = 1,nXCfunc
          if (.not.(leqi(XCauth(n),'PZ').or.leqi(XCauth(n),'CA'))) then
            call die("** Harris forces not implemented for non-LDA XC")
          endif
        enddo
      endif
! ----------------------------------------------------------------------
!     Orbital initialisation : part 1
! ----------------------------------------------------------------------
!     Find the maximum orbital radius
      rmax = 0.0_dp
      do io = 1, norb
        ia   = iaorb(io)    ! Atomic index of each orbital
        iphi = iphorb(io)   ! Orbital index of each  orbital in its atom
        is   = isa(ia)      ! Species index of each atom
        rmax = max( rmax, rcut(is,iphi) )
      enddo
!     Start time counter for mesh initialization
      call timer( 'DHSCF1', 1 )
! ----------------------------------------------------------------------
!     Unit cell handling
! ----------------------------------------------------------------------
!     Find diagonal unit cell and supercell
      call digcel( ucell, mscell, cell, scell, nsc, IsDiag )
      if (.not.IsDiag) then
        if (Node.eq.0) then
          write(6,'(/,a,3(/,a,3f12.6,a,i6))')
     &      'DHSCF: WARNING: New shape of unit cell and supercell:',
     &      ('DHSCF:',(cell(i,j),i=1,3),'   x',nsc(j),j=1,3)
        endif
      endif
!     Find the system shape
      call shaper( cell, nua, isa, xa, shape, nbcell, bcell )
!     Find system volume
      volume = volcel( cell )
! ----------------------------------------------------------------------
!     Mesh initialization
! ----------------------------------------------------------------------
      call InitMesh( na, cell, norb, iaorb, iphorb, isa, rmax,
     &               G2max, G2mesh, nsc, nmpl, nm,
     &               nml, ntm, ntml, ntpl, dvol )
!     Setup box descriptors for each processor,
!     held in module iogrid_netcdf
      call set_box_limits( ntm, nsm )
      ! Initialize information on local mesh for each node
      call init_mesh_node( cell, ntm , meshLim , nsm )
      ! Setup charge additions in the mesh
      call init_charge_add(cell, ntm)
      ! Setup Hartree additions in the mesh
      call init_hartree_add(cell, ntm)
#ifdef NCDF_4
      ! Initialize the box for each node...
      call cdf_init_mesh( ntm, nsm )
#endif
!     Stop time counter for mesh initialization
      call timer( 'DHSCF1', 2 )
! ----------------------------------------------------------------------
!     End of mesh initialization
! ----------------------------------------------------------------------
! ----------------------------------------------------------------------
!     Initialize atomic orbitals, density and potential
! ----------------------------------------------------------------------
!     Start time counter for atomic initializations
      call timer( 'DHSCF2', 1 )
      if (nodes.gt.1) then
        call setMeshDistr( UNIFORM, nsm, nsp,
     &                     nml, nmpl, ntml, ntpl )
      endif
!     Initialise quantities relating to the atom-mesh positioning
      call InitAtomMesh( UNIFORM, na, xa )
#ifdef BSC_CELLXC
!     Check if we need extencils in cellxc
      call setGGA( )
#endif /* BSC_CELLXC */
!     Compute the number of orbitals on the mesh and recompute the
!     partions for every processor in order to have a similar load
!     in each of them.
      nullify( numphi )
      call re_alloc( numphi, 1, nmpl, 'numphi', 'dhscf_init' )
!$OMP parallel do default(shared), private(i)
      do i= 1, nmpl
        numphi(i) = 0
      enddo
!$OMP end parallel do
      call distriPhiOnMesh( nm, nmpl, norb, iaorb, iphorb,
     &                      isa, numphi )
!     Find if there are partial-core-corrections for any atom
      npcc = 0
      do ia = 1,na
        if (rcore(isa(ia)) .gt. tiny) npcc = 1
      enddo
!     Find partial-core-correction energy density
!     Vscf and Vaux are not used here
      call re_alloc( rhopcc, 1, ntpl*npcc+1, 'rhopcc', 'dhscf_init' )
      if (npcc .eq. 1) then
        call PartialCoreOnMesh( na, isa, ntpl, rhopcc, indxua,
     &    nsd, dvol, volume, dummy_Vscf, dummy_Vaux, Fal, stressl,
     &    .false., .false. )
        call reord( rhopcc, rhopcc, nml, nsm, TO_SEQUENTIAL )
        if ( debug_dhscf ) then
           write(*,debug_fmt) Node,'rhopcc',sqrt(sum(rhopcc**2))
        end if
      endif
!     Find neutral-atom potential
!     Drho is not used here
      call re_alloc( Vna, 1, ntpl, 'Vna', 'dhscf_init' )
      call NeutralAtomOnMesh( na, isa, ntpl, Vna, indxua, dvol,
     &                        volume, dummy_DRho, Fal, stressl,
     &                        .false., .false. )
      call reord( Vna, Vna, nml, nsm, TO_SEQUENTIAL )
      if ( debug_dhscf ) then
         write(*,debug_fmt) Node,'Vna',sqrt(sum(Vna**2))
      end if
      if (nodes.gt.1) then
        if (node .eq. 0) then
           write(6,"(a)") "Setting up quadratic distribution..."
        endif
        call setMeshDistr( QUADRATIC, nsm, nsp,
     &                     nml, nmpl, ntml, ntpl )
!       Create extended mesh arrays for the second data distribution
        call setupExtMesh( QUADRATIC, rmax )
!       Compute atom positions for the second data distribution
        call InitAtomMesh( QUADRATIC, na, xa )
      endif
!     Calculate orbital values on mesh
!     numphi has already been computed in distriPhiOnMesh
!     in the UNIFORM distribution
      if (nodes.eq.1) then
        numphi_par => numphi
      else
        nullify(numphi_par)
        call re_alloc( numphi_par, 1, nmpl, 'numphi_par',
     &                 'dhscf_init' )
        call distMeshData( UNIFORM, numphi, QUADRATIC,
     &                     numphi_par, KEEP )
      endif
      call PhiOnMesh( nmpl, norb, iaorb, iphorb, isa, numphi_par )
      if (nodes.gt.1) then
        call de_alloc( numphi_par, 'numphi_par', 'dhscf_init' )
      endif
      call de_alloc( numphi, 'numphi', 'dhscf_init' )
! ----------------------------------------------------------------------
!       Create sparse indexing for Dscf as needed for local mesh
!       Note that this is done in the QUADRATIC distribution
!       since 'endpht' (computed finally in PhiOnMesh and stored in
!       meshphi module) is in that distribution.
! ----------------------------------------------------------------------
      if (Nodes.gt.1) then
        call CreateLocalDscfPointers( nmpl, nuotot, numd, listdptr,
     &                                listd )
      endif
! ----------------------------------------------------------------------
!     Calculate terms relating to the neutral atoms on the mesh
! ----------------------------------------------------------------------
!     Find Harris (sum of atomic) electron density
      call re_alloc( rhoatm_par, 1, ntpl, 'rhoatm_par', 'dhscf_init' )
      call rhooda( norb, nmpl, datm, rhoatm_par, iaorb, iphorb, isa )
!     rhoatm_par comes out of here in clustered form in QUADRATIC dist
!     Routine Poison should use the uniform data distribution
      if (nodes.gt.1) then
         call setMeshDistr( UNIFORM, nsm, nsp,
     &                      nml, nmpl, ntml, ntpl )
      endif
!     Create Rhoatm using UNIFORM distr, in sequential form
      call re_alloc( rhoatm, 1, ntpl, 'rhoatm', 'dhscf_init' )
      call distMeshData( QUADRATIC, rhoatm_par,
     &     UNIFORM, rhoatm, TO_SEQUENTIAL )
      if ( debug_dhscf ) then
         write(*,debug_fmt) Node,'rhoatm', sqrt(sum(rhoatm**2))
      end if
!
!  AG: The initialization of doping structs could be done here now,
!      in the uniform distribution, and with a simple loop over
!      rhoatm.
        if (frstme) call initialize_doping_uniform()
        if (doping_active) then
           call compute_doping_structs_uniform(ntpl,rhoatm,nsd)
           ! Will get the global number of hit points
           ! Then, the doping density to be added can be simply computed
        endif
!     Allocate Temporal array
      call re_alloc( Vscf, 1, ntpl, 1, nspin, 'Vscf', 'dhscf_init' )
!     Vscf is filled here but not used later
!     Uharrs is computed (and saved)
!     DStres is computed but not used later
      call poison( cell, ntml(1), ntml(2), ntml(3), ntm, rhoatm,
     &             Uharrs, Vscf, DStres, nsm )
      call de_alloc( Vscf, 'Vscf', 'dhscf_init' )
!     Always deallocate rhoatm_par, as it was used even if nodes=1
      call de_alloc( rhoatm_par, 'rhoatm_par', 'dhscf_init' )
      if (mix_charge) then
         call re_alloc( rhog, 1, 2, 1, ntpl, 1, nspin,
     $                 'Rhog', 'dhscf_init' )
         call re_alloc( rhog_in, 1, 2, 1, ntpl, 1, nspin,
     $                 'Rhog_in', 'dhscf_init' )
         call order_rhog(cell, ntml(1), ntml(2), ntml(3), ntm, nsm)
      endif
!     Stop time counter for atomic initializations
      call timer( 'DHSCF2', 2 )
! ----------------------------------------------------------------------
!     At the end of initializations:
!     We are in the UNIFORM distribution
!     Rhoatm, Rhopcc and Vna are in UNIFORM dist, sequential form
!     The index array endpht is in the QUADRATIC distribution
! ----------------------------------------------------------------------
      if (frstme) then
         call initialize_efield()
      end if
      ! Check if we need to add the potential
      ! corresponding to the voltage-drop.
      if ( TSmode ) then
        ! These routines are important if there are cell-changes
        call ts_init_hartree_fix( cell, nua, xa, ntm, ntml)
        if ( IsVolt ) then
           call ts_init_voltage( cell, nua, xa, ntm)
        end if
        if ( acting_efield ) then
         ! We do not allow the electric field for
         ! transiesta runs with V = 0, either.
         ! It does not make sense, only for fields perpendicular
         ! to the applied bias.
         ! We need to check that the e-field is perpendicular
         ! to the transport direction, and that the system is
         ! either a chain, or a slab.
         ! However, due to the allowance of a dipole correction
         ! along the transport direction for buffer calculations
         ! we have to allow all shapes. (atom is not transiesta
         ! compatible anyway)
         ! check that we do not violate the periodicity
         if ( Node .eq. 0 ) then
            write(*,'(/,2(2a,/))') 'ts-WARNING: ',
     &           'E-field/dipole-correction! ',
     &           'ts-WARNING: ',
     &           'I hope you know what you are doing!'
         end if
         ! This is either dipole or user, or both
         field(:) = user_specified_field(:)
         do iE = 1 , N_Elec
            field2 = Elecs(iE)%cell(:,Elecs(iE)%t_dir)
            ortho = ddot(3,field2,1,field,1)
            if ( abs(ortho) > 1.e-9_dp ) then
               call die('User defined E-field must be
     &perpendicular to semi-infinite directions')
            end if
         end do
        end if ! acting_efield
        ! We know that we currently allow people to do more than
        ! they probably should be allowed. However, there are many
        ! corner cases that may require dipole corrections, or
        ! electric fields to "correct" an intrinsic dipole.
        ! For instance, what should we do with a dipole in a transiesta
        ! calculation?
        ! Should we apply a field to counter act it in a device
        ! calculation?
      end if
      frstme = .false.
      call timer( 'DHSCF_Init', 2 )
#ifdef DEBUG
      call write_debug( '    POS dhscf_init' )
#endif
!------------------------------------------------------------------------- END
      end subroutine dhscf_init
Call graph
dhscf_init calls volcel, ts_init_voltage, re_alloc, de_alloc, fdf_get, setupextmesh, distriphionmesh, rcore, initmesh, leqi, setmeshdistr, initatommesh, fdf_integer, init_hartree_add, ts_init_hartree_fix, partialcoreonmesh, die, digcel, reord, init_mesh_node, setgga, phionmesh, rcut, initialize_efield, createlocaldscfpointers, init_charge_add, neutralatomonmesh, distmeshdata, elecs, timer, shaper, user_specified_field, rhooda, write_debug, cdf_init_mesh, set_box_limits, getxc, compute_doping_structs_uniform, ddot
rcore calls chk
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush
reord calls re_alloc, de_alloc, timer
rcut calls chk
distmeshdata calls distmeshdata_int, distmeshdata_rea
rhooda calls rcut, write_debug, indxuo, endpht, phi, lstpht, phiatm, listp2
chk calls die
phiatm calls floating, rad_get, rlylm
distmeshdata_int calls re_alloc, de_alloc, die, boxintersection
distmeshdata_rea calls re_alloc, de_alloc, die, reord, timer, write_debug, mpitrace_event, boxintersection, mpi_barrier
floating calls izofis
rad_get calls splint
izofis calls chk
setup_h0 calls dhscf_init