die – SIESTA
die Subroutine
29 statements
Source File
public subroutine die(str)
Uses
parallel
siesta_cml
mpi_siesta
Prints an error message and calls MPI_Abort
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: str
Calls
Called by
Contents
Source Code
die
Source Code
      subroutine die(str)
        !! Prints an error message and calls MPI_Abort
      use parallel, only : Node
      use siesta_cml
#ifdef MPI
      use mpi_siesta
#endif
      character(len=*), intent(in), optional   :: str
      external ::  io_assign, io_close
      integer  ::  lun
#ifdef MPI
      integer MPIerror
#endif
! Even though formally (in MPI 1.X), only the master node
! can do I/O, in those systems that allow it having each
! node state its complaint can be useful.
!                                        if (Node.eq.0) then
      if (present(str)) then
         write(6,'(a)') trim(str)
         write(0,'(a)') trim(str)
      endif
      write(6,'(a,i4)') 'Stopping Program from Node: ', Node
      write(0,'(a,i4)') 'Stopping Program from Node: ', Node
!                                        endif
      if (Node .eq. 0) then
         call io_assign( lun )
         open(lun,file="MESSAGES",status="unknown",
     $        position="append",action="write")
         write(lun,"(a)") 'FATAL: ' // trim(str)
         call io_close(lun)
         call pxfflush(6)
         call pxfflush(0)
         If (cml_p) Then
            Call cmlFinishFile(mainXML)
         Endif                  !cml_p
      endif
#ifdef MPI
      call MPI_Abort(MPI_Comm_World,1,MPIerror)
      stop
#else
      call pxfabort()
#endif
      end subroutine die
Call graph
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush
dhscf_init calls die, rcore, distmeshdata, rcut, rhooda
state_init calls die
chk calls die
distmeshdata_rea calls die
dfscf calls die, rcut
distextmeshdata calls die
zetafio calls die, chk
kbproj_gindex calls die, chk
dhscf calls die, dfscf, rhoofd, distmeshdata, vmat, forhar
initmeshdistr calls die
distmeshdata_int calls die
rhoofd calls die, rcut
setup_hamiltonian calls die, dhscf
read_rho calls die
all_phi calls die, chk, floating
nkbfis calls chk
psch calls chk, floating
uion calls chk
labelfis calls chk
zvalfis calls chk
nkbl_func calls chk
atmpopfio calls chk
rcore calls chk
lmxkbfis calls chk
setup_h0 calls dhscf_init, uion
cnfigfio calls chk
massfis calls chk
lofio calls chk
vna_gindex calls chk
lomaxfis calls chk
nztfl calls chk
vna_sub calls chk, floating
ldau_gindex calls chk
chcore_sub calls chk, floating
mofio calls chk
siesta_analysis calls dhscf
distmeshdata calls distmeshdata_rea, distmeshdata_int
psover calls chk, floating
nofis calls chk
orb_gindex calls chk
izofis calls chk
siesta_forces calls state_init, setup_hamiltonian
symfio calls chk, lofio, mofio
rcut calls chk
rchlocal calls chk
delk calls rcut
vmat calls rcut
rhooda calls rcut, phiatm
floating calls izofis
forhar calls distmeshdata
phiatm calls floating
delk_wrapper calls delk
rphiatm calls floating