distMeshData_int – SIESTA
distMeshData_int Subroutine
132 statements
Source File
private subroutine distMeshData_int(iDistr, fsrc, oDistr, fdst, itr)
Uses
mpi_siesta
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iDistr
integer, intent(in) :: fsrc(*)
integer, intent(in) :: oDistr
integer, intent(out) :: fdst(*)
integer, intent(in) :: itr
Calls
Called by
Contents
Source Code
distMeshData_int
Source Code
      subroutine distMeshData_int( iDistr, fsrc, oDistr, fdst, itr )
#ifdef MPI
      use mpi_siesta
#endif
      implicit none
!     Passed arguments
      integer,  intent(in) :: iDistr, oDistr, itr
      integer,  intent(in) :: fsrc(*)
      integer, intent(out) :: fdst(*)
!     Local variables
      character(len=*), parameter :: myName = moduName//'distMeshData '
      character(len=*), parameter :: errMsg = myName//'ERROR: '
      integer                     :: I1, I2, I3, J1, J2, J3, K1, K2, K3,
     &                               ind, ncom, icom, NSRC(3), NDST(3),
     &                               ME, MaxSize, Xsize, Ysize, Zsize,
     &                               Lbox(2,3)
      integer, pointer            :: src(:), dst(:), Sbox(:,:),
     &                               Dbox(:,:)
      type(meshDisType),  pointer :: idis, odis
      logical                     :: inters
      integer,            pointer :: TBUF(:)
#ifdef MPI
      integer                     :: MPIerror, Status(MPI_Status_Size)
#endif
      if (nodes == 1) then
         call die("Called _int version of distMeshData for n=1")
      else
!       The communications are stored in a triangular structure.
        if (iDistr.gt.oDistr) then
          ind  = ((iDistr-1)*(iDistr-2))/2 + oDistr
          ncom = meshCommu(ind)%ncom
          src => meshCommu(ind)%dst
          dst => meshCommu(ind)%src
        else
          ind = ((oDistr-1)*(oDistr-2))/2 + iDistr
          ncom = meshCommu(ind)%ncom
          src => meshCommu(ind)%src
          dst => meshCommu(ind)%dst
        endif
        idis => meshDistr(iDistr)
        odis => meshDistr(oDistr)
        ME  = Node + 1
!       Compute the maximum size of the buffer needed to transfer data
!       among the several processes
        maxSize = 0
        do icom= 1, ncom
          if (src(icom).ne.dst(icom)) then
            Sbox => idis%box(:,:,src(icom))
            Dbox => odis%box(:,:,dst(icom))
            call boxIntersection( Sbox, Dbox, Lbox, inters )
            Xsize = Lbox(2,1) - Lbox(1,1) + 1
            Ysize = Lbox(2,2) - Lbox(1,2) + 1
            Zsize = Lbox(2,3) - Lbox(1,3) + 1
            MaxSize = max(MaxSize,Xsize*Ysize*Zsize)
          endif
        enddo
        if (MaxSize.gt.0) then
          nullify( TBUF )
          call re_alloc( TBUF, 1, MaxSize, 'TBUF', 'moreMeshSubs' )
        endif
        Sbox => idis%box(:,:,ME)
        NSRC(1) = Sbox(2,1) - Sbox(1,1) + 1
        NSRC(2) = Sbox(2,2) - Sbox(1,2) + 1
        NSRC(3) = Sbox(2,3) - Sbox(1,3) + 1
        Dbox => odis%box(:,:,ME)
        NDST(1) = Dbox(2,1) - Dbox(1,1) + 1
        NDST(2) = Dbox(2,2) - Dbox(1,2) + 1
        NDST(3) = Dbox(2,3) - Dbox(1,3) + 1
        if (itr.eq.0) then
!         From sequencial to sequencial
          do icom= 1, ncom
            Sbox => idis%box(:,:,src(icom))
            Dbox => odis%box(:,:,dst(icom))
            call boxIntersection( Sbox, Dbox, Lbox, inters )
            Xsize = Lbox(2,1) - Lbox(1,1) + 1
            Ysize = Lbox(2,2) - Lbox(1,2) + 1
            Zsize = Lbox(2,3) - Lbox(1,3) + 1
            if (src(icom).eq.ME) then
              if (dst(icom).eq.ME) then
!               SRC and DST are the current process
                J3 = (Lbox(1,3) - Sbox(1,3))*NSRC(1)*NSRC(2)
                K3 = (Lbox(1,3) - Dbox(1,3))*NDST(1)*NDST(2)
                do I3 = 1, Zsize
                  J2 = (Lbox(1,2) - Sbox(1,2))*NSRC(1)
                  K2 = (Lbox(1,2) - Dbox(1,2))*NDST(1)
                  do I2 = 1, Ysize
                    J1 = Lbox(1,1) - Sbox(1,1) + 1 + J2 + J3
                    K1 = Lbox(1,1) - Dbox(1,1) + 1 + K2 + K3
                    do I1 = 1, Xsize
                      fdst(K1) = fsrc(J1)
                      K1 = K1 + 1
                      J1 = J1 + 1
                    enddo
                    J2 = J2 + NSRC(1)
                    K2 = K2 + NDST(1)
                  enddo
                  J3 = J3 + NSRC(1)*NSRC(2)
                  K3 = K3 + NDST(1)*NDST(2)
                enddo
              else
!               We should send data to process dst(icom)-1
                J3 = (Lbox(1,3) - Sbox(1,3))*NSRC(1)*NSRC(2)
                K1 = 1
                do I3 = 1, Zsize
                  J2 = (Lbox(1,2) - Sbox(1,2))*NSRC(1)
                  do I2 = 1, Ysize
                    J1 = Lbox(1,1) - Sbox(1,1) + 1 + J2 + J3
                    do I1 = 1, Xsize
                      TBUF(K1) = fsrc(J1)
                      K1 = K1 + 1
                      J1 = J1 + 1
                    enddo
                    J2 = J2 + NSRC(1)
                  enddo
                  J3 = J3 + NSRC(1)*NSRC(2)
                enddo
#ifdef MPI
                call MPI_Send( TBUF, Xsize*Ysize*Zsize,
     &                         MPI_Integer, dst(icom)-1, 1,
     &                         MPI_Comm_world, MPIerror )
#endif
              endif
            else
!             We should receive data from process src(icom)-1
#ifdef MPI
              call mpi_recv( TBUF, Xsize*Ysize*Zsize,
     &                       MPI_Integer, src(icom)-1, 1,
     &                       MPI_Comm_world, Status, MPIerror )
#endif
              J1 = 1
              K3 = (Lbox(1,3) - Dbox(1,3))*NDST(1)*NDST(2)
              do I3 = 1, Zsize
                K2 = (Lbox(1,2) - Dbox(1,2))*NDST(1)
                do I2 = 1, Ysize
                  K1 = Lbox(1,1) - Dbox(1,1) + 1 + K2 + K3
                  do I1 = 1, Xsize
                    fdst(K1) = TBUF(J1)
                    K1 = K1 + 1
                    J1 = J1 + 1
                  enddo
                  K2 = K2 + NDST(1)
                enddo
                K3 = K3 + NDST(1)*NDST(2)
              enddo
            endif
          enddo
        else
          if (Node.eq.0) then
            write(*,*)'ERROR: Wrong parameter for function distMeshData'
          endif
          call die()
        endif
        if (MaxSize.gt.0) then
          call de_alloc( TBUF, 'TBUF', 'moreMeshSubs' )
        endif
      endif
      end subroutine distMeshData_int
Call graph
distmeshdata_int calls re_alloc, boxintersection, de_alloc, die
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush
distmeshdata calls distmeshdata_int
dhscf_init calls distmeshdata
dhscf calls distmeshdata, forhar
forhar calls distmeshdata
siesta_analysis calls dhscf
setup_hamiltonian calls dhscf
setup_h0 calls dhscf_init
siesta_forces calls setup_hamiltonian