distMeshData_rea – SIESTA
distMeshData_rea Subroutine
358 statements
Source File
private subroutine distMeshData_rea(iDistr, fsrc, oDistr, fdst, itr)
Uses
mesh
mpi_siesta
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iDistr
real(kind=grid_p), intent(in) :: fsrc(*)
integer, intent(in) :: oDistr
real(kind=grid_p), intent(out) :: fdst(*)
integer, intent(in) :: itr
Calls
Contents
Source Code
distMeshData_rea
Source Code
      subroutine distMeshData_rea( iDistr, fsrc, oDistr, fdst, itr )
      use mesh,    only : nsm, nmeshg
#ifdef MPI
      use mpi_siesta
#endif
      implicit none
!     Passed arguments
      integer,         intent(in) :: iDistr, oDistr, itr
      real(grid_p),    intent(in) :: fsrc(*)
      real(grid_p),   intent(out) :: fdst(*)
!     Local variables
      integer                     :: i, I1, I2, I3, N1, N2, N3, NN, ind,
     &                               J1, J2, J3, K1, K2, K3, KS, KR,
     &                               icom, ncom, nsp, me, nsize, lsize,
     &                               NSRC(3), NDST(3), Lbox(2,3), ierr,
     &                               nm(3), status(MPI_Status_Size),
     &                               Xsize, Ysize, Zsize
      logical                     :: inters
      integer,            pointer :: request(:), src(:), dst(:),
     &                               Sbox(:,:), Dbox(:,:), JS(:)
      real(grid_p),       pointer :: sBuff(:), rBuff(:)
      type(meshDisType),  pointer :: idis, odis
#ifdef DEBUG
      call write_debug( '    PRE distMeshData' )
#endif
#ifdef _TRACE_
      call MPI_Barrier( MPI_Comm_World, ierr )
      call MPItrace_event( 1000, 6 )
#endif
      call timer( 'COMM_BSC', 1 )
      nm(1:3) = nmeshg(1:3) / nsm
      if (nodes == 1) then
        if (itr.gt.0) then
          ! Note that in reord the first argument is always
          ! clustered
          call reord( fsrc, fdst, nm, nsm, TO_SEQUENTIAL )
        else if (itr .lt. 0) then
          call reord( fdst, fsrc, nm, nsm, TO_CLUSTER )
        else
          ! Copy source to destination
          ! This will be executed only in serial mode,
          ! so we know that the size is the total number
          ! of (small) points, but maybe this information
          ! should be more explicit.
          nsize = product(nmeshg(1:3))
          fdst(1:nsize) = fsrc(1:nsize)
        endif
      else  ! nodes > 1
!       The communications are stored in a triangular structure.
        if (iDistr.gt.oDistr) then
          ind  = ((iDistr-1)*(iDistr-2))/2 + oDistr
          ncom = meshCommu(ind)%ncom
          src => meshCommu(ind)%dst
          dst => meshCommu(ind)%src
        else
          ind = ((oDistr-1)*(oDistr-2))/2 + iDistr
          ncom = meshCommu(ind)%ncom
          src => meshCommu(ind)%src
          dst => meshCommu(ind)%dst
        endif
        nullify( request )
        call re_alloc( request, 1, ncom, 'request', 'distmeshdata' )
        idis => meshDistr(iDistr)
        odis => meshDistr(oDistr)
        nsp = nsm*nsm*nsm
        me  = node + 1
        nullify( JS )
        call re_alloc( JS, 1, nsp, 'JS', 'distmeshdata' )
        if (iDistr.eq.UNIFORM) then
          sBuff => tBuff1(:)
          rBuff => tBuff2(:)
        else
          if (oDistr.eq.UNIFORM) then
            sBuff => tBuff2(:)
            rBuff => tBuff1(:)
          else
!           Asynchronous buffers are sized to move data from/to
!           UNIFORM distribution. Check subroutine allocASynBuffer
!           to contemplate different cases
            call die( 'Asynchronous temporal buffer error' )
          endif
        endif
        Sbox => idis%box(:,:,ME)
        NSRC(1) = (Sbox(2,1) - Sbox(1,1) + 1)*nsm
        NSRC(2) = (Sbox(2,2) - Sbox(1,2) + 1)*nsm
        NSRC(3) = (Sbox(2,3) - Sbox(1,3) + 1)*nsm
        Dbox => odis%box(:,:,ME)
        NDST(1) = (Dbox(2,1) - Dbox(1,1) + 1)*nsm
        NDST(2) = (Dbox(2,2) - Dbox(1,2) + 1)*nsm
        NDST(3) = (Dbox(2,3) - Dbox(1,3) + 1)*nsm
        if (itr.eq.1) then
!         From clustered to sequential
          NN = 1
          I3 = 0
          DO N3=0, NSM-1
            I2 = 0
            DO N2= 0, NSM-1
              I1 = I2 + I3
              DO N1= 0, NSM-1
                JS(NN) = I1
                NN     = NN + 1
                I1     = I1 + 1
              ENDDO
              I2 = I2 + NDST(1)
            ENDDO
            I3 = I3 + NDST(1)*NDST(2)
          ENDDO
          KS = 1
          KR = 1
          do icom= 1, ncom
            Sbox => idis%box(:,:,src(icom))
            Dbox => odis%box(:,:,dst(icom))
            call boxIntersection( Sbox, Dbox, Lbox, inters )
            if (src(icom).eq.ME) then
              if (dst(icom).eq.ME) then
!               SRC and DST are the current process
                J3 = (Lbox(1,3) - Sbox(1,3))*NSRC(1)*NSRC(2)*NSM
                K3 = (Lbox(1,3) - Dbox(1,3))*NDST(1)*NDST(2)*NSM
                do I3 = Lbox(1,3), Lbox(2,3)
                  J2 = (Lbox(1,2) - Sbox(1,2))*NSRC(1)*NSM*NSM
                  K2 = (Lbox(1,2) - Dbox(1,2))*NDST(1)*NSM
                  do I2 = Lbox(1,2), Lbox(2,2)
                    J1 = (Lbox(1,1) - Sbox(1,1))*NSP + 1 + J2 + J3
                    K1 = (Lbox(1,1) - Dbox(1,1))*NSM + 1 + K2 + K3
                    do I1 = Lbox(1,1), Lbox(2,1)
                      DO NN= 1, NSP
                        fdst(K1+JS(NN)) = fsrc(J1)
                        J1 = J1 + 1
                      ENDDO
                      K1 = K1 + NSM
                    enddo
                    J2 = J2 + NSRC(1)*NSM*NSM
                    K2 = K2 + NDST(1)*NSM
                  enddo
                  J3 = J3 + NSRC(1)*NSRC(2)*NSM
                  K3 = K3 + NDST(1)*NDST(2)*NSM
                enddo
              else
!               We should send data to process dst(icom)-1
                lsize = (Lbox(2,1) - Lbox(1,1) + 1)*
     &                  (Lbox(2,2) - Lbox(1,2) + 1)*
     &                  (Lbox(2,3) - Lbox(1,3) + 1)*nsp
                J3 = (Lbox(1,3) - Sbox(1,3))*NSRC(1)*NSRC(2)*NSM
                K1 = KS
                do I3 = Lbox(1,3), Lbox(2,3)
                  J2 = (Lbox(1,2) - Sbox(1,2))*NSRC(1)*NSM*NSM
                  do I2 = Lbox(1,2), Lbox(2,2)
                    J1 = (Lbox(1,1) - Sbox(1,1))*NSP + 1 + J2 + J3
                    do I1 = Lbox(1,1), Lbox(2,1)
                      DO NN= 1, NSP
                        sBuff(K1) = fsrc(J1)
                        J1 = J1 + 1
                        K1 = K1 + 1
                      ENDDO
                    enddo
                    J2 = J2 + NSRC(1)*NSM*NSM
                  enddo
                  J3 = J3 + NSRC(1)*NSRC(2)*NSM
                enddo
#ifdef MPI
                call mpi_isend( sBuff(KS), lsize, MPI_grid_real,
     &                          dst(icom)-1, 0, MPI_COMM_WORLD,
     &                          request(icom), ierr )
#endif
                KS = K1
              endif
            else
!             We should receive data from process src(icom)-1
              lsize = (Lbox(2,1) - Lbox(1,1) + 1)*
     &                (Lbox(2,2) - Lbox(1,2) + 1)*
     &                (Lbox(2,3) - Lbox(1,3) + 1)*nsp
#ifdef MPI
              call mpi_irecv( rBuff(KR), lsize, MPI_grid_real,
     &                        src(icom)-1, 0, MPI_COMM_WORLD,
     &                        request(icom), ierr )
#endif
              KR = KR + lsize
            endif
          enddo
          J1 = 1
          do icom= 1, ncom
!           Wait for received data and move it to the destination buffer
            if (src(icom).ne.ME) then
              Sbox => idis%box(:,:,src(icom))
              Dbox => odis%box(:,:,dst(icom))
              call boxIntersection( Sbox, Dbox, Lbox, inters )
#ifdef MPI
              CALL MPI_WAIT( request(icom), status, ierr )
#endif
              K3 = (Lbox(1,3) - Dbox(1,3))*NDST(1)*NDST(2)*NSM
              do I3 = Lbox(1,3), Lbox(2,3)
                K2 = (Lbox(1,2) - Dbox(1,2))*NDST(1)*NSM
                do I2 = Lbox(1,2), Lbox(2,2)
                  K1 = (Lbox(1,1) - Dbox(1,1))*NSM + 1 + K2 + K3
                  do I1 = Lbox(1,1), Lbox(2,1)
                    DO NN= 1, NSP
                      fdst(K1+JS(NN)) = rBuff(J1)
                      J1 = J1 + 1
                    ENDDO
                    K1 = K1 + NSM
                  enddo
                  K2 = K2 + NDST(1)*NSM
                enddo
                K3 = K3 + NDST(1)*NDST(2)*NSM
              enddo
            endif
          enddo
        else if (itr.eq.-1) then
!         From sequencial to clustered
          NN = 1
          I3 = 0
          DO N3=0, NSM-1
            I2 = 0
            DO N2= 0, NSM-1
              I1 = I2 + I3
              DO N1= 0, NSM-1
                JS(NN) = I1
                NN     = NN + 1
                I1     = I1 + 1
              ENDDO
              I2 = I2 + NSRC(1)
            ENDDO
            I3 = I3 + NSRC(1)*NSRC(2)
          ENDDO
          KS = 1
          KR = 1
          do icom= 1, ncom
            Sbox => idis%box(:,:,src(icom))
            Dbox => odis%box(:,:,dst(icom))
            call boxIntersection( Sbox, Dbox, Lbox, inters )
            if (src(icom).eq.ME) then
              if (dst(icom).eq.ME) then
!               SRC and DST are the current process
                J3 = (Lbox(1,3) - Sbox(1,3))*NSRC(1)*NSRC(2)*NSM
                K3 = (Lbox(1,3) - Dbox(1,3))*NDST(1)*NDST(2)*NSM
                do I3 = Lbox(1,3), Lbox(2,3)
                  J2 = (Lbox(1,2) - Sbox(1,2))*NSRC(1)*NSM
                  K2 = (Lbox(1,2) - Dbox(1,2))*NDST(1)*NSM*NSM
                  do I2 = Lbox(1,2), Lbox(2,2)
                    J1 = (Lbox(1,1) - Sbox(1,1))*NSM + 1 + J2 + J3
                    K1 = (Lbox(1,1) - Dbox(1,1))*NSP + 1 + K2 + K3
                    do I1 = Lbox(1,1), Lbox(2,1)
                      DO NN= 1, NSP
                        fdst(K1) = fsrc(J1+JS(NN))
                        K1 = K1 + 1
                      ENDDO
                      J1 = J1 + NSM
                    enddo
                    J2 = J2 + NSRC(1)*NSM
                    K2 = K2 + NDST(1)*NSM*NSM
                  enddo
                  J3 = J3 + NSRC(1)*NSRC(2)*NSM
                  K3 = K3 + NDST(1)*NDST(2)*NSM
                enddo
              else
!               We should send data to process dst(icom)-1
                lsize = (Lbox(2,1) - Lbox(1,1) + 1)*
     &                  (Lbox(2,2) - Lbox(1,2) + 1)*
     &                  (Lbox(2,3) - Lbox(1,3) + 1)*nsp
                J3 = (Lbox(1,3) - Sbox(1,3))*NSRC(1)*NSRC(2)*NSM
                K1 = KS
                do I3 = Lbox(1,3), Lbox(2,3)
                  J2 = (Lbox(1,2) - Sbox(1,2))*NSRC(1)*NSM
                  do I2 = Lbox(1,2), Lbox(2,2)
                    J1 = (Lbox(1,1) - Sbox(1,1))*NSM + 1 + J2 + J3
                    do I1 = Lbox(1,1), Lbox(2,1)
                      DO NN= 1, NSP
                        sBuff(K1) = fsrc(J1+JS(NN))
                        K1 = K1 + 1
                      ENDDO
                      J1 = J1 + NSM
                    enddo
                    J2 = J2 + NSRC(1)*NSM
                  enddo
                  J3 = J3 + NSRC(1)*NSRC(2)*NSM
                enddo
#ifdef MPI
                call mpi_isend( sBuff(KS), lsize, MPI_grid_real,
     &                          dst(icom)-1, 0, MPI_COMM_WORLD,
     &                          request(icom), ierr )
#endif
                KS = K1
              endif
            else
C             We should receive data from process src(icom)-1
              lsize = (Lbox(2,1) - Lbox(1,1) + 1)*
     &                (Lbox(2,2) - Lbox(1,2) + 1)*
     &                (Lbox(2,3) - Lbox(1,3) + 1)*nsp
#ifdef MPI
              call mpi_irecv( rBuff(KR), lsize, MPI_grid_real,
     &                        src(icom)-1, 0, MPI_COMM_WORLD,
     &                        request(icom), ierr )
#endif
              KR = KR + lsize
            endif
          enddo
          J1 = 1
          do icom= 1, ncom
!           Wait for received data and move it to the destination buffer
            if (src(icom).ne.ME) then
              Sbox => idis%box(:,:,src(icom))
              Dbox => odis%box(:,:,dst(icom))
              call boxIntersection( Sbox, Dbox, Lbox, inters )
#ifdef MPI
              CALL MPI_WAIT( request(icom), status, ierr )
#endif
              K3 = (Lbox(1,3) - Dbox(1,3))*NDST(1)*NDST(2)*NSM
              do I3 = Lbox(1,3), Lbox(2,3)
                K2 = (Lbox(1,2) - Dbox(1,2))*NDST(1)*NSM*NSM
                do I2 = Lbox(1,2), Lbox(2,2)
                  K1 = (Lbox(1,1) - Dbox(1,1))*NSP + 1 + K2 + K3
                  do I1 = Lbox(1,1), Lbox(2,1)
                    DO NN= 1, NSP
                      fdst(K1) = rBuff(J1)
                      K1 = K1 + 1
                      J1 = J1 + 1
                    ENDDO
                  enddo
                  K2 = K2 + NDST(1)*NSM*NSM
                enddo
                K3 = K3 + NDST(1)*NDST(2)*NSM
              enddo
            endif
          enddo
        else if (itr.eq.0) then
          KS = 1
          KR = 1
!         From sequencial to sequencial or from clustered to clustered
          do icom= 1, ncom
            Sbox => idis%box(:,:,src(icom))
            Dbox => odis%box(:,:,dst(icom))
            call boxIntersection( Sbox, Dbox, Lbox, inters )
            Xsize = (Lbox(2,1)-Lbox(1,1)+1)*NSM
            Ysize = (Lbox(2,2)-Lbox(1,2)+1)*NSM
            Zsize = (Lbox(2,3)-Lbox(1,3)+1)*NSM
            if (src(icom).eq.ME) then
              if (dst(icom).eq.ME) then
!               SRC and DST are the current process
                J3 = (Lbox(1,3) - Sbox(1,3))*NSRC(1)*NSRC(2)*NSM
                K3 = (Lbox(1,3) - Dbox(1,3))*NDST(1)*NDST(2)*NSM
                do I3 = 1, Zsize
                  J2 = (Lbox(1,2) - Sbox(1,2))*NSRC(1)*NSM
                  K2 = (Lbox(1,2) - Dbox(1,2))*NDST(1)*NSM
                  do I2 = 1, Ysize
                    J1 = (Lbox(1,1) - Sbox(1,1))*NSM + 1 + J2 + J3
                    K1 = (Lbox(1,1) - Dbox(1,1))*NSM + 1 + K2 + K3
                    do I1 = 1, Xsize
                      fdst(K1) = fsrc(J1)
                      K1 = K1 + 1
                      J1 = J1 + 1
                    enddo
                    J2 = J2 + NSRC(1)
                    K2 = K2 + NDST(1)
                  enddo
                  J3 = J3 + NSRC(1)*NSRC(2)
                  K3 = K3 + NDST(1)*NDST(2)
                enddo
              else
!               We should send data to process dst(icom)-1
                lsize = Xsize*Ysize*Zsize
                J3 = (Lbox(1,3) - Sbox(1,3))*NSRC(1)*NSRC(2)*NSM
                K1 = KS
                do I3 = 1, Zsize
                  J2 = (Lbox(1,2) - Sbox(1,2))*NSRC(1)*NSM
                  do I2 = 1, Ysize
                    J1 = (Lbox(1,1) - Sbox(1,1))*NSM + 1 + J2 + J3
                    do I1 = 1, Xsize
                      sBuff(K1) = fsrc(J1)
                      K1 = K1 + 1
                      J1 = J1 + 1
                    enddo
                    J2 = J2 + NSRC(1)
                  enddo
                  J3 = J3 + NSRC(1)*NSRC(2)
                enddo
#ifdef MPI
                call mpi_isend( sBuff(KS), lsize, MPI_grid_real,
     &                          dst(icom)-1, 0, MPI_COMM_WORLD,
     &                          request(icom), ierr )
#endif
                KS = K1
              endif
            else
!             We should receive data from process src(icom)-1
              lsize = Xsize*Ysize*Zsize
#ifdef MPI
              call mpi_irecv( rBuff(KR), lsize, MPI_grid_real,
     &                        src(icom)-1, 0, MPI_COMM_WORLD,
     &                        request(icom), ierr )
#endif
              KR = KR + lsize
            endif
          enddo
          J1 = 1
          do icom= 1, ncom
!           Wait for received data and move it to the destination buffer
            if (src(icom).ne.ME) then
              Sbox => idis%box(:,:,src(icom))
              Dbox => odis%box(:,:,dst(icom))
              call boxIntersection( Sbox, Dbox, Lbox, inters )
              Xsize = (Lbox(2,1)-Lbox(1,1)+1)*NSM
              Ysize = (Lbox(2,2)-Lbox(1,2)+1)*NSM
              Zsize = (Lbox(2,3)-Lbox(1,3)+1)*NSM
#ifdef MPI
              CALL MPI_WAIT( request(icom), status, ierr )
#endif
              K3 = (Lbox(1,3) - Dbox(1,3))*NDST(1)*NDST(2)*NSM
              do I3 = 1, Zsize
                K2 = (Lbox(1,2) - Dbox(1,2))*NDST(1)*NSM
                do I2 = 1, Ysize
                  K1 = (Lbox(1,1) - Dbox(1,1))*NSM + 1 + K2 + K3
                  do I1 = 1, Xsize
                    fdst(K1) = rBuff(J1)
                    K1 = K1 + 1
                    J1 = J1 + 1
                  enddo
                  K2 = K2 + NDST(1)
                enddo
                K3 = K3 + NDST(1)*NDST(2)
              enddo
            endif
          enddo
        else
          if (Node.eq.0) then
            write(*,*)'ERROR: Wrong parameter for function distMeshData'
          endif
          call die()
        endif
        call de_alloc( JS,      'JS',      'distmeshdata' )
        call de_alloc( request, 'request', 'distmeshdata' )
      endif
#ifdef _TRACE_
      call MPI_Barrier( MPI_Comm_World, ierr )
      call MPItrace_event( 1000, 0 )
#endif
      call timer( 'COMM_BSC', 2 )
#ifdef DEBUG
      call write_debug( '    POS distMeshData' )
#endif
      end subroutine distMeshData_rea
Call graph
distmeshdata_rea calls mpitrace_event, boxintersection, reord, re_alloc, timer, mpi_barrier, de_alloc, write_debug, die
reord calls re_alloc, timer, de_alloc
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush