initMeshDistr – SIESTA
initMeshDistr Subroutine
85 statements
Source File
public subroutine initMeshDistr(iDistr, oDistr, nm, wload)
Computes a new data distribution and the communications needed to move data from/to the current distribution to the existing ones.
The limits of the new distributions are stored in the current module in meshDistr:
 meshDistr(oDistr)
 meshCommu(((oDistr-2)*(oDistr-1))/2+1:(oDistr-1)*oDistr/2)
If this is the first distribution, we split the mesh uniformly among the several processes (we only split it in dimensions Y and Z).
For the other data distributions we should split the vector wload. The subroutine splitwload will return the limits of the new data distribution. The subroutine compMeshComm will return the communications needed to move data from/to the current distribution to/from the previous ones.
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: iDistr
Distribution index of the input vector
integer, intent(in) :: oDistr
The new data distribution index
integer, intent(in) :: nm(3)
Number of Mesh divisions of each cell vector
integer, intent(in), optional :: wload(*)
Weights of every point of the mesh using the input distribut !ion
Calls
Contents
Source Code
initMeshDistr
Source Code
      subroutine initMeshDistr( iDistr, oDistr, nm, wload )
!! Computes a new data distribution and the communications needed to
!! move data from/to the current distribution to the existing ones.
!!
!! The limits of the new distributions are stored in the current module
!! in `[[moreMeshSubs(module):meshDistr(variable)]]`:
!!
!!     meshDistr(oDistr)
!!     meshCommu(((oDistr-2)*(oDistr-1))/2+1:(oDistr-1)*oDistr/2)
!!
!! If this is the first distribution, we split the mesh uniformly among
!! the several processes (we only split it in dimensions Y and Z).
!!
!! For the other data distributions we should split the vector wload.
!! The subroutine splitwload will return the limits of the new data
!! distribution. The subroutine compMeshComm will return the communications
!! needed to move data from/to the current distribution to/from the
!! previous ones.
      implicit none
      integer, optional,  intent(in) :: iDistr
        !!  Distribution index of the input vector
      integer,            intent(in) :: oDistr
        !!  The new data distribution index
      integer,            intent(in) :: nm(3)
        !!  Number of Mesh divisions of each cell vector
      integer, optional,  intent(in) :: wload(*)
        !!  Weights of every point of the mesh using the input distribution
!     Local variables
      character(len=*), parameter :: myName = moduName//'initMeshDistr '
      character(len=*), parameter :: errMsg = myName//'ERROR: '
      integer                     :: ii, jj, PY, PZ, PP, ProcessorZ,
     &                               blocY, blocZ, nremY, nremZ,
     &                               iniY, iniZ, dimY, dimZ, nsize
      type(meshDisType),  pointer :: distr
      logical,               save :: firstime=.true.
      integer, pointer            :: box(:,:,:), mybox(:,:)
      call timer( 'INITMESH', 1 )
!     Check the number of mesh distribution
      if (oDistr.gt.maxDistr)
     &  call die( errMsg // 'oDistr.gt.maxDistr' )
!     Reset data if necessay
      if (firstime) then
        do ii= 1, maxDistr
          nullify(meshDistr(ii)%box)
          nullify(meshDistr(ii)%indexp)
          nullify(meshDistr(ii)%idop)
          nullify(meshDistr(ii)%xdop)
          nullify(meshDistr(ii)%ipa)
        enddo
        do ii= 1, (maxDistr*(maxDistr-1))/2
          nullify(meshCommu(ii)%src)
          nullify(meshCommu(ii)%dst)
        enddo
        do ii= 1, maxDistr
          do jj= 1, 3
            nullify(exteCommu(ii,jj)%src)
            nullify(exteCommu(ii,jj)%dst)
          enddo
        enddo
#ifdef ASYNCHRONOUS
        nullify(tBuff1)
        nullify(tBuff2)
#endif
        firstime = .false.
      endif
      distr => meshDistr(oDistr)
!     Allocate memory for the current distribution
      nullify( distr%box )
      call re_alloc( distr%box, 1, 2, 1, 3, 1, Nodes,
     &               'distr%box', moduName )
!     The first distribution should be the uniform distribution
      if (oDistr.eq.1) then
        ProcessorZ = Nodes/ProcessorY
        blocY = (nm(2)/ProcessorY)
        blocZ = (nm(3)/ProcessorZ)
        nremY = nm(2) - blocY*ProcessorY
        nremZ = nm(3) - blocZ*ProcessorZ
        PP   = 1
        iniY = 1
        do PY = 1, ProcessorY
          dimY = blocY
          if (PY.LE.nremY) dimY = dimY + 1
          iniZ = 1
          do PZ = 1, ProcessorZ
            dimZ = blocZ
            if (PZ.LE.nremZ) dimZ = dimZ + 1
            distr%box(1,1,PP) = 1
            distr%box(2,1,PP) = nm(1)
            distr%box(1,2,PP) = iniY
            distr%box(2,2,PP) = iniY + dimY - 1
            distr%box(1,3,PP) = iniZ
            distr%box(2,3,PP) = iniZ + dimZ - 1
            iniZ = iniZ + dimZ
            PP   = PP + 1
          enddo
          iniY = iniY + dimY
        enddo
      else
!       In order to compute the other data distributions, we should split
!       the vector "wload" among the several processes
#ifdef MPI
        if (.NOT. present(iDistr) .OR.
     &      .NOT. present(wload) ) then
          call die( errMsg // 'Wrong parameters' )
        endif
        call splitwload( Nodes, node+1, nm, wload,
     &                   meshDistr(iDistr), meshDistr(oDistr) )
        call reordMeshNumbering( meshDistr(1), distr )
!       Precompute the communications needed to move data between the new data
!       distribution and the previous ones.
        jj = ((oDistr-2)*(oDistr-1))/2 + 1
        do ii=1, oDistr-1
          call compMeshComm( meshDistr(ii), distr, meshCommu(jj) )
          jj = jj + 1
        enddo
#endif
      endif
      if (Node == 0) then
         write(6,"(a,i3)")"New grid distribution: ", oDistr
         do PP= 1, Nodes
            write(6,"(i12,3x,3(i5,a1,i5))")
     $       PP,
     $       (distr%box(1,jj,PP), ":", distr%box(2,jj,PP), jj=1,3)
         enddo
      endif
      call timer( 'INITMESH', 2 )
      end subroutine initMeshDistr
Call graph
initmeshdistr calls re_alloc, die, timer
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush