initMeshExtencil – SIESTA
initMeshExtencil Subroutine
95 statements
Source File
public subroutine initMeshExtencil(iDistr, nm)
Uses
scheComm
Compute the needed communications in order to send/receive the extencil (when the data is ordered in the distribution iDistr) The results are stored in the variable exteCommu(iDistr,1:3) of the current module.
For every dimension of the problem, search all the neighbors that we have. Given the current data distribution we compute the limits of our extencil and we check its intersection with all the other processes. Once we know all our neighbors we call subroutine scheduleComm in order to minimize the number of communications steps.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iDistr
Distribution index to be used
integer, intent(in) :: nm(3)
Number of Mesh divisions in each cell vector
Calls
Contents
Source Code
initMeshExtencil
Source Code
      subroutine initMeshExtencil( iDistr, nm )
!! Compute the needed communications in order to send/receive the
!! extencil (when the data is ordered in the distribution `iDistr`)
!! The results are stored in the variable
!! `[[moreMeshSubs(module):exteCommu(variable)]](iDistr,1:3)`
!! of the current module.
!!
!! For every dimension of the problem, search all the neighbors that
!! we have. Given the current data distribution we compute the limits
!! of our extencil and we check its intersection with all the other
!! processes. Once we know all our neighbors we call subroutine
!! `[[scheduleComm(proc)]]` in order to minimize the number
!! of communications steps.
      use scheComm
      implicit none
!     Passed arguments
      integer,  intent(in)        :: iDistr
        !! Distribution index to be used
      integer,  intent(in)        :: nm(3)
        !! Number of Mesh divisions in each cell vector
!     Local variables
      integer                     :: Ubox(2,3), Lbox(2,3), Ibox(2,3),
     &                               ii, iaxis, ncom, Gcom, Lcom, P1, P2
      integer,            pointer :: src(:), dst(:), Dbox(:,:)
      type(meshDisType),  pointer :: idis
      type(meshCommType), pointer :: mcomm
      type(COMM_T)                :: comm
      logical                     :: inters
      idis => meshDistr(iDistr)
      do iaxis=1, 3
!       One communication structure for every dimension
        mcomm => exteCommu(iDistr,iaxis)
!       Count the number of communications needed to send/receive
!       the extencil
        ncom = 0
        do P1= 1, Nodes
!         Create the extencil boxes for both sides of the current
!         partition
          Ubox(1:2,1:3) = idis%box(1:2,1:3,P1)
          Ubox(1,iaxis) = Ubox(1,iaxis) - 1
          if (Ubox(1,iaxis).lt.1) Ubox(1,iaxis) = nm(iaxis)
          Ubox(2,iaxis)   = Ubox(1,iaxis)
          Lbox(1:2,1:3) = idis%box(1:2,1:3,P1)
          Lbox(2,iaxis) = Lbox(2,iaxis) + 1
          if (Lbox(2,iaxis).gt.nm(iaxis)) Lbox(2,iaxis) = 1
          Lbox(1,iaxis) = Lbox(2,iaxis)
          do P2= P1+1, Nodes
            Dbox => idis%box(:,:,P2)
            call boxIntersection( Dbox, Ubox, Ibox, inters )
            if (inters) then
              ncom = ncom + 1
            else
              call boxIntersection( Dbox, Lbox, Ibox, inters )
              if (inters) ncom = ncom + 1
            endif
          enddo
        enddo
        Gcom = ncom
!       Create a list of communications needed to send/receive
!       the extencil
        if (Gcom.gt.0) then
          nullify( src, dst )
          call re_alloc( src, 1, Gcom, 'src', 'moreMeshSubs' )
          call re_alloc( dst, 1, Gcom, 'dst', 'moreMeshSubs' )
          ncom = 0
          do P1= 1, Nodes
            Ubox(1:2,1:3) = idis%box(1:2,1:3,P1)
            Ubox(1,iaxis) = Ubox(1,iaxis) - 1
            if (Ubox(1,iaxis).lt.1) Ubox(1,iaxis) = nm(iaxis)
            Ubox(2,iaxis)   = Ubox(1,iaxis)
            Lbox(1:2,1:3) = idis%box(1:2,1:3,P1)
            Lbox(2,iaxis) = Lbox(2,iaxis) + 1
            if (Lbox(2,iaxis).gt.nm(iaxis)) Lbox(2,iaxis) = 1
            Lbox(1,iaxis) = Lbox(2,iaxis)
            do P2= P1+1, Nodes
              Dbox => idis%box(:,:,P2)
              call boxIntersection( Dbox, Ubox, Ibox, inters )
              if (inters) then
                ncom = ncom + 1
                src(ncom) = P1
                dst(ncom) = P2
              else
                call boxIntersection( Dbox, Lbox, Ibox, inters )
                if (inters) then
                  ncom = ncom + 1
                  src(ncom) = P1
                  dst(ncom) = P2
                endif
              endif
            enddo
          enddo
          comm%np = Nodes
!         reschedule the communications in order to minimize the time
          call scheduleComm( Gcom, src, dst, comm )
!         Count the number of communications needed by the current process
          ncom = 0
          do P1= 1, comm%ncol
            if (comm%ind(P1,Node+1).ne.0) ncom = ncom + 1
          enddo
          Lcom = ncom
!         Store the ordered list of communications needed by the current
!         process to send/receive the extencil.
          if (Lcom.gt.0) then
            nullify( mcomm%src, mcomm%dst )
            call re_alloc( mcomm%src, 1, Lcom, 'mcomm%src',
     &                     'moreMeshSubs' )
            call re_alloc( mcomm%dst, 1, Lcom, 'mcomm%dst',
     &                     'moreMeshSubs' )
            ncom = 0
            do P1= 1, comm%ncol
              ii = comm%ind(P1,Node+1)
              if (ii.ne.0) then
                ncom            = ncom + 1
                mcomm%src(ncom) = src(ii)
                mcomm%dst(ncom) = dst(ii)
              endif
            enddo
            mcomm%ncom = Lcom
            call de_alloc( comm%ind, 'comm%ind', 'scheComm' )
          endif
          call de_alloc( dst, 'dst', 'moreMeshSubs' )
          call de_alloc( src, 'src', 'moreMeshSubs' )
        endif
      enddo
      end subroutine initMeshExtencil
Call graph
initmeshextencil calls re_alloc, boxintersection, de_alloc, schedulecomm