IZOFIS – SIESTA
IZOFIS Function
6 statements
Source File
public function IZOFIS(is) result(izofis)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
Species index
Return Value integer
Atomic number
Calls
Called by
Contents
Source Code
IZOFIS
Source Code
      FUNCTION IZOFIS( IS )
      integer :: izofis
        !! Atomic number
      integer, intent(in) :: is
        !! Species index
      call chk('izofis',is)
      izofis = species(is)%z
      end function izofis
Call graph
izofis calls chk
chk calls die
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush
floating calls izofis
psch calls floating
rphiatm calls floating
vna_sub calls floating
psover calls floating
chcore_sub calls floating
phiatm calls floating
all_phi calls floating
rhooda calls phiatm
dhscf_init calls rhooda
setup_h0 calls dhscf_init