kbproj_gindex – SIESTA
kbproj_gindex Function
12 statements
Source File
public function kbproj_gindex(is, io)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
integer, intent(in) :: io
Return Value integer
Calls
Contents
Source Code
kbproj_gindex
Source Code
      FUNCTION kbproj_gindex (IS,IO)
      integer kbproj_gindex
      integer, intent(in) :: is    ! Species index
      integer, intent(in) :: io    ! KBproj index
                                   ! (within atom, <0, for compatibility)
C Returns the global index of a KB projector
      integer :: ko
      call chk('kbproj_gindex',is)
      ko = -io
      if ( (ko .gt. species(is)%nprojs) .or.
     $     (ko .lt. 1)) then
         call die("kbproj_gindex: Wrong io")
      endif
      kbproj_gindex = species(is)%pj_gindex(ko)
      end function kbproj_gindex
Call graph
kbproj_gindex calls chk, die
chk calls die
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush