LOMAXFIS – SIESTA
LOMAXFIS Function
6 statements
Source File
public function LOMAXFIS(is) result(lomaxfis)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
Return Value integer
Calls
Contents
Source Code
LOMAXFIS
Source Code
      FUNCTION LOMAXFIS (IS)
      integer :: lomaxfis  ! Maximum ang mom of the Basis Functions
      integer, intent(in) :: is            ! Species index
      call chk('lomaxfis',is)
      lomaxfis = species(is)%lmax_basis
      end function lomaxfis
Call graph
lomaxfis calls chk
chk calls die
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush