message – SIESTA
message Subroutine
17 statements
Source File
public subroutine message(level, str)
Uses
parallel
Prints a message string if node==0
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: level
One of INFO, WARNING, FATAL
character(len=*), intent(in) :: str
Calls
Called by
Contents
Source Code
message
Source Code
      subroutine message(level,str)
        !! Prints a message string if `node==0`
      use parallel, only : Node
      character(len=*), intent(in)  :: level
        !! One of INFO, WARNING, FATAL
      character(len=*), intent(in)  :: str
      external ::  io_assign, io_close
      integer  ::  lun
      if (Node .eq. 0) then
         write(6,'(a)') trim(str)
         write(0,'(a)') trim(str)
         call io_assign(lun)
         open(lun,file="MESSAGES",status="unknown",
     $        position="append",action="write")
         write(lun,"(a)") trim(level) // ": " // trim(str)
         call io_close(lun)
         call pxfflush(6)
         call pxfflush(0)
      endif
      end subroutine message
Call graph
message calls io_assign, pxfflush, io_close
state_init calls message, check_cohp
check_cohp calls message
siesta_forces calls state_init