mix_rhog – SIESTA
mix_rhog Subroutine
94 statements
Source File
public subroutine mix_rhog(iscf)
Uses
siesta_options
precision
fdf
m_diis
! maybe if (g2(j) <= certain cutoff) then
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iscf
Calls
Called by
Contents
Source Code
mix_rhog
Source Code
  subroutine mix_rhog(iscf)
    use siesta_options, only: wmix
    use precision,      only: dp
    use fdf,            only: fdf_get
    use m_diis,         only: diis
    integer, intent(in) :: iscf
    integer  :: j, i
    real(dp) :: alpha
    real(dp), allocatable :: coeff(:)
    logical  :: mix_first_iter
    if (using_diis_for_rhog) then
       ! Do not use the first diff in the cycle for DIIS
       if (iscf>1) call add_rhog_in_and_diff_to_stack()
       !call print_type(rhog_stack)
       if (n_items(rhog_stack) > 1) then
          allocate(coeff(n_items(rhog_stack)))
          ! Get the DIIS coefficients
          call diis(rhog_stack,scalar_product,coeff)
          ! This will replace the small-G set coefficients
          ! by the DIIS-optimal ones
          call get_optimal_rhog_in()
          deallocate(coeff)
       endif
    endif
    ! Do Kerker mixing on the whole fourier series
    ! Check whether we want to mix in the first step
    mix_first_iter = fdf_get("SCF.MixCharge.SCF1",.false.)
    if ((iscf == 1) .and. (.not. mix_first_iter)) then
       ! Do not mix. Take the output density
       rhog_in(:,:,:) = rhog(:,:,:)
    else
       do j = 1, size(rhog_in,dim=2)
          !!! maybe           if (g2(j) <= certain cutoff) then
          if (.true.) then
             alpha = wmix * g2(j) / (g2(j) + q0sq)
             if (alpha == 0) alpha = wmix  ! for G=0
             rhog_in(:,j,:) = alpha * rhog(:,j,:) +  &
                  (1.0_dp - alpha) * rhog_in(:,j,:)
          else
             rhog_in(:,j,:) = rhog(:,j,:)
          endif
       enddo
    endif
  CONTAINS
    subroutine add_rhog_in_and_diff_to_stack()
    ! Store rho_in(G) and rho_diff(G) as single vectors
    ! in a circular stack of the appropriate size
    type(dData1D)      :: vin, vdiff
    type(Pair_dData1D) :: pair
    integer :: ip, i, j, ispin
    character(len=20) :: msg
    ip = 0
    do ispin = 1, nspin
       do j = 1, size(rhog_in,dim=2)
          if (g2mask(j)) then   ! if this G is treated within DIIS
             do i = 1, 2
                ip = ip + 1
                rg_in(ip) = rhog_in(i,j,ispin)
                rg_diff(ip) = rhog(i,j,ispin) - rg_in(ip)
             enddo
          endif
       enddo
    enddo
    write(msg,"(a,i3)") "scf step: ",iscf
    call newdData1D(vin,rg_in,name="(rhog_in -- " // trim(msg) //")")
    call newdData1D(vdiff,rg_diff,name="(rhog_diff -- " // trim(msg) //")")
    call new(pair,vin,vdiff,"(pair in-diff -- " // trim(msg) //")")
    call push(rhog_stack,pair)    ! Store in stack
    call delete(vin)
    call delete(vdiff)
    call delete(pair)
  end subroutine add_rhog_in_and_diff_to_stack
  subroutine get_optimal_rhog_in()
    ! Synthesize the DIIS-optimal rho_in(G) and rho_out(G)
    ! from the DIIS coefficients.
    real(dp), dimension(:), pointer :: vin, vdiff
    type(Pair_dData1D), pointer     :: pairp
    type(dData1D),  pointer         :: vp
    integer :: ip, i, j, ispin, k
    ! zero-out the components treated with DIIS
    do ispin = 1, nspin
       do j = 1, size(rhog_in,dim=2)
          if (g2mask(j)) then
             rhog_in(:,j,ispin) = 0.0_dp
             rhog(:,j,ispin)    = 0.0_dp
          endif
       enddo
    enddo
    do k = 1, n_items(rhog_stack)
       pairp => get_pointer(rhog_stack,k)
       call firstp(pairp,vp)
       vin => val(vp)
       call secondp(pairp,vp)
       vdiff => val(vp)
       ip = 0
       do ispin = 1, nspin
          do j = 1, size(rhog_in,dim=2)
             if (g2mask(j)) then
                do i = 1, 2
                   ip = ip + 1
                   rhog_in(i,j,ispin) = rhog_in(i,j,ispin) + &
                                               coeff(k)* vin(ip)
                   rhog(i,j,ispin)  =   rhog(i,j,ispin) +    &
                                             coeff(k)* (vdiff(ip) + vin(ip))
                enddo
             endif
          enddo
       enddo
    enddo
  end subroutine get_optimal_rhog_in
  end subroutine mix_rhog
Call graph
mix_rhog calls n_items, diis, fdf_get
siesta_forces calls mix_rhog