mixers_history_init – SIESTA
mixers_history_init Subroutine
45 statements
Source File
public subroutine mixers_history_init(mixers)
Initialize all history for the mixers
Routine for clearing all history and setting up the arrays so that they may be used subsequently.
@param[inout] mixers the mixers to be initialized
Arguments
Type Intent Optional Attributes Name
type(tMixer), intent(inout), target :: mixers(:)
Calls
Called by
Source Code
mixers_history_init
Source Code
  subroutine mixers_history_init( mixers )
    type(tMixer), intent(inout), target :: mixers(:)
    type(tMixer), pointer :: m
    integer :: im, is, ns
    logical :: is_GR
    do im = 1 , size(mixers)
       m => mixers(im)
       if ( debug_mix .and. current_itt(m) >= 1 ) then
          write(*,'(a,a)') trim(debug_msg), &
               ' resetting history of all mixers'
          exit
       end if
    end do
    ! Clean up all arrays and reference counted
    ! objects
    do im = 1 , size(mixers)
       m => mixers(im)
       ! reset history track
       m%start_itt = 0
       m%cur_itt = 0
       ! do not try and de-allocate something not
       ! allocated
       if ( allocated(m%stack) ) then
          ns = size(m%stack)
          do is = 1 , ns
             call delete(m%stack(is))
          end do
          ! clean-up
          deallocate(m%stack)
       end if
       ! Re-populate
       select case ( m%m )
       case ( MIX_LINEAR )
          ! do nothing
       case ( MIX_PULAY )
          is_GR = (m%v == 1) .or. (m%v == 3)
          if ( .not. is_GR ) then
             allocate(m%stack(3))
          else
             allocate(m%stack(2))
          end if
          ! These arrays contains these informations
          !   s1 = m%stack(1)
          !   s2 = m%stack(2)
          !   s3 = m%stack(3)
          ! Here <> is input function, x[in], and
          ! <>' is the corresponding output, x[out].
          ! First iteration:
          !   s1 = { 1' - 1 }
          !   s3 = { 1' }
          ! Second iteration
          !   s2 = { 2' - 2 - (1' - 1) }
          !   s1 = { 2 - 1 , 2' - 2 }
          !   s3 = { 2' }
          ! Third iteration
          !   s2 = { 2' - 2 - (1' - 1) , 3' - 3 - (2' - 2) }
          !   s1 = { 2 - 1 , 3 - 2, 3' - 3 }
          !   s3 = { 3' }
          ! and so on
          ! allocate x[i+1] - x[i]
          call new(m%stack(1), m%n_hist)
          ! allocate F[i+1] - F[i]
          call new(m%stack(2), m%n_hist-1)
          if ( .not. is_GR ) then
             call new(m%stack(3), 1)
          end if
       case ( MIX_BROYDEN )
          ! Same as original Pulay
          allocate(m%stack(3))
          call new(m%stack(1), m%n_hist)
          call new(m%stack(2), m%n_hist-1)
          call new(m%stack(3), 1)
       end select
    end do
  end subroutine mixers_history_init
All Procedures
compute_dm current_itt getstackval inverse is_next mix_method mix_method_variant mixer_init mixers_history_init mixers_init mixers_print mixers_print_block mixers_reset mixers_scf_history_init mixers_scf_init mixers_scf_print mixers_scf_print_block mixers_scf_reset mixing mixing_1d mixing_2d mixing_calc_next mixing_coeff mixing_finalize mixing_init mixing_ncoeff mixing_scf_converged mixing_step norm push_diff push_F push_stack_data setup_H0 setup_hamiltonian siesta_analysis siesta_forces stack_check state_analysis state_init svd update_F
Call graph
mixers_history_init calls delete, current_itt, new
mixers_scf_init calls mixers_history_init, mixers_init
mixers_scf_history_init calls mixers_history_init
state_init calls mixers_history_init
mixers_init calls mixers_history_init
siesta_forces calls mixers_scf_history_init, state_init