mixers_scf_print – SIESTA
mixers_scf_print Subroutine
21 statements
Source File
public subroutine mixers_scf_print(nspin)
Uses
parallel
m_mixing
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nspin
Calls
Source Code
mixers_scf_print
Source Code
  subroutine mixers_scf_print( nspin )
    use parallel, only: IONode
    use m_mixing, only: mixers_print
    integer, intent(in) :: nspin
    ! Print mixing options
    call mixers_print( 'SCF' , scf_mixs )
    if ( IONode .and. nspin > 1 ) then
       select case ( mix_spin )
       case ( MIX_SPIN_ALL )
          write(*, '(a,t50,a)') 'mix.SCF: Spin-component mixing','all'
       case ( MIX_SPIN_SPINOR )
          write(*, '(a,t50,a)') 'mix.SCF: Spin-component mixing','spinor'
          if ( nspin <= 2 ) then
             call die("SCF.Mixer.Spin spinor option only valid for &
                  &non-collinear and spin-orbit calculations")
          end if
       case ( MIX_SPIN_SUM )
          write(*, '(a,t50,a)') 'mix.SCF: Spin-component mixing','sum'
       case ( MIX_SPIN_SUM_DIFF )
          write(*, '(a,t50,a)') 'mix.SCF: Spin-component mixing','sum and diff'
       end select
    end if
  end subroutine mixers_scf_print
All Procedures
compute_dm compute_max_diff compute_max_diff_1d compute_max_diff_2d current_itt getstackval inverse is_next mix_method mix_method_variant mixer_init mixers_history_init mixers_init mixers_print mixers_print_block mixers_reset mixers_scf_history_init mixers_scf_init mixers_scf_print mixers_scf_print_block mixers_scf_reset mixing mixing_1d mixing_2d mixing_calc_next mixing_coeff mixing_finalize mixing_init mixing_ncoeff mixing_scf_converged mixing_step norm push_diff push_F push_stack_data setup_H0 setup_hamiltonian siesta_analysis siesta_forces stack_check state_analysis state_init svd update_F
Call graph
mixers_scf_print calls die, mixers_print
mixers_print calls die