mixers_init – SIESTA
mixers_init Subroutine
156 statements
Source File
public subroutine mixers_init(prefix, mixers, Comm)
Uses
parallel
fdf
Initialize a set of mixers by reading in fdf information. @param[in] prefix the fdf-label prefixes @param[pointer] mixers the mixers that are to be initialized @param[in] Comm @opt optional MPI-communicator
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: prefix
type(tMixer), pointer :: mixers(:)
integer, intent(in), optional :: Comm
Calls
Called by
Source Code
mixers_init
Source Code
  subroutine mixers_init( prefix, mixers, Comm )
    use parallel, only: IONode, Node
    use fdf
    ! FDF-prefix for searching keywords
    character(len=*), intent(in) :: prefix
    ! The array of mixers (has to be nullified upon entry)
    type(tMixer), pointer :: mixers(:)
    integer, intent(in), optional :: Comm
    ! Block constructs
    type(block_fdf) :: bfdf
    type(parsed_line), pointer :: pline
    ! number of history steps saved
    integer :: n_hist, n_restart, n_save
    real(dp) :: w
    integer :: nm, im, im2
    character(len=10) :: lp
    character(len=70) :: method, variant
    ! Default mixing options...
    if ( fdf_get('Mixer.Debug',.false.) ) then
       debug_mix = IONode
       debug_msg = 'mix:'
    end if
    if ( fdf_get('Mixer.Debug.MPI',.false.) ) then
       debug_mix = .true.
       write(debug_msg,'(a,i0,a)') 'mix (',Node,'):'
    end if
    lp = trim(prefix)//'.Mixer'
    ! ensure nullification
    call mixers_reset(mixers)
    ! Return immediately if the user hasn't defined
    ! an fdf-block for the mixing options...
    if ( .not. fdf_block(trim(lp)//'s', bfdf) ) return
    ! update mixing weight and kick mixing weight
    w      = fdf_get(trim(lp)//'.Weight',0.1_dp)
    ! Get history length
    n_hist = fdf_get(trim(lp)//'.History',6)
    ! Restart after this number of iterations
    n_restart = fdf_get(trim(lp)//'.Restart',0)
    n_save    = fdf_get(trim(lp)//'.Restart.Save',1)
    ! negative savings are not allowed
    n_save = max(0, n_save)
    ! Read in the options regarding the mixing options
    nm = 0
    do while ( fdf_bline(bfdf,pline) )
       if ( fdf_bnnames(pline) == 0 ) cycle
       nm = nm + 1
    end do
    if ( nm == 0 ) then
       call die('mixing: No mixing schemes selected. &
            &Please at least add one mixer.')
    end if
    ! Allocate all denoted mixers...
    allocate(mixers(nm))
    mixers(:)%w = w
    mixers(:)%n_hist = n_hist
    mixers(:)%restart = n_restart
    mixers(:)%restart_save = n_save
    ! Rewind to grab names.
    call fdf_brewind(bfdf)
    nm = 0
    do while ( fdf_bline(bfdf,pline) )
       if ( fdf_bnnames(pline) == 0 ) cycle
       nm = nm + 1
       mixers(nm)%name = fdf_bnames(pline,1)
    end do
    ! Now read all mixers for this segment and their options
    do im = 1 , nm
       call read_block( mixers(im) )
    end do
    ! Create history stack and associate correct
    ! stack pointers
    call mixers_history_init(mixers)
#ifdef MPI
    if ( present(Comm) ) then
       mixers(:)%Comm = Comm
    else
       mixers(:)%Comm = MPI_Comm_World
    end if
#endif
  contains
    subroutine read_block( m )
      type(tMixer), intent(inout), target :: m
      character(len=64) :: opt
      ! create block string
      opt = trim(lp)//'.'//trim(m%name)
      if ( .not. fdf_block(opt,bfdf) ) then
         call die('Block: '//trim(opt)//' does not exist!')
      end if
      ! Default to the pulay method...
      ! This enables NOT writing this in the block
      method = 'pulay'
      variant = ' '
      ! read method
      do while ( fdf_bline(bfdf,pline) )
         if ( fdf_bnnames(pline) == 0 ) cycle
         opt = fdf_bnames(pline,1)
         if ( leqi(opt,'method') ) then
            method = fdf_bnames(pline,2)
         else if ( leqi(opt,'variant') ) then
            variant = fdf_bnames(pline,2)
         end if
      end do
      ! Retrieve the method and the variant
      m%m = mix_method(method)
      m%v = mix_method_variant(m%m, variant)
      ! Define separate defaults which are
      ! not part of the default input options
      select case ( m%m )
      case ( MIX_LINEAR )
         m%n_hist = 0
      end select
      call fdf_brewind(bfdf)
      ! read options
      do while ( fdf_bline(bfdf,pline) )
         if ( fdf_bnnames(pline) == 0 ) cycle
         opt = fdf_bnames(pline,1)
         if ( leqi(opt,'iterations') &
              .or. leqi(opt,'itt') ) then
            m%n_itt = fdf_bintegers(pline,1)
         else if ( leqi(opt,'history') ) then
            m%n_hist = fdf_bintegers(pline,1)
         else if ( leqi(opt,'weight') .or. leqi(opt, 'w') ) then
            m%w = fdf_breals(pline,1)
         else if ( leqi(opt,'restart') ) then
            m%restart = fdf_bintegers(pline,1)
         else if ( leqi(opt,'restart.save') ) then
            m%restart_save = fdf_bintegers(pline,1)
            m%restart_save = max(0,m%restart_save)
         end if
      end do
      ! Initialize the mixer by setting the correct
      ! standard options and allocate space in the mixers...
      call mixer_init( m )
      ! Read the options for this mixer
      call fdf_brewind(bfdf)
      ! read options
      do while ( fdf_bline(bfdf,pline) )
         if ( fdf_bnnames(pline) == 0 ) cycle
         opt = fdf_bnames(pline,1)
         if ( leqi(opt,'next') ) then
            nullify(m%next)
            opt = fdf_bnames(pline,2)
            do im2 = 1 , nm
               if ( leqi(opt,mixers(im2)%name) ) then
                  m%next => mixers(im2)
                  exit
               end if
            end do
            if ( .not. associated(m%next) ) then
               call die('mixing: Could not find next mixer. &
                    &Ensure all mixers exist and their names.')
            end if
            if ( associated(m%next, target=m) ) then
               call die('mixing: Next *must* not be it-self. &
                    &Please change accordingly.')
            end if
         else if ( leqi(opt,'next.conv') ) then
            nullify(m%next_conv)
            opt = fdf_bnames(pline,2)
            do im2 = 1 , nm
               if ( leqi(opt,mixers(im2)%name) ) then
                  m%next_conv => mixers(im2)
                  exit
               end if
            end do
            if ( .not. associated(m%next_conv) ) then
               call die('mixing: Could not find next convergence mixer. &
                    &Ensure all mixers exist and their names.')
            end if
            if ( associated(m%next_conv,target=m) ) then
               call die('mixing: next.conv *must* not be it-self. &
                    &Please change accordingly.')
            end if
         end if
      end do
      ! Ensure that if a next have not been specified
      ! it will continue indefinitely.
      if ( .not. associated(m%next) ) then
         m%n_itt = 0
      end if
      ! Read the options for this mixer
      call fdf_brewind(bfdf)
      ! read options
      do while ( fdf_bline(bfdf,pline) )
         ! skip lines without associated content
         if ( fdf_bnnames(pline) == 0 ) cycle
         opt = fdf_bnames(pline,1)
         ! Do options so that a pulay option may refer to
         ! the actual names of the constants
         if ( m%m == MIX_PULAY ) then
            ! The linear mixing weight
            if ( leqi(opt,'weight.linear') &
                 .or. leqi(opt,'w.linear') ) then
               m%rv(1) = fdf_breals(pline,1)
            else if ( leqi(opt,'svd.cond') ) then
               ! This is only applicable to the Pulay
               ! mixing scheme...
               m%rv(I_SVD_COND) = fdf_bvalues(pline,1)
            end if
         end if
         ! Generic options for all advanced methods...
         if ( leqi(opt,'next.p') ) then
            ! Only allow stepping to the next when
            ! having a next associated
            if ( associated(m%next) ) then
               m%rv(I_P_NEXT) = fdf_bvalues(pline,1)
            end if
         else if ( leqi(opt,'restart.p') ) then
            m%rv(I_P_RESTART) = fdf_bvalues(pline,1)
         end if
      end do
    end subroutine read_block
  end subroutine mixers_init
All Procedures
current_itt getstackval inverse is_next mix_method mix_method_variant mixer_init mixers_history_init mixers_init mixers_print mixers_print_block mixers_reset mixers_scf_history_init mixers_scf_init mixers_scf_print mixers_scf_print_block mixers_scf_reset mixing mixing_1d mixing_2d mixing_calc_next mixing_coeff mixing_finalize mixing_init mixing_ncoeff mixing_scf_converged mixing_step norm push_diff push_F push_stack_data setup_H0 siesta_analysis siesta_forces stack_check state_analysis state_init svd update_F
Call graph
mixers_init calls fdf_bline, fdf_brewind, fdf_block, fdf_bnnames, fdf_get, mixers_reset, mixers_history_init, fdf_bnames, die
mixers_reset calls delete
mixers_history_init calls current_itt, delete, new
mixers_scf_init calls mixers_init