mixers_reset – SIESTA
mixers_reset Subroutine
26 statements
Source File
public subroutine mixers_reset(mixers)
Reset the mixers, i.e. clean everything
Also deallocates (and nullifies) the input array!
@param[inout] mixers array of mixers to be cleaned
Arguments
Type Intent Optional Attributes Name
type(tMixer), pointer :: mixers(:)
Calls
Called by
Contents
Source Code
mixers_reset
Source Code
  subroutine mixers_reset( mixers )
    type(tMixer), pointer :: mixers(:)
    type(tMixer), pointer :: m
    integer :: im, is, ns
    if ( .not. associated(mixers) ) return
    do im = 1 , size(mixers)
       m => mixers(im)
       if ( allocated(m%stack) ) then
          ns = size(m%stack)
          do is = 1 , ns
             call delete(m%stack(is))
          end do
          deallocate(m%stack)
       end if
       if ( associated(m%rv) ) then
          deallocate(m%rv)
          nullify(m%rv)
       end if
       if ( associated(m%iv) ) then
          deallocate(m%iv)
          nullify(m%iv)
       end if
    end do
    deallocate(mixers)
    nullify(mixers)
  end subroutine mixers_reset
Call graph
mixers_reset calls delete
mixers_scf_reset calls mixers_reset
mixers_init calls mixers_reset
mixers_scf_init calls mixers_reset, mixers_init