mixers_scf_history_init – SIESTA
mixers_scf_history_init Subroutine
5 statements
Source File
public subroutine mixers_scf_history_init()
Uses
m_mixing
Arguments
None
Calls
Called by
Contents
Source Code
mixers_scf_history_init
Source Code
  subroutine mixers_scf_history_init( )
    use m_mixing, only: mixers_history_init
    call mixers_history_init( scf_mixs )
    scf_mix => scf_mixs(1)
  end subroutine mixers_scf_history_init
Call graph
mixers_scf_history_init calls mixers_history_init
mixers_history_init calls current_itt, new, delete
siesta_forces calls mixers_scf_history_init