mixing_1d – SIESTA
mixing_1d Subroutine
20 statements
Source File
private subroutine mixing_1d(mix, n, xin, F, xnext, nsub)
Arguments
Type Intent Optional Attributes Name
type(tMixer), pointer :: mix
integer, intent(in) :: n
real(kind=dp), intent(in) :: xin(n)
real(kind=dp), intent(in) :: F(n)
real(kind=dp), intent(inout) :: xnext(n)
integer, intent(in), optional :: nsub
Calls
Called by
Source Code
mixing_1d
Source Code
  subroutine mixing_1d( mix, n, xin, F, xnext, nsub)
    ! The current mixing method
    type(tMixer), pointer :: mix
    ! The current step in the SCF and size of arrays
    integer, intent(in) :: n
    ! x1 == Input function,
    ! F1 == Residual from x1
    real(dp), intent(in) :: xin(n), F(n)
    ! x2 == Next input function
    real(dp), intent(inout) :: xnext(n)
    ! Number of elements used for calculating the mixing
    ! coefficients
    integer, intent(in), optional :: nsub
    ! Coefficients
    integer :: ncoeff
    real(dp), allocatable :: coeff(:)
    call mixing_init( mix, n, xin, F )
    ncoeff = mixing_ncoeff( mix )
    allocate(coeff(ncoeff))
    ! Calculate coefficients
    if ( present(nsub) ) then
       call mixing_coeff( mix, nsub, xin, F, coeff)
    else
       call mixing_coeff( mix, n, xin, F, coeff)
    end if
    ! Calculate the following output
    call mixing_calc_next( mix, n, xin, F, xnext, coeff)
    ! Coefficients are not needed anymore...
    deallocate(coeff)
    ! Finalize the mixer
    call mixing_finalize( mix, n, xin, F, xnext)
  end subroutine mixing_1d
All Procedures
compute_dm compute_max_diff compute_max_diff_1d compute_max_diff_2d current_itt getstackval inverse is_next mix_method mix_method_variant mixer_init mixers_history_init mixers_init mixers_print mixers_print_block mixers_reset mixers_scf_history_init mixers_scf_init mixers_scf_print mixers_scf_print_block mixers_scf_reset mixing mixing_1d mixing_2d mixing_calc_next mixing_coeff mixing_finalize mixing_init mixing_ncoeff mixing_scf_converged mixing_step norm push_diff push_F push_stack_data setup_H0 setup_hamiltonian siesta_analysis siesta_forces stack_check state_analysis state_init svd update_F
Call graph
mixing_1d calls mixing_coeff, mixing_finalize, mixing_init, mixing_calc_next, mixing_ncoeff
mixing_coeff calls mixing_ncoeff
mixing_finalize calls n_items, current_itt, mixing_step, reset
mixing_init calls norm, current_itt
mixing_ncoeff calls n_items
mixing_step calls n_items, reset, get_pointer, push
mixing calls mixing_1d