mixing_step – SIESTA
mixing_step Subroutine
58 statements
Source File
private subroutine mixing_step(mix)
Uses
parallel
Arguments
Type Intent Optional Attributes Name
type(tMixer), pointer :: mix
Calls
Called by
Source Code
mixing_step
Source Code
  subroutine mixing_step( mix )
    use parallel, only: IONode
    type(tMixer), pointer :: mix
    type(tMixer), pointer :: next => null()
    type(dData1D), pointer :: d1D
    integer :: i, is, n, init_itt
    logical :: reset_stack, copy_stack
    ! First try and
    next => mix%next
    if ( associated(next) ) then
       ! Whether or not the two methods are allowed
       ! to share history
       copy_stack = mix%m == next%m
       select case ( mix%m )
       case ( MIX_PULAY , MIX_BROYDEN )
          select case ( next%m )
          case ( MIX_PULAY , MIX_BROYDEN )
             copy_stack = .true.
          end select
       end select
       copy_stack = copy_stack .and. allocated(mix%stack)
       ! If the two methods are similar
       if ( copy_stack ) then
          ! They are similar, copy over the history stack
          do is = 1 , size(mix%stack)
             ! Get maximum size of the current stack,
             n = n_items(mix%stack(is))
             ! Note that this will automatically take care of
             ! wrap-arounds and delete the unneccesry elements
             do i = 1 , n
                d1D => get_pointer(mix%stack(is),i)
                call push(next%stack(is),d1D)
             end do
             ! nullify
             nullify(d1D)
          end do
       end if
    end if
    reset_stack = .true.
    if ( associated(next) ) then
       if ( associated(next%next, mix) .and. &
            next%n_itt > 0 ) then
          ! if this is a circular mixing routine
          ! we should not reset the history...
          reset_stack = .false.
       end if
    end if
    if ( reset_stack ) then
       select case ( mix%m )
       case ( MIX_PULAY , MIX_BROYDEN )
          n = size(mix%stack)
          do is = 1 , n
             call reset(mix%stack(is))
          end do
       end select
    end if
    if ( associated(next) ) then
       init_itt = 0
       ! Set-up the next mixer
       select case ( next%m )
       case ( MIX_PULAY , MIX_BROYDEN )
          init_itt = n_items(next%stack(1))
       end select
       next%start_itt = init_itt
       next%cur_itt = init_itt
       if ( IONode ) then
          write(*,'(3a)') trim(debug_msg),' switching mixer --> ', &
               trim(next%name)
       end if
       mix => mix%next
    end if
  end subroutine mixing_step
All Procedures
compute_dm compute_max_diff compute_max_diff_1d compute_max_diff_2d current_itt getstackval inverse is_next mix_method mix_method_variant mixer_init mixers_history_init mixers_init mixers_print mixers_print_block mixers_reset mixers_scf_history_init mixers_scf_init mixers_scf_print mixers_scf_print_block mixers_scf_reset mixing mixing_1d mixing_2d mixing_calc_next mixing_coeff mixing_finalize mixing_init mixing_ncoeff mixing_scf_converged mixing_step norm push_diff push_F push_stack_data setup_H0 setup_hamiltonian siesta_analysis siesta_forces stack_check state_analysis state_init svd update_F
Call graph
mixing_step calls n_items, reset, get_pointer, push
mixing_finalize calls mixing_step
mixing_1d calls mixing_finalize
mixing calls mixing_1d