mixing_init – SIESTA
mixing_init Subroutine
170 statements
Source File
private subroutine mixing_init(mix, n, xin, F)
Initialize the mixing algorithm
@param[pointer] mix the mixing method @param[in] n size of the arrays to be used in the algorithm @param[in] xin array of the input variables @param[in] xout array of the output variables
Arguments
Type Intent Optional Attributes Name
type(tMixer), pointer :: mix
integer, intent(in) :: n
real(kind=dp), intent(in) :: xin(n)
real(kind=dp), intent(in) :: F(n)
Calls
Called by
Contents
Source Code
mixing_init
Source Code
  subroutine mixing_init( mix, n, xin, F)
    ! The current mixing method
    type(tMixer), pointer :: mix
    integer, intent(in) :: n
    ! In/out of the function
    real(dp), intent(in) :: xin(n), F(n)
    real(dp), pointer :: res(:), rres(:)
    integer :: i, ns
    real(dp) :: dnorm, dtmp
    logical :: p_next, p_restart
    ! Initialize action for mixer
    mix%action = ACTION_MIX
    ! Step iterator (so first mixing has cur_itt == 1)
    mix%cur_itt = mix%cur_itt + 1
    ! If we are going to skip to next, we signal it
    ! before entering
    if ( mix%n_itt > 0 .and. &
         mix%n_itt <= current_itt(mix) ) then
       mix%action = IOR(mix%action, ACTION_NEXT)
    end if
    ! Check whether the residual norm is below a certain
    ! criteria
    p_next = mix%rv(I_P_NEXT) > 0._dp
    p_restart = mix%rv(I_P_RESTART) > 0._dp
    ! Check whether a parameter next/restart is required
    if ( p_restart .or. p_next ) then
       ! Calculate norm: ||f_k||
       dnorm = norm(n, F, F)
#ifdef MPI
       dtmp = dnorm
       call MPI_AllReduce(dtmp,dnorm,1, &
            MPI_double_precision, MPI_Sum, &
            mix%Comm, i)
#endif
       ! Calculate the relative difference
       dtmp = abs(dnorm / mix%rv(I_PREVIOUS_RES) - 1._dp)
       ! We first check for next, that has precedence
       if ( p_next ) then
          if ( dtmp < mix%rv(I_P_NEXT) ) then
             ! Signal stepping mixer
             mix%action = IOR(mix%action, ACTION_NEXT)
          end if
          if ( debug_mix .and. current_itt(mix) > 1 ) &
               write(*,'(a,2(a,e8.3))') trim(debug_msg), &
               ' | ||f_k|| - ||f_k-1|| |/||f_k-1|| < np  :  ', &
               dtmp, ' < ', mix%rv(I_P_NEXT)
       end if
       if ( p_restart ) then
          if ( dtmp < mix%rv(I_P_RESTART) ) then
             ! Signal restart
             mix%action = IOR(mix%action, ACTION_RESTART)
          end if
          if ( debug_mix .and. current_itt(mix) > 1 ) &
               write(*,'(a,2(a,e8.3))') trim(debug_msg), &
               ' | ||f_k|| - ||f_k-1|| |/||f_k-1|| < rp  :  ', &
               dtmp, ' < ', mix%rv(I_P_RESTART)
       end if
       ! Store the new residual norm
       mix%rv(I_PREVIOUS_RES) = dnorm
    end if
    ! Push information to the stack
    select case ( mix%m )
    case ( MIX_LINEAR )
       if ( debug_mix ) &
            write(*,'(2a)') trim(debug_msg),' linear'
       call init_linear()
    case ( MIX_PULAY )
       if ( debug_mix ) then
          select case ( mix%v )
          case ( 0 )
            write(*,'(2a)') trim(debug_msg),' Pulay'
          case ( 1 )
            write(*,'(2a)') trim(debug_msg),' Pulay, GR'
          case ( 2 )
            write(*,'(2a)') trim(debug_msg),' Pulay-SVD'
          case ( 3 )
            write(*,'(2a)') trim(debug_msg),' Pulay-SVD, GR'
          end select
       end if
       call init_pulay()
    case ( MIX_BROYDEN )
      if ( debug_mix ) &
           write(*,'(2a)') trim(debug_msg),' Broyden'
       call init_broyden()
    end select
  contains
    subroutine init_linear()
      ! information for this depends on the
      ! following method
      call fake_history_from_linear(mix%next)
      call fake_history_from_linear(mix%next_conv)
    end subroutine init_linear
    subroutine init_pulay()
      logical :: GR_linear
      select case ( mix%v )
      case ( 0 , 2 ) ! Stable Pulay
         ! Add the residual to the stack
         call push_F(mix%stack(1), n, F)
         ns = n_items(mix%stack(1))
         ! Add the residuals of the residuals if applicable
         if ( ns > 1 ) then
            ! Create F[i+1] - F[i]
            call push_diff(mix%stack(2), mix%stack(1))
            ! Update the residual to reflect the input residual
            res => getstackval(mix, 1, ns-1)
            rres => getstackval(mix, 3)
!$OMP parallel do default(shared), private(i)
            do i = 1 , n
               res(i) = res(i) - rres(i) + xin(i)
            end do
!$OMP end parallel do
         end if
      case ( 1 , 3 )
         ! Whether this is the linear cycle...
         GR_linear = mod(current_itt(mix), 2) == 1
         ! Add the residual to the stack
         call push_F(mix%stack(1), n, F, mix%rv(1))
         ns = n_items(mix%stack(1))
         if ( GR_linear .and. current_itt(mix) > 1 .and. &
              ns > 1 ) then
            res => getstackval(mix, 1)
            rres => getstackval(mix, 2)
!$OMP parallel do default(shared), private(i)
            do i = 1 , n
               rres(i) = rres(i) + res(i)
            end do
!$OMP end parallel do
         else if ( ns > 1 .and. .not. GR_linear ) then
            ! now we can calculate RRes[i]
            call push_diff(mix%stack(2),mix%stack(1))
         end if
      end select
    end subroutine init_pulay
    subroutine init_broyden()
      ! Add the residual to the stack
      call push_F(mix%stack(1), n, F)
      ns = n_items(mix%stack(1))
      ! Add the residuals of the residuals if applicable
      if ( ns > 1 ) then
         ! Create F[i+1] - F[i]
         call push_diff(mix%stack(2), mix%stack(1))
         ! Update the residual to reflect the input residual
         res => getstackval(mix, 1, ns-1)
         rres => getstackval(mix, 3)
!$OMP parallel do default(shared), private(i)
         do i = 1 , n
            res(i) = res(i) - rres(i) + xin(i)
         end do
!$OMP end parallel do
      else
         ! Store F[x_in] (used to create the input residual)
         call push_stack_data(mix%stack(3), n)
         res => getstackval(mix, 3)
!$OMP parallel do default(shared), private(i)
         do i = 1 , n
            res(i) = xin(i) + F(i)
         end do
!$OMP end parallel do
      end if
    end subroutine init_broyden
    subroutine fake_history_from_linear(next)
      type(tMixer), pointer :: next
      real(dp), pointer :: t1(:), t2(:)
      integer :: ns, nh, i, nhl
      if ( .not. associated(next) ) return
      ! Reduce to # history of linear
      nhl = mix%n_hist
      ! if the number of fake-history steps saved is
      ! zero we immediately return.
      ! Only if mix%n_hist > 0 will the below
      ! occur.
      if ( nhl == 0 ) return
      ! Check for the type of following method
      select case ( next%m )
      case ( MIX_PULAY )
         ! Here it depends on the variant
         select case ( next%v )
         case ( 0 , 2 ) ! stable pulay mixing
            ! Add the residual to the stack
            call push_F(next%stack(1), n, F)
            ns = n_items(next%stack(1))
            ! Add the residuals of the residuals if applicable
            if ( ns > 1 ) then
               ! Create F[i+1] - F[i]
               call push_diff(next%stack(2), next%stack(1))
               ! Update the residual to reflect the input residual
               t1 => getstackval(next, 1, ns-1)
               t2 => getstackval(next, 3)
!$OMP parallel do default(shared), private(i)
               do i = 1 , n
                  t1(i) = t1(i) - t2(i) + xin(i)
                  t2(i) = xin(i) + F(i)
               end do
!$OMP end parallel do
            else
               call push_stack_data(next%stack(3), n)
               t1 => getstackval(next, 3)
!$OMP parallel do default(shared), private(i)
               do i = 1 , n
                  t1(i) = xin(i) + F(i)
               end do
!$OMP end parallel do
            end if
            ! Clean up the data...
            if ( ns >= nhl ) then
               call reset(next%stack(1), 1)
               call reset(next%stack(2), 1)
               ns = ns - 1
            end if
            nh = max_size(next%stack(1))
            if ( debug_mix ) &
                 write(*,'(a,2(a,i0))') trim(debug_msg), &
                 ' next%n_hist = ', ns, ' / ', nh
         end select
      case ( MIX_BROYDEN )
         ! Add the residual to the stack
         call push_F(next%stack(1), n, F)
         ns = n_items(next%stack(1))
         ! Add the residuals of the residuals if applicable
         if ( ns >= 2 ) then
            ! Create F[i+1] - F[i]
            call push_diff(next%stack(2), next%stack(1))
            ! Update the residual to reflect the input residual
            t1 => getstackval(next, 1, ns-1)
            t2 => getstackval(next, 3)
!$OMP parallel do default(shared), private(i)
            do i = 1 , n
               t1(i) = t1(i) - t2(i) + xin(i)
               t2(i) = xin(i) + F(i)
            end do
!$OMP end parallel do
         else
            call push_stack_data(next%stack(3), n)
            t1 => getstackval(next, 3)
!$OMP parallel do default(shared), private(i)
            do i = 1 , n
               t1(i) = xin(i) + F(i)
            end do
!$OMP end parallel do
         end if
         ! Clean up the data...
         if ( ns >= nhl ) then
            call reset(next%stack(1), 1)
            call reset(next%stack(2), 1)
            ns = ns - 1
         end if
         nh = max_size(next%stack(1))
         if ( debug_mix ) &
              write(*,'(a,2(a,i0))') trim(debug_msg), &
              ' next%n_hist = ', ns, ' / ', nh
      end select
    end subroutine fake_history_from_linear
  end subroutine mixing_init
Call graph
mixing_init calls current_itt, norm
mixing_1d calls mixing_init
mixing calls mixing_1d