mixing_finalize – SIESTA
mixing_finalize Subroutine
105 statements
Source File
private subroutine mixing_finalize(mix, n, xin, F, xnext)
Uses
parallel
Finalize the mixing algorithm
@param[inout] mix mixer to be finalized @param[in] n size of the input arrays @param[in] xin the input for this iteration @param[in] F the residual for this iteration @param[in] xnext the optimized input for the next iteration
Arguments
Type Intent Optional Attributes Name
type(tMixer), pointer :: mix
integer, intent(in) :: n
real(kind=dp), intent(in) :: xin(n)
real(kind=dp), intent(in) :: F(n)
real(kind=dp), intent(in) :: xnext(n)
Calls
Called by
Source Code
mixing_finalize
Source Code
  subroutine mixing_finalize(mix, n, xin, F, xnext)
    use parallel, only: IONode
    type(tMixer), pointer :: mix
    integer, intent(in) :: n
    real(dp), intent(in) :: xin(n), F(n), xnext(n)
    integer :: rsave
    select case ( mix%m )
    case ( MIX_LINEAR )
       call fin_linear()
    case ( MIX_PULAY )
       call fin_pulay()
    case ( MIX_BROYDEN )
       call fin_broyden()
    end select
    ! Fix the action to finalize it..
    if ( mix%restart > 0 .and. &
         mod(current_itt(mix),mix%restart) == 0 ) then
       mix%action = IOR(mix%action, ACTION_RESTART)
    end if
    ! Check the actual finalization...
    ! First check whether we should restart history
    if ( IAND(mix%action, ACTION_RESTART) == ACTION_RESTART ) then
       ! The user has requested to restart the
       ! mixing scheme now
       rsave = mix%restart_save
       select case ( mix%m )
       case ( MIX_PULAY )
          if ( IONode ) then
             write(*,'(a)')'mix: Pulay -- resetting history'
          end if
          if ( rsave == 0 ) then
             call reset(mix%stack(1))
             call reset(mix%stack(2))
             call reset(mix%stack(3))
          else
             call reset(mix%stack(1),-rsave)
             call reset(mix%stack(2),-rsave+1)
          end if
       case ( MIX_BROYDEN )
          if ( IONode ) then
             write(*,'(a)')'mix: Broyden -- resetting history'
          end if
          if ( rsave == 0 ) then
             call reset(mix%stack(1))
             call reset(mix%stack(2))
             call reset(mix%stack(3))
          else
             call reset(mix%stack(1),-rsave)
             call reset(mix%stack(2),-rsave+1)
          end if
       end select
       if ( allocated(mix%stack) ) then
          if ( debug_mix ) &
               write(*,'(a,a,i0)') trim(debug_msg), &
               ' saved hist = ',n_items(mix%stack(1))
       end if
    end if
    ! check whether we should change the mixer
    if ( IAND(mix%action, ACTION_NEXT) == ACTION_NEXT ) then
       call mixing_step( mix )
    end if
  contains
    subroutine fin_linear()
      ! do nothing...
    end subroutine fin_linear
    subroutine fin_pulay()
      integer :: ns
      integer :: i
      logical :: GR_linear
      real(dp), pointer :: res(:), rres(:)
      ns = n_items(mix%stack(1))
      select case ( mix%v )
      case ( 0 , 2 ) ! stable Pulay
         if ( n_items(mix%stack(3)) == 0 ) then
            call push_stack_data(mix%stack(3), n)
         end if
         res => getstackval(mix, 3)
!$OMP parallel do default(shared), private(i)
         do i = 1 , n
            ! Input:
            !  res == x[i-1] + F[i-1]
            res(i) = xin(i) + F(i)
            ! Output:
            !  res == x[i] + F[i]
         end do
!$OMP end parallel do
      case ( 1 , 3 ) ! GR Pulay
         GR_linear = mod(current_itt(mix), 2) == 1
         if ( n_items(mix%stack(2)) > 0 .and. &
              .not. GR_linear ) then
            res => getstackval(mix, 1)
            rres => getstackval(mix, 2)
!$OMP parallel do default(shared), private(i)
            do i = 1 , n
               ! Input:
               !  rres == F[i] - F[i-1]
               rres(i) = rres(i) - res(i)
               ! Output:
               !  rres == - F[i-1]
            end do
!$OMP end parallel do
            call pop(mix%stack(1))
            ! Note that this is Res[i-1] = (F^i-1_out - F^i-1_in)
            res => getstackval(mix,1)
!$OMP parallel do default(shared), private(i)
            do i = 1 , n
               res(i) = res(i) - xin(i) + xnext(i)
            end do
!$OMP end parallel do
         end if
      end select
    end subroutine fin_pulay
    subroutine fin_broyden()
      integer :: ns, nh
      integer :: i
      real(dp), pointer :: res(:), rres(:)
      ns = current_itt(mix)
      nh = n_items(mix%stack(2))
      if ( ns >= 2 .and. n_items(mix%stack(3)) > 0 ) then
         ! Update the residual to reflect the input residual
         res => getstackval(mix, 3)
!$OMP parallel do default(shared), private(i)
         do i = 1 , n
            ! Input:
            !  res == x[i-1] + F[i-1]
            res(i) = xin(i) + F(i)
            ! Output:
            !  res == x[i] + F[i]
         end do
!$OMP end parallel do
      end if
      ! Update weights (if necessary)
      if ( nh > 1 ) then
         do i = 2 , nh
            mix%rv(i) = mix%rv(i+1)
         end do
      end if
    end subroutine fin_broyden
  end subroutine mixing_finalize
All Procedures
compute_dm compute_max_diff compute_max_diff_1d compute_max_diff_2d current_itt getstackval inverse is_next mix_method mix_method_variant mixer_init mixers_history_init mixers_init mixers_print mixers_print_block mixers_reset mixers_scf_history_init mixers_scf_init mixers_scf_print mixers_scf_print_block mixers_scf_reset mixing mixing_1d mixing_2d mixing_calc_next mixing_coeff mixing_finalize mixing_init mixing_ncoeff mixing_scf_converged mixing_step norm push_diff push_F push_stack_data setup_H0 setup_hamiltonian siesta_analysis siesta_forces stack_check state_analysis state_init svd update_F
Call graph
mixing_finalize calls current_itt, n_items, reset, mixing_step
mixing_step calls n_items, reset, get_pointer, push
mixing_1d calls mixing_finalize
mixing calls mixing_1d