mixing_coeff – SIESTA
mixing_coeff Subroutine
153 statements
Source File
private subroutine mixing_coeff(mix, n, xin, F, coeff)
Uses
parallel
Calculate the mixing coefficients for the current mixer
@param[in] mix the current mixer @param[in] n the number of elements used to calculate the coefficients @param[in] xin the input value @param[in] F xout - xin, (residual) @param[out] coeff the coefficients
Arguments
Type Intent Optional Attributes Name
type(tMixer), intent(inout) :: mix
integer, intent(in) :: n
real(kind=dp), intent(in) :: xin(n)
real(kind=dp), intent(in) :: F(n)
real(kind=dp), intent(out) :: coeff(:)
Calls
Called by
Contents
Source Code
mixing_coeff
Source Code
  subroutine mixing_coeff( mix, n, xin, F, coeff)
    use parallel, only: IONode
    type(tMixer), intent(inout) :: mix
    integer, intent(in) :: n
    real(dp), intent(in) :: xin(n), F(n)
    real(dp), intent(out) :: coeff(:)
    integer :: ncoeff
    ncoeff = size(coeff)
    if ( ncoeff < mixing_ncoeff(mix) ) then
       write(*,'(a)') 'mix: Error in calculating coefficients'
       ! Do not allow this...
       return
    end if
    select case ( mix%m )
    case ( MIX_LINEAR )
       call linear_coeff()
    case ( MIX_PULAY )
       call pulay_coeff()
    case ( MIX_BROYDEN )
       call broyden_coeff()
    end select
  contains
    subroutine linear_coeff()
      integer :: i
      do i = 1 , ncoeff
         coeff(i) = 0._dp
      end do
    end subroutine linear_coeff
    subroutine pulay_coeff()
      integer :: ns, nh, nmax
      integer :: i, j, info
      logical :: lreturn
      ! Calculation quantities
      real(dp) :: dnorm, G
      real(dp), pointer :: res(:), rres(:), rres1(:), rres2(:)
      real(dp), allocatable :: A(:,:), Ainv(:,:)
      ns = n_items(mix%stack(1))
      nmax = max_size(mix%stack(1))
      nh = n_items(mix%stack(2))
      lreturn = .false.
      ! Easy check for initial step...
      select case ( mix%v )
      case ( 0 , 2 ) ! Stable Pulay
         lreturn = ns == 1
      case ( 1 , 3 ) ! Guaranteed Pulay
         lreturn = mod(current_itt(mix), 2) == 1
      end select
      ! In case we return we are actually doing
      ! linear mixing
      if ( lreturn ) return
      ! Print out number of currently used history steps
      if ( debug_mix ) &
           write(*,'(a,2(a,i0))') trim(debug_msg), &
           ' n_hist = ',ns, ' / ',nmax
      ! Allocate arrays for calculating the
      ! coefficients
      allocate(A(nh,nh), Ainv(nh,nh))
      ! Calculate A_ij coefficients for inversion
      do i = 1 , nh
         ! Get RRes[i] array
         rres1 => getstackval(mix, 2, i)
         do j = 1 , i - 1
            ! Get RRes[j] array
            rres2 => getstackval(mix, 2, j)
            ! A(i,j) = A(j,i) = norm(RRes[i],RRes[j])
            A(i,j) = norm(n, rres1, rres2)
            A(j,i) = A(i,j)
         end do
         ! Diagonal
         A(i,i) = norm(n, rres1, rres1)
      end do
#ifdef MPI
      ! Global operations, but only for the non-extended entries
      call MPI_AllReduce(A(1,1),Ainv(1,1),nh*nh, &
           MPI_double_precision, MPI_Sum, &
           mix%Comm, i)
      ! copy over reduced arrays
      A = Ainv
#endif
      ! Get inverse of matrix
      select case ( mix%v )
      case ( 0 , 1 )
         call inverse(nh, A, Ainv, info)
         if ( info /= 0 ) then
            ! only inform if we should not use SVD per default
            if ( IONode ) &
                 write(*,'(2a)') trim(debug_msg), &
                 ' Pulay -- inversion failed, > SVD'
            ! We will first try the SVD routine
            call svd(nh, A, Ainv, mix%rv(I_SVD_COND), info)
         end if
      case ( 2 , 3 )
         ! We forcefully use the SVD routine
         call svd(nh, A, Ainv, mix%rv(I_SVD_COND), info)
      end select
      ! NOTE, although mix%stack(1) contains
      ! the x[i] - x[i-1], the tip of the stack
      ! contains F[i]!
      ! res == F[i]
      res => getstackval(mix, 1)
      ! Initialize the coefficients
      do i = 1 , nh
         coeff(i) = 0._dp
      end do
      if ( info == 0 ) then
         ! Calculate the coefficients on all processors
         do j = 1 , nh
            ! res  == F[i]
            ! rres == F[j+1] - F[j]
            rres => getstackval(mix, 2, j)
            dnorm = norm(n, rres, res)
            do i = 1 , nh
               coeff(i) = coeff(i) - Ainv(i,j) * dnorm
            end do
         end do
#ifdef MPI
         ! Reduce the coefficients
         call MPI_AllReduce(coeff(1),A(1,1),nh, &
              MPI_double_precision, MPI_Sum, &
              mix%Comm, i)
         do i = 1 , nh
            coeff(i) = A(i,1)
         end do
#endif
      else
         info = 0
         ! reset to linear mixing
         write(*,'(2a)') trim(debug_msg), &
              ' Pulay -- inversion failed, SVD failed, > linear'
      end if
      ! Clean up memory
      deallocate(A, Ainv)
    end subroutine pulay_coeff
    subroutine broyden_coeff()
      integer :: ns, nh, nmax
      integer :: i, j, k, info
      ! Calculation quantities
      real(dp) :: dnorm, dtmp
      real(dp), pointer :: w(:), res(:), rres(:), rres1(:), rres2(:)
      real(dp), allocatable :: c(:), A(:,:), Ainv(:,:)
      ns = n_items(mix%stack(1))
      nmax = max_size(mix%stack(1))
      nh = n_items(mix%stack(2))
      ! Easy check for initial step...
      if ( ns == 1 ) then
         ! reset
         coeff = 0._dp
         return
      end if
      ! Print out number of currently used history steps
      if ( debug_mix ) &
           write(*,'(a,2(a,i0))') trim(debug_msg), &
           ' n_hist = ',ns, ' / ',nmax
      ! This is the modified Broyden algorithm...
      ! Retrieve the previous weights
      w => mix%rv(2:1+nh)
      select case ( mix%v )
      case ( 2 ) ! Unity Broyden
         w(nh) = 1._dp
      case ( 1 ) ! RMS Broyden
         dnorm = norm(n, F, F)
#ifdef MPI
         call MPI_AllReduce(dnorm, dtmp, 1, &
              MPI_Double_Precision, MPI_Max, &
              mix%Comm, i)
         dnorm = dtmp
#endif
         w(:) = 1._dp / sqrt(dnorm)
         if ( debug_mix ) &
              write(*,'(2(a,e10.4))') &
              trim(debug_msg)//' weight = ',w(1), &
              ' , norm = ',dnorm
      case ( 0 ) ! Varying weight
         dnorm = 0._dp
!$OMP parallel do default(shared), private(i), &
!$OMP& reduction(max:dnorm)
         do i = 1 , n
            dnorm = max( dnorm, abs(F(i)) )
         end do
!$OMP end parallel do
#ifdef MPI
         call MPI_AllReduce(dnorm, dtmp, 1, &
              MPI_Double_Precision, MPI_Max, &
              mix%Comm, i)
         dnorm = dtmp
#endif
         ! Problay 0.2 should be changed to user-defined
         w(nh) = exp( 1._dp / (dnorm + 0.2_dp) )
         if ( debug_mix ) &
              write(*,'(2a,1000(tr1,e10.4))') &
              trim(debug_msg),' weights = ',w(1:nh)
      end select
      ! Allocate arrays used
      allocate(c(nh))
      allocate(A(nh,nh), Ainv(nh,nh))
      !  < RRes[i] | Res[n] >
      do i = 1 , nh
         rres => getstackval(mix, 2, i)
         c(i) = norm(n, rres, F)
      end do
#ifdef MPI
      call MPI_AllReduce(c(1), A(1,1), nh, &
           MPI_Double_Precision, MPI_Sum, &
           mix%Comm, i)
      do i = 1 , nh
         c(i) = A(i,1)
      end do
#endif
      ! Create A_ij coefficients for inversion
      do i = 1 , nh
         ! Get RRes[i] array
         rres1 => getstackval(mix, 2, i)
         do j = 1 , i -1
            ! Get RRes[j] array
            rres2 => getstackval(mix, 2, j)
            ! A(i,j) = A(j,i) = dot_product(RRes[i],RRes[j])
            A(i,j) = w(i) * w(j) * norm(n, rres1, rres2)
            A(j,i) = A(i,j)
         end do
         ! Do the diagonal term
         A(i,i) = w(i) * w(i) * norm(n, rres1, rres1)
      end do
#ifdef MPI
      call MPI_AllReduce(A(1,1),Ainv(1,1),nh*nh, &
           MPI_double_precision, MPI_Sum, &
           mix%Comm, i)
      A = Ainv
#endif
      ! Add the diagonal term
      ! This should also prevent it from being
      ! singular (unless mix%w == 0)
      do i = 1 , nh
         A(i,i) = mix%rv(1) ** 2 + A(i,i)
      end do
      ! Calculate the inverse
      call inverse(nh, A, Ainv, info)
      if ( info /= 0 ) then
         ! only inform if we should not use SVD per default
         if ( IONode ) &
              write(*,'(2a)') trim(debug_msg), &
              ' Broyden -- inversion failed, > SVD'
         ! We will first try the SVD routine
         call svd(nh, A, Ainv, mix%rv(I_SVD_COND), info)
      end if
      do i = 1 , nh
         coeff(i) = 0._dp
      end do
      if ( info == 0 ) then
         ! Calculate the coefficients...
         do i = 1 , nh
            do j = 1 , nh
               ! Ainv should be symmetric (A is)
               coeff(i) = coeff(i) + w(j) * c(j) * Ainv(j,i)
            end do
            ! Calculate correct weight...
            coeff(i) = - w(i) * coeff(i)
         end do
      else
         ! reset to linear mixing
         write(*,'(2a)') trim(debug_msg), &
              ' Broyden -- inversion failed, SVD failed, > linear'
      end if
      deallocate(A, Ainv)
    end subroutine broyden_coeff
  end subroutine mixing_coeff
Call graph
mixing_coeff calls mixing_ncoeff
mixing_ncoeff calls n_items
mixing_1d calls mixing_coeff
mixing calls mixing_1d