mixing_ncoeff – SIESTA
mixing_ncoeff Function
11 statements
Source File
private function mixing_ncoeff(mix) result(n)
Function to retrieve the number of coefficients calculated in this iteration. This is so external routines can query the size of the arrays used.
@param[in] mix the used mixer
Arguments
Type Intent Optional Attributes Name
type(tMixer), intent(in) :: mix
Return Value integer
Calls
Called by
Source Code
mixing_ncoeff
Source Code
  function mixing_ncoeff( mix ) result(n)
    type(tMixer), intent(in) :: mix
    integer :: n
    n = 0
    select case ( mix%m )
    case ( MIX_PULAY )
       n = n_items(mix%stack(2))
    case ( MIX_BROYDEN )
       n = n_items(mix%stack(2))
    end select
  end function mixing_ncoeff
All Procedures
compute_dm compute_max_diff compute_max_diff_1d compute_max_diff_2d current_itt getstackval inverse is_next mix_method mix_method_variant mixer_init mixers_history_init mixers_init mixers_print mixers_print_block mixers_reset mixers_scf_history_init mixers_scf_init mixers_scf_print mixers_scf_print_block mixers_scf_reset mixing mixing_1d mixing_2d mixing_calc_next mixing_coeff mixing_finalize mixing_init mixing_ncoeff mixing_scf_converged mixing_step norm push_diff push_F push_stack_data setup_H0 setup_hamiltonian siesta_analysis siesta_forces stack_check state_analysis state_init svd update_F
Call graph
mixing_ncoeff calls n_items
mixing_coeff calls mixing_ncoeff
mixing_1d calls mixing_ncoeff, mixing_coeff
mixing calls mixing_1d