NZTFL – SIESTA
NZTFL Function
12 statements
Source File
public function NZTFL(is, l) result(nztfl)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
integer, intent(in) :: l
Return Value integer
Calls
Contents
Source Code
NZTFL
Source Code
      FUNCTION NZTFL (IS,L)
      integer nztfl
      integer, intent(in)  :: is   ! Species index
      integer, intent(in)  :: l    ! Angular momentum of the basis funcs
C Returns the number of different basis functions
C with the same angular momentum and for a given species
      integer i
      call chk('nztfl',is)
      spp => species(is)
      nztfl = 0
      do i = 1, spp%norbs
         if (spp%orb_l(i).eq.l) nztfl = nztfl+1
      enddo
      end function nztfl
Call graph
nztfl calls chk
chk calls die
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush