psch – SIESTA
psch Subroutine
17 statements
Source File
public subroutine psch(is, r, ch, grch)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
real(kind=dp), intent(in) :: r(3)
real(kind=dp), intent(out) :: ch
real(kind=dp), intent(out) :: grch(3)
Calls
Contents
Source Code
psch
Source Code
      subroutine psch(is,r,ch,grch)
      integer, intent(in) :: is      ! Species index
      real(dp), intent(in)  :: r(3)    ! Point vector, relative to atom
      real(dp), intent(out) :: ch      ! Local pseudopot. charge dens.
      real(dp), intent(out) :: grch(3) ! Gradient of local ps. ch. dens.
C Returns 'local-pseudotential charge density'.
C Distances in Bohr, Energies in Rydbergs
C Density in electrons/Bohr**3
C  2) Returns exactly zero when |R| > Rchloc
      real(dp) :: rmod, dchdr
      call chk('psch',is)
      ch=0.0_dp
      grch(1:3)=0.0_dp
      if (floating(is)) return
      func => species(is)%chlocal
      rmod = sqrt(sum(r*r))
      if (rmod .gt. func%cutoff) return
      call rad_get(func,rmod,ch,dchdr)
      rmod=rmod+tiny20
      grch(1:3) = dchdr * r(1:3)/rmod
      end subroutine psch
Call graph
psch calls chk, floating, rad_get
chk calls die
floating calls izofis
rad_get calls splint
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush
izofis calls chk