push_F – SIESTA
push_F Subroutine
30 statements
Source File
private subroutine push_F(s_F, n, F, fact)
Arguments
Type Intent Optional Attributes Name
type(Fstack_dData1D), intent(inout) :: s_F
integer, intent(in) :: n
real(kind=dp), intent(in) :: F(n)
real(kind=dp), intent(in), optional :: fact
Calls
Called by
Source Code
push_F
Source Code
  subroutine push_F(s_F,n,F,fact)
    type(Fstack_dData1D), intent(inout) :: s_F
    integer, intent(in) :: n
    real(dp), intent(in) :: F(n)
    real(dp), intent(in), optional :: fact
    type(dData1D) :: dD1
    real(dp), pointer :: sF(:)
    integer :: in, ns
    integer :: i
    if ( .not. stack_check(s_F,n) ) then
       call die('mixing: history has changed size...')
    end if
    in = n_items(s_F)
    ns = max_size(s_F)
    if ( in == ns ) then
       ! we have to cycle the storage
       call get(s_F,1,dD1)
    else
       call newdData1D(dD1, n, '(F)')
    end if
    sF => val(dD1)
    if ( present(fact) ) then
!$OMP parallel do default(shared), private(i)
       do i = 1 , n
          sF(i) = F(i) * fact
       end do
!$OMP end parallel do
    else
       call dcopy(n, F, 1, sF, 1)
    end if
    ! Push the data to the stack
    call push(s_F,dD1)
    ! Delete double reference
    call delete(dD1)
  end subroutine push_F
All Procedures
compute_dm compute_max_diff compute_max_diff_1d compute_max_diff_2d current_itt getstackval inverse is_next mix_method mix_method_variant mixer_init mixers_history_init mixers_init mixers_print mixers_print_block mixers_reset mixers_scf_history_init mixers_scf_init mixers_scf_print mixers_scf_print_block mixers_scf_reset mixing mixing_1d mixing_2d mixing_calc_next mixing_coeff mixing_finalize mixing_init mixing_ncoeff mixing_scf_converged mixing_step norm push_diff push_F push_stack_data setup_H0 setup_hamiltonian siesta_analysis siesta_forces stack_check state_analysis state_init svd update_F
Call graph
push_f calls val, n_items, push, dcopy, get, die, newddata1d, max_size, stack_check, delete
stack_check calls n_items, get_pointer
update_f calls push_f