push_diff – SIESTA
push_diff Subroutine
37 statements
Source File
private subroutine push_diff(s_rres, s_res, alpha)
Arguments
Type Intent Optional Attributes Name
type(Fstack_dData1D), intent(inout) :: s_rres
type(Fstack_dData1D), intent(in) :: s_res
real(kind=dp), intent(in), optional :: alpha
Calls
Contents
Source Code
push_diff
Source Code
  subroutine push_diff(s_rres,s_res,alpha)
    type(Fstack_dData1D), intent(inout) :: s_rres
    type(Fstack_dData1D), intent(in) :: s_res
    real(dp), intent(in), optional :: alpha
    type(dData1D) :: dD1
    type(dData1D), pointer :: pD1
    real(dp), pointer :: res1(:), res2(:), rres(:)
    integer :: in, ns, i, n
    if ( n_items(s_res) < 2 ) then
       call die('mixing: Residual residuals cannot be calculated, &
            &inferior residual size.')
    end if
    in = n_items(s_res)
    ! First get the value of in
    pD1 => get_pointer(s_res,in-1)
    res1 => val(pD1)
    ! get the value of in
    pD1 => get_pointer(s_res,in)
    res2 => val(pD1)
    in = n_items(s_rres)
    ns = max_size(s_rres)
    if ( in == ns ) then
       ! we have to cycle the storage
       call get(s_rres,1,dD1)
    else
       call newdData1D(dD1, size(res1), '(res)')
    end if
    ! Get the residual of the residual
    rres => val(dD1)
    n = size(rres)
    if ( present(alpha) ) then
!$OMP parallel do default(shared), private(i)
       do i = 1 , n
          rres(i) = (res2(i) - res1(i)) * alpha
       end do
!$OMP end parallel do
    else
!$OMP parallel do default(shared), private(i)
       do i = 1 , n
          rres(i) = res2(i) - res1(i)
       end do
!$OMP end parallel do
    end if
    ! Push the data to the stack
    call push(s_rres,dD1)
    ! Delete double reference
    call delete(dD1)
  end subroutine push_diff
Call graph
push_diff calls val, get, die, get_pointer, push, n_items, max_size, delete