push_stack_data – SIESTA
push_stack_data Subroutine
11 statements
Source File
private subroutine push_stack_data(s_F, n)
Arguments
Type Intent Optional Attributes Name
type(Fstack_dData1D), intent(inout) :: s_F
integer, intent(in) :: n
Calls
Source Code
push_stack_data
Source Code
  subroutine push_stack_data(s_F,n)
    type(Fstack_dData1D), intent(inout) :: s_F
    integer, intent(in) :: n
    type(dData1D) :: dD1
    if ( .not. stack_check(s_F,n) ) then
       call die('mixing: history has changed size...')
    end if
    call newdData1D(dD1, n, '(F)')
    ! Push the data to the stack
    call push(s_F,dD1)
    ! Delete double reference
    call delete(dD1)
  end subroutine push_stack_data
All Procedures
compute_dm compute_max_diff compute_max_diff_1d compute_max_diff_2d current_itt getstackval inverse is_next mix_method mix_method_variant mixer_init mixers_history_init mixers_init mixers_print mixers_print_block mixers_reset mixers_scf_history_init mixers_scf_init mixers_scf_print mixers_scf_print_block mixers_scf_reset mixing mixing_1d mixing_2d mixing_calc_next mixing_coeff mixing_finalize mixing_init mixing_ncoeff mixing_scf_converged mixing_step norm push_diff push_F push_stack_data setup_H0 setup_hamiltonian siesta_analysis siesta_forces stack_check state_analysis state_init svd update_F
Call graph
push_stack_data calls push, die, newddata1d, delete, stack_check
stack_check calls n_items, get_pointer