rad_get – SIESTA
rad_get Subroutine
12 statements
Source File
public subroutine rad_get(func, r, fr, dfdr)
Arguments
Type Intent Optional Attributes Name
type(rad_func), intent(in) :: func
real(kind=dp), intent(in) :: r
real(kind=dp), intent(out) :: fr
real(kind=dp), intent(out) :: dfdr
Calls
Called by
Contents
Source Code
rad_get
Source Code
      subroutine rad_get(func,r,fr,dfdr)
      type(rad_func), intent(in) :: func
      real(dp), intent(in)         :: r
      real(dp), intent(out)        :: fr
      real(dp), intent(out)        :: dfdr
      if (func%n .eq. 0) then
          fr = 0._dp
          dfdr = 0._dp
       else
          call splint(func%delta,func%f,func%d2,func%n,r,fr,dfdr)
       endif
      end subroutine rad_get
Call graph
rad_get calls splint
psch calls rad_get
rphiatm calls rad_get
vna_sub calls rad_get
psover calls rad_get
chcore_sub calls rad_get
phiatm calls rad_get
all_phi calls rad_get