radial_read_ascii – SIESTA
radial_read_ascii Subroutine
13 statements
Source File
public subroutine radial_read_ascii(op, lun, yp1, ypn)
Arguments
Type Intent Optional Attributes Name
type(rad_func) :: op
integer :: lun
real(kind=dp), intent(in) :: yp1
real(kind=dp), intent(in) :: ypn
Calls
Contents
Source Code
radial_read_ascii
Source Code
      subroutine radial_read_ascii(op,lun,yp1,ypn)
      type(rad_func)    :: op
      real(dp), intent(in)          :: yp1, ypn
      integer lun
      integer j, npts
      real(dp) dummy
      read(lun,*) npts, op%delta, op%cutoff
      call rad_alloc(op,npts)
      do j=1,npts
         read(lun,*) dummy, op%f(j)
      enddo
      call rad_setup_d2(op,yp1,ypn)
      end subroutine radial_read_ascii
Call graph
radial_read_ascii calls rad_alloc, rad_setup_d2
rad_alloc calls re_alloc
rad_setup_d2 calls spline