reordMeshNumbering – SIESTA
reordMeshNumbering Subroutine
73 statements
Source File
private subroutine reordMeshNumbering(distr1, distr2)
Uses
fdf
Warning
This version of subroutine is called if the directive REORD1 is NOT defined.
Here an integer parameter PROCS_PER_NODE is also used as an input. Value of PROCS_PER_NODE is either read from .fdf-file or set to 4 as default.
Given a new distribution, distr2, reasign each box to the proper process. We use the following criteria:
Minimize the number of communications. Data don't need to be communicated if it belongs to the same process in different data distributions
Distribute memory needs among different NODES (group of processes that shares the same memory)
The output values are stored in the current module: meshDistr(distr2)%box(:,:,:)
Behavior
Compute the size of all the boxes of the second distribution
Reorder the list of boxes according to its size
Create a list of buckets
Arguments
Type Intent Optional Attributes Name
type(meshDisType), intent(in) :: distr1
First distribution
type(meshDisType), intent(out) :: distr2
Second distribution
Calls
Contents
Source Code
reordMeshNumbering
Source Code
      subroutine reordMeshNumbering( distr1, distr2 )
!!@warning
!! This version of subroutine is called if
!! the directive `REORD1` is defined.
!!@endwarning
!!
!! Given a new distribution, `distr2`, reasign each box to the proper
!! process. We use the following criteria:
!! > Minimize the number of communications. Data don't need to
!! > be communicated if it belongs to the same process in
!! > different data distributions
!!
!! The output values are stored in the current module:
!!        `[[moreMeshSubs(module):meshDistr(variable)]](distr2)%box(:,:,:)`
      implicit none
      type(meshDisType),   intent(in) :: distr1
        !! First distribution
      type(meshDisType),  intent(out) :: distr2
        !! Second distribution
!     Local variables
      integer                         :: P1, P2, P3, Lbox(2,3), II, I1,
     &                                   PermI
      integer,                pointer :: Isiz(:,:), perm(:), weig(:),
     &                                   invp(:), box(:,:,:)=>null()
      logical                         :: inters
!     Allocate local arrays
      nullify( Isiz, perm, invp, weig )
      call re_alloc( Isiz, 1, Nodes, 1, Nodes, 'Isiz', 'moreMeshSubs' )
      call re_alloc( perm, 1, Nodes, 'perm', 'moreMeshSubs' )
      call re_alloc( invp, 1, Nodes, 'invp', 'moreMeshSubs' )
      call re_alloc( weig, 1, Nodes, 'weig', 'moreMeshSubs' )
!     Check the intersections sizes between the two distributions
      Isiz(1:nodes,1:nodes) = 0
      do P1= 1, Nodes
        II=-1
        do P2= 1, Nodes
          call boxIntersection( distr1%box(:,:,P1),
     &                          distr2%box(:,:,P2), Lbox, inters )
          if (inters) then
            Isiz(P2,P1) = (Lbox(2,1)-Lbox(1,1)+1)*
     &                    (Lbox(2,2)-Lbox(1,2)+1)*
     &                    (Lbox(2,3)-Lbox(1,3)+1)
            if (Isiz(P2,P1).gt.II) then
              II = Isiz(P2,P1)
              I1 = P2
            endif
          endif
        enddo
        weig(P1) = II
        perm(P1) = I1
      enddo
!     Choose a proper permutation for every row
      invp(1:Nodes) = 0
      do P1= 1, Nodes
        II = -1
!       Choose the node with higher weight among those not permuted before
        do P2= 1, Nodes
          if (perm(P2).gt.0) then
            if (weig(P2).gt.II) then
              II = weig(P2)
              I1 = P2
            endif
          endif
        enddo
!       Save the permutation for this node (a negative number means that
!       the node has been permuted.
        PermI       = perm(I1)
        invp(PermI) = I1
        perm(I1)    = -PermI
!       Change the permutation of those nodes who pretend to use the
!       permutation permI
        do P2= 1, Nodes
          if (perm(P2).eq.PermI) then
            II= -1
            do P3= 1, Nodes
              if (invp(P3).eq.0 .and. Isiz(P3,P2).gt.II) then
                II = Isiz(P3,P2)
                I1 = P3
              endif
            enddo
            weig(P2) = II
            perm(P2) = I1
          endif
        enddo
      enddo
      call re_alloc( box, 1, 2, 1, 3, 1, Nodes, 'box', 'moreMeshSubs' )
      box(1:2,1:3,1:Nodes) = distr2%box(1:2,1:3,1:Nodes)
      do P1= 1, Nodes
        II = -perm(P1)
        distr2%box(1:2,1:3,P1) = box(1:2,1:3,II)
      enddo
      call de_alloc( box, 'box', 'moreMeshSubs' )
      call de_alloc( weig, 'weig', 'moreMeshSubs' )
      call de_alloc( invp, 'invp', 'moreMeshSubs' )
      call de_alloc( perm, 'perm', 'moreMeshSubs' )
      call de_alloc( Isiz, 'Isiz', 'moreMeshSubs' )
      end subroutine reordMeshNumbering
Call graph
reordmeshnumbering calls myqsort, re_alloc, boxintersection, de_alloc, fdf_get