reord – SIESTA
reord Subroutine
J.M.Soler
May 1995
76 statements
Source File
subroutine reord(FCLUST, FSEQ, NM, NSM, ITR)
Uses
precision
alloc
Re-orders a clustered data array into a sequential one and viceversa
Arguments
Type Intent Optional Attributes Name
real(kind=grid_p), intent(inout) :: FCLUST(*)
CLUSTered data:
REAL*4 FCLUST(NSM,NSM,NSM,NM1,NM2,NM3)
real(kind=grid_p), intent(inout) :: FSEQ(*)
SEQuential data:
REAL*4 FSEQ(NSM*NM1,NSM*NM2,NSM*NM3)
integer, intent(in) :: NM(3)
Number of Mesh divisions in each cell vector
integer, intent(in) :: NSM
Number of Sub-divisions in each Mesh division
integer, intent(in) :: ITR
TRanslation-direction switch
ITR=+1 => From clustered to sequential
ITR=-1 => From sequential to clustered
Calls
Called by
Contents
None
Call graph
reord calls re_alloc, de_alloc, timer
dhscf_init calls reord, distmeshdata
dhscf calls reord, distmeshdata, forhar
distmeshdata_rea calls reord
siesta_analysis calls dhscf
distmeshdata calls distmeshdata_rea
setup_hamiltonian calls dhscf
setup_h0 calls dhscf_init
siesta_forces calls setup_hamiltonian
forhar calls distmeshdata