resetRhog – SIESTA
resetRhog Subroutine
21 statements
Source File
public subroutine resetRhog(continuation)
Uses
alloc
Arguments
Type Intent Optional Attributes Name
logical, intent(in), optional :: continuation
If .true. we don't de-allocate anything, we only reset the history
Calls
Contents
Source Code
resetRhog
Source Code
 subroutine resetRhog(continuation)
   use alloc, only: de_alloc
   !< If .true. we don't de-allocate anything, we only reset the history
   logical, intent(in), optional :: continuation
   logical :: lcontinuation
   lcontinuation = .false.
   if ( present(continuation) ) lcontinuation = continuation
   if ( lcontinuation ) then
     call reset(rhog_stack)
   else
     call de_alloc(rhog_in)
     call de_alloc(rhog)
     call de_alloc(g2)
     call de_alloc(g2mask)
     call de_alloc(gindex)
     call de_alloc(star_index)
     call de_alloc(g2_diis)
     call de_alloc(rg_in)
     call de_alloc(rg_diff)
     call delete(rhog_stack)
   end if
 end subroutine resetRhog
Call graph
resetrhog calls reset, de_alloc, delete