rphiatm – SIESTA
rphiatm Subroutine
44 statements
Source File
public subroutine rphiatm(is, io, r, phi, dphidr)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
integer, intent(in) :: io
real(kind=dp), intent(in) :: r
real(kind=dp), intent(out) :: phi
real(kind=dp), intent(out) :: dphidr
Calls
Contents
Source Code
rphiatm
Source Code
      subroutine rphiatm(is,io,r,phi,dphidr)
      integer, intent(in) :: is      ! Species index
      integer, intent(in) :: io      ! Orbital index (within atom)
!              IO > 0 =>  Basis orbitals
!              IO = 0 =>  Local screened pseudopotential
!              IO < 0 =>  Kleynman-Bylander projectors
      real(dp), intent(in)  :: r       ! Radial distance, relative to atom
      real(dp), intent(out) :: phi     ! Basis orbital, KB projector, or
                                     !  local pseudopotential
      real(dp), intent(out) :: dphidr  ! Radial derivative of BO,
                                     !  KB proj, or Loc pseudopot.
C  Returns the radial component of
C  Kleynman-Bylander local pseudopotential, nonlocal projectors,
C  and atomic basis orbitals (and their radial drivatives)
C Distances in Bohr
C 1) Each projector and basis function has a well defined total
C    angular momentum (quantum number l).
C 2) Basis functions are normalized and mutually orthogonal
C 3) Projection functions are normalized and mutually orthogonal
C 4) Normalization of KB projectors |Phi_lm> is such that
C     <Psi|V_KB|Psi'> = <Psi|V_local|Psi'> +
C                   Sum_lm(epsKB_l * <Psi|Phi_lm> * <Phi_lm|Psi'>)
C    where epsKB_l is returned by function EPSKB
C 6) Returns exactly zero when |R| > RCUT(IS,IO)
C 7) RPHIATM with ITYPE = 0 is strictly equivalent to VNA_SUB
      real(dp) rmod, phir
      integer l, m, ik
      phi = 0.0_dp
      dphidr = 0._dp
      spp => species(is)
      if (io.gt.0) then
         if (io.gt.spp%norbs)  call die("rphiatm: No such orbital")
         func => spp%orbnl(spp%orb_index(io))
         l = spp%orb_l(io)
         m = spp%orb_m(io)
      else if (io.lt.0) then
         if (floating(is)) return
         ik = -io
         if (ik.gt.spp%nprojs)  call die("rphiatm: No such projector")
         func => spp%pjnl(spp%pj_index(ik))
         l = spp%pj_l(ik)
         m = spp%pj_m(ik)
      else
         if (floating(is)) return
         func => spp%vna
         l = 0
         m = 0
      endif
      rmod = r + tiny20
      if(rmod.gt.func%cutoff-tiny12) return
      call rad_get(func,rmod,phir,dphidr)
      if (l.eq.0) then
         phi=phir
      elseif (l.eq.1) then
         phi=phir*r
         dphidr=dphidr*r
         dphidr=dphidr+phir
      else
         phi=phir*r**l
         dphidr=dphidr * r**l
         dphidr=dphidr + l * phir * r**(l-1)
      endif
      end subroutine rphiatm
Call graph
rphiatm calls rad_get, floating
rad_get calls splint
floating calls izofis
izofis calls chk
chk calls die
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush