setMeshDistr – SIESTA
setMeshDistr Subroutine
24 statements
Source File
public subroutine setMeshDistr(iDistr, nsm, nsp, nml, nmpl, ntml, ntpl)
Uses
mesh
Fixes the new data limits and dimensions of the mesh to those of the data distribution iDistr.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iDistr
Distribution index of the input vector
integer, intent(in) :: nsm
Number of mesh sub-divisions in each direction
integer, intent(in) :: nsp
Number of sub-points of each mesh point
integer, intent(out) :: nml(3)
Local number of Mesh divisions in each cell vector
integer, intent(out) :: nmpl
Local number of Mesh divisions
integer, intent(out) :: ntml(3)
Local number of Mesh points in each cell vector
integer, intent(out) :: ntpl
Local number of Mesh points
Called by
Contents
Source Code
setMeshDistr
Source Code
      subroutine setMeshDistr( iDistr, nsm, nsp, nml, nmpl, ntml, ntpl )
!! Fixes the new data limits and dimensions of the mesh to those of
!! the data distribution `iDistr`.
      use mesh, only: meshLim, indexp, ipa, idop, xdop
      implicit none
      integer,  intent(in) :: iDistr
        !! Distribution index of the input vector
      integer,  intent(in) :: nsm
        !! Number of mesh sub-divisions in each direction
      integer,  intent(in) :: nsp
        !! Number of sub-points of each mesh point
      integer, intent(out) :: nml(3)
        !! Local number of Mesh divisions in each cell vector
      integer, intent(out) :: nmpl
        !! Local number of Mesh divisions
      integer, intent(out) :: ntml(3)
        !! Local number of Mesh points in each cell vector
      integer, intent(out) :: ntpl
        !! Local number of Mesh points
!     Local variables
      type(meshDisType),  pointer :: distr
      distr => meshDistr(iDistr)
      meshLim = distr%box(1:2,1:3,node+1)
      nml(1) = (MeshLim(2,1)-MeshLim(1,1)) + 1
      nml(2) = (MeshLim(2,2)-MeshLim(1,2)) + 1
      nml(3) = (MeshLim(2,3)-MeshLim(1,3)) + 1
      nmpl   = nml(1)*nml(2)*nml(3)
      ntml   = nml*nsm
      ntpl   = nmpl*nsp
      indexp => distr%indexp
      idop   => distr%idop
      xdop   => distr%xdop
      ipa    => distr%ipa
!--------------------------------------------------------------------------- END
      end subroutine setMeshDistr
Call graph
dhscf_init calls setmeshdistr
dhscf calls setmeshdistr, forhar
delk_wrapper calls setmeshdistr
forhar calls setmeshdistr
siesta_analysis calls dhscf
setup_hamiltonian calls dhscf
setup_h0 calls dhscf_init
siesta_forces calls setup_hamiltonian