siesta_forces – SIESTA
siesta_forces Subroutine
375 statements
Source File
public subroutine siesta_forces(istep)
Uses
units
precision
sys
files
siesta_cml
m_state_init
m_setup_hamiltonian
m_setup_H0
m_compute_dm
m_compute_max_diff
m_scfconvergence_test
m_post_scf_work
m_mixer
m_mixing_scf
m_mixing_scf
m_mixing_scf
m_rhog
siesta_options
parallel
m_state_analysis
m_steps
m_spin
sparse_matrices
sparse_matrices
m_convergence
m_convergence
siesta_geom
m_energies
m_forces
m_stress
siesta_master
siesta_master
m_save_density_matrix
m_iodm_old
atomlist
m_dm_charge
m_pexsi_solver
write_subs
write_subs
m_compute_energies
m_mpi_utils
fdf
m_check_walltime
m_energies
m_ts_options
m_ts_method
m_ts_global_vars
siesta_geom
sparse_matrices
sparse_matrices
m_ts_charge
m_ts_charge
m_ts_charge
m_ts_charge
m_transiesta
kpoint_scf_m
m_energies
m_initwf
This subroutine represents central SIESTA operation logic.
Todo
It might be better to split the two, putting the grid initialization into state_init (link!) and moving the calculation of to the body of the loop, done if first_scf=.true. This would suit analysis runs in which nscf = 0
The dHmax variable only has meaning for Hamiltonian mixing, or when requiring the Hamiltonian to be converged.
SCF loop
The current structure of the loop tries to reproduce the historical Siesta usage. It should be made more clear.
Two changes:
The number of scf iterations performed is exactly equal to the number specified (i.e., the "forces" phase is not counted as a final scf step)
At the change to a TranSiesta GF run the variable "first_scf" is implicitly reset to "true".
Start of SCF cycle
Conditions of exit:
At the top, to catch a non-positive nscf and # of iterations
At the bottom, based on convergence
Note implications for TranSiesta when mixing . Now will be recomputed instead of simply being inherited, however, this is required as if we have bias calculations as the electric field across the junction needs to be present.
end of SCF cycle
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: istep
Calls
Contents
Source Code
siesta_forces
Source Code
  subroutine siesta_forces(istep)
  !! This subroutine represents central SIESTA operation logic.
#ifdef MPI
    use mpi_siesta
#endif
    use units, only: eV, Ang
    use precision, only: dp
    use sys, only: bye
    use files, only: slabel
    use siesta_cml
#ifdef SIESTA__FLOOK
    use flook_siesta, only : slua_call
    use flook_siesta, only : LUA_INIT_MD, LUA_SCF_LOOP
    use siesta_dicts, only : dict_variable_add
    use m_ts_options, only : ts_scf_mixs
    use variable, only : cunpack
#ifndef NCDF_4
    use dictionary, only: assign
#endif
    use m_mixing, only : mixers_history_init
#endif
    use m_state_init
    use m_setup_hamiltonian
    use m_setup_H0
    use m_compute_dm
    use m_compute_max_diff
    use m_scfconvergence_test
    use m_post_scf_work
    use m_mixer, only: mixer
    use m_mixing_scf, only: mixing_scf_converged
    use m_mixing_scf, only: mixers_scf_history_init
    use m_mixing_scf, only: scf_mixs, scf_mix
    use m_rhog,                only: mix_rhog, compute_charge_diff
    use siesta_options
    use parallel,     only : IOnode, SIESTA_worker
    use m_state_analysis
    use m_steps
    use m_spin,                only: spin
    use sparse_matrices, only: DM_2D, S_1D
    use sparse_matrices, only: H, Hold, Dold, Dscf, Eold, Escf, maxnh
    use m_convergence, only: converger_t
    use m_convergence, only: reset, set_tolerance
    use siesta_geom,   only: na_u           ! Number of atoms in unit cell
    use m_energies,    only: Etot           ! Total energy
    use m_forces,      only: fa, cfa        ! Forces and constrained forces
    use m_stress,      only: cstress        ! Constrained stress tensor
    use siesta_master, only: forcesToMaster ! Send forces to master prog
    use siesta_master, only: siesta_server  ! Is siesta a server?
    use m_save_density_matrix, only: save_density_matrix
    use m_iodm_old,    only: write_spmatrix
    use atomlist,      only: no_u, lasto, Qtot
    use m_dm_charge, only: dm_charge
    use m_pexsi_solver,        only: prevDmax
    use write_subs,            only: siesta_write_forces
    use write_subs,            only: siesta_write_stress_pressure
#ifdef NCDF_4
    use dictionary
    use m_ncdf_siesta, only : cdf_init_file, cdf_save_settings
    use m_ncdf_siesta, only : cdf_save_state, cdf_save_basis
#endif
    use m_compute_energies, only: compute_energies
    use m_mpi_utils, only: broadcast, barrier
    use fdf
#ifdef SIESTA__PEXSI
    use m_pexsi, only: pexsi_finalize_scfloop
#endif
    use m_check_walltime
    use m_energies, only: DE_NEGF
    use m_ts_options, only : N_Elec
    use m_ts_method
    use m_ts_global_vars,      only: TSmode, TSinit, TSrun
    use siesta_geom,           only: nsc, xa, ucell, isc_off
    use sparse_matrices,       only: sparse_pattern, block_dist
    use sparse_matrices,       only: S
    use m_ts_charge, only : ts_get_charges
    use m_ts_charge,           only: TS_RHOCORR_METHOD
    use m_ts_charge,           only: TS_RHOCORR_FERMI
    use m_ts_charge,           only: TS_RHOCORR_FERMI_TOLERANCE
    use m_transiesta,          only: transiesta
    use kpoint_scf_m, only : gamma_scf
    use m_energies, only : Ef
    use m_initwf, only: initwf
    integer, intent(inout)  :: istep
    integer :: iscf
    logical :: first_scf, SCFconverged
    real(dp) :: dDmax ! Max. change in DM elements
    real(dp) :: dHmax ! Max. change in H elements
    real(dp) :: dEmax ! Max. change in EDM elements
    real(dp) :: drhog ! Max. change in rho(G) (experimental)
    real(dp), target :: G2max ! actually used meshcutoff
    type(converger_t) ::  conv_harris, conv_freeE
    ! For initwf
    integer :: istpp
#ifdef SIESTA__FLOOK
    ! len=24 from m_mixing.F90
    character(len=1), target :: next_mixer(24)
    character(len=24) :: nnext_mixer
    integer :: imix
#endif
    logical               :: time_is_up
    character(len=40)     :: tmp_str
    real(dp) :: Qcur
#ifdef NCDF_4
    type(dict) :: d_sav
#endif
#ifdef MPI
    integer :: MPIerror
#endif
    external :: die, message
#ifdef DEBUG
    call write_debug( '    PRE siesta_forces' )
#endif
#ifdef SIESTA__PEXSI
    ! Broadcast relevant things for program logic
    ! These were set in read_options, called only by "SIESTA_workers".
    call broadcast(nscf, comm=true_MPI_Comm_World)
#endif
    !  Initialization tasks for a given geometry:
    if ( SIESTA_worker )  then
       call state_init( istep )
    end if
#ifdef SIESTA__PEXSI
    if (ionode) call memory_snapshot("after state_init")
#endif
    if ( fdf_get("Sonly",.false.) ) then
       if ( SIESTA_worker ) then
          call timer( 'all', 2 )
          call timer( 'all', 3 )
       end if
       call bye("S only")
    end if
    Qcur = Qtot
#ifdef SIESTA__FLOOK
    ! Add the iscf constant to the list of variables
    ! that are available only in this part of the routine.
    call dict_variable_add('SCF.iteration',iscf)
    call dict_variable_add('SCF.converged',SCFconverged)
    call dict_variable_add('SCF.charge',Qcur)
    call dict_variable_add('SCF.dD',dDmax)
    call dict_variable_add('SCF.dH',dHmax)
    call dict_variable_add('SCF.dE',dEmax)
    call dict_variable_add('SCF.drhoG',drhog)
    ! We have to set the meshcutoff here
    ! because the asked and required ones are not
    ! necessarily the same
    call dict_variable_add('Mesh.Cutoff.Minimum',G2cut)
    call dict_variable_add('Mesh.Cutoff.Used',G2max)
    if ( mix_charge ) then
      call dict_variable_add('SCF.Mixer.Weight', wmix)
    else
      call dict_variable_add('SCF.Mixer.Weight',scf_mix%w)
      call dict_variable_add('SCF.Mixer.Restart',scf_mix%restart)
      call dict_variable_add('SCF.Mixer.Iterations',scf_mix%n_itt)
      ! Just to populate the table in the dictionary
      call dict_variable_add('SCF.Mixer.Switch',next_mixer)
    end if
    ! Initialize to no switch
    next_mixer = ' '
#endif
    !  This call computes the **non-scf** part of \( H \) and initializes the
    !  real-space grid structures:
    if ( SIESTA_worker ) call setup_H0(G2max)
    !!@todo
    !* It might be better to split the two,
    !  putting the grid initialization into **state_init (link!)** and moving the
    !  calculation of \( H_0 \) to the body of the loop, done `if first_scf=.true.`
    !  This would suit _analysis_ runs in which **nscf = 0**
    !!@endtodo
#ifdef SIESTA__PEXSI
    if (ionode) call memory_snapshot("after setup_H0")
#endif
#ifdef SIESTA__FLOOK
    ! Communicate with lua, just before entering the SCF loop
    ! This is mainly to be able to communicate
    ! mesh-related quantities (g2max)
    call slua_call(LUA, LUA_INIT_MD)
#endif
#ifdef NCDF_4
    ! Initialize the NC file
    if ( write_cdf ) then
       ! Initialize the file...
       call cdf_init_file(trim(slabel)//'.nc',is_MD = .false.)
#ifdef MPI
       call MPI_Barrier(MPI_Comm_World,MPIerror)
#endif
       ! Save the settings
       call cdf_save_settings(trim(slabel)//'.nc')
#ifdef MPI
       call MPI_Barrier(MPI_Comm_World,MPIerror)
#endif
       d_sav = ('sp'.kv.1)//('S'.kv.1)
       d_sav = d_sav//('nsc'.kv.1)//('xij'.kv.1)
       d_sav = d_sav//('xa'.kv.1)//('cell'.kv.1)
       d_sav = d_sav//('isc_off'.kv.1)
       call cdf_save_state(trim(slabel)//'.nc',d_sav)
       call delete(d_sav)
       ! Save the basis set
       call cdf_save_basis(trim(slabel)//'.nc')
    end if
#endif
    !* The dHmax variable only has meaning for Hamiltonian
    !  mixing, or when requiring the Hamiltonian to be converged.
    dDmax = -1._dp
    dHmax = -1._dp
    dEmax = -1._dp
    drhog = -1._dp
    ! Setup convergence criteria:
    if ( SIESTA_worker ) then
       if ( converge_Eharr ) then
          call reset(conv_harris)
          call set_tolerance(conv_harris,tolerance_Eharr)
       end if
       if ( converge_FreeE ) then
          call reset(conv_FreeE)
          call set_tolerance(conv_FreeE,tolerance_FreeE)
       end if
    end if
    !!# SCF loop
    !* The current structure of the loop tries to reproduce the
    !  historical Siesta usage. It should be made more clear.
    !* Two changes:
    !
    !  1. The number of scf iterations performed is exactly
    !     equal to the number specified (i.e., the "forces"
    !     phase is not counted as a final scf step)
    !  2. At the change to a TranSiesta GF run the variable "first_scf"
    !     is implicitly reset to "true".
    !
    !!## Start of SCF cycle
    !
    !* Conditions of exit:
    !
    !  * At the top, to catch a non-positive nscf and # of iterations
    !  * At the bottom, based on convergence
    !
    iscf = 0
    do while ( iscf < nscf )
       iscf = iscf + 1
       !* Note implications for TranSiesta when mixing \(H\).
       !  Now \(H\) will be recomputed instead of simply being
       !  inherited, however, this is required as if
       !  we have bias calculations as the electric
       !  field across the junction needs to be present.
       first_scf = (iscf == 1)
       if ( SIESTA_worker ) then
          ! Check whether we are short of time to continue
          call check_walltime(time_is_up)
          if ( time_is_up ) then
             ! Save DM/H if we were not saving it...
             !   Do any other bookeeping not done by "die"
             call timer('all',2)
             call timer('all',3)
             call message('WARNING', &
                  'SCF_NOT_CONV: SCF did not converge'// &
                  ' before wall time exhaustion')
             write(tmp_str,"(2(i5,tr1),f12.6)") istep, iscf, prevDmax
             call message(' (info)',"Geom step, scf iteration, dmax:"//trim(tmp_str))
             call barrier() ! A non-root node might get first to the 'die' call
             call die("OUT_OF_TIME: Time is up.")
          end if
          call timer( 'IterSCF', 1 )
          if (cml_p) &
               call cmlStartStep( xf=mainXML, type='SCF', index=iscf )
          if ( mixH ) then
             if ( first_scf ) then
                if (fdf_get("Read-H-from-file",.false.)) then
                   call get_H_from_file()
                else
                   call setup_hamiltonian( iscf )
                end if
             end if
             call compute_DM( iscf )
             ! Maybe set Dold to zero if reading charge or H...
             call compute_max_diff(Dold, Dscf, dDmax)
             if ( converge_EDM ) &
                  call compute_max_diff(Eold, Escf, dEmax)
             call setup_hamiltonian( iscf )
             call compute_max_diff(Hold, H, dHmax)
          else
             call setup_hamiltonian( iscf )
             call compute_max_diff(Hold, H, dHmax)
             call compute_DM( iscf )
             call compute_max_diff(Dold, Dscf, dDmax)
             if ( converge_EDM ) &
                  call compute_max_diff(Eold, Escf, dEmax)
          end if
          ! This iteration has completed calculating the new DM
          call compute_energies( iscf )
          if ( mix_charge ) then
             call compute_charge_diff( drhog )
          end if
          ! Note: For DM and H convergence checks. At this point:
          ! If mixing the DM:
          !        Dscf=DM_out, Dold=DM_in(mixed), H=H_in, Hold=H_in(prev step)
          !        dDmax=maxdiff(DM_out,DM_in)
          !        dHmax=maxdiff(H_in - H_in(prev step))
          ! If mixing the Hamiltonian:
          !        Dscf=DM_out, Dold=DM_in, H=H_(DM_out), Hold=H_in(mixed)
          !        dDmax=maxdiff(DM_out,DM_in)
          !        dHmax=maxdiff(H(DM_out),H_in)
          call scfconvergence_test( first_scf, iscf, &
               dDmax, dHmax, dEmax, &
               conv_harris, conv_freeE, &
               SCFconverged )
          ! ** Check this heuristic
          if ( mixH ) then
             prevDmax = dHmax
          else
             prevDmax = dDmax
          end if
          ! Calculate current charge based on the density matrix
          call dm_charge(spin, DM_2D, S_1D, Qcur)
          ! Check whether we should step to the next mixer
          call mixing_scf_converged( SCFconverged )
          if ( SCFconverged .and. iscf < min_nscf ) then
             SCFconverged = .false.
             if ( IONode ) then
                write(*,"(a,i0)") &
                     "SCF cycle continued for minimum number of iterations: ", &
                     min_nscf
             end if
          end if
          ! In case the user has requested a Fermi-level correction
          ! Then we start by correcting the fermi-level
          if ( TSrun .and. SCFconverged .and. &
               TS_RHOCORR_METHOD == TS_RHOCORR_FERMI ) then
             if ( abs(Qcur - Qtot) > TS_RHOCORR_FERMI_TOLERANCE ) then
                ! Call transiesta with fermi-correct
                call transiesta(iscf,spin%H, &
                     block_dist, sparse_pattern, Gamma_Scf, ucell, nsc, &
                     isc_off, no_u, na_u, lasto, xa, maxnh, H, S, &
                     Dscf, Escf, Ef, Qtot, .true., DE_NEGF)
                ! We will not have not converged as we have just
                ! changed the Fermi-level
                SCFconverged = .false.
             end if
          end if
          if ( monitor_forces_in_scf ) call compute_forces()
          ! Mix_after_convergence preserves the old behavior of
          ! the program.
          if ( (.not. SCFconverged) .or. mix_after_convergence) then
             ! Mix for next step
             if ( mix_charge ) then
                call mix_rhog( iscf )
             else
                call mixer( iscf )
             end if
             ! Save for possible restarts
             if ( mixH ) then
                call write_spmatrix(H,file="H_MIXED",when=writeH)
                call save_density_matrix(file="DM_OUT",when=writeDM)
             else
                call save_density_matrix(file="DM_MIXED",when=writeDM)
                call write_spmatrix(H,file="H_DMGEN",when=writeH)
             end if
          end if
          call timer( 'IterSCF', 2 )
          call print_timings( first_scf, istep == inicoor )
          if (cml_p) call cmlEndStep(mainXML)
#ifdef SIESTA__FLOOK
          ! Communicate with lua
          call slua_call(LUA, LUA_SCF_LOOP)
          ! Retrieve an easy character string
          nnext_mixer = cunpack(next_mixer)
          if ( len_trim(nnext_mixer) > 0 .and. .not. mix_charge ) then
             if ( TSrun ) then
                do imix = 1 , size(ts_scf_mixs)
                   if ( ts_scf_mixs(imix)%name == nnext_mixer ) then
                      call mixers_history_init(ts_scf_mixs)
                      scf_mix => ts_scf_mixs(imix)
                      exit
                   end if
                end do
             else
                do imix = 1 , size(scf_mixs)
                   if ( scf_mixs(imix)%name == nnext_mixer ) then
                      call mixers_history_init(scf_mixs)
                      scf_mix => scf_mixs(imix)
                      exit
                   end if
                end do
             end if
             ! Check that we indeed have changed the mixer
             if ( IONode .and. scf_mix%name /= nnext_mixer ) then
                write(*,'(2a)') 'siesta-lua: WARNING: trying to change ', &
                     'to a non-existing mixer! Not changing anything!'
             else if ( IONode ) then
                write(*,'(2a)') 'siesta-lua: Switching mixer method to: ', &
                     trim(nnext_mixer)
             end if
             ! Reset for next loop
             next_mixer = ' '
             ! Update the references
             call dict_variable_add('SCF.Mixer.Weight',scf_mix%w)
             call dict_variable_add('SCF.Mixer.Restart',scf_mix%restart)
             call dict_variable_add('SCF.Mixer.Iterations',scf_mix%n_itt)
          end if
#endif
          ! ... except that we might continue for TranSiesta
          if ( SCFconverged ) then
             call transiesta_switch()
             ! might reset SCFconverged and iscf
          end if
       else
          ! non-siesta worker
          call compute_DM( iscf )
       end if
#ifdef SIESTA__PEXSI
       call broadcast(iscf, comm=true_MPI_Comm_World)
       call broadcast(SCFconverged, comm=true_MPI_Comm_World)
#endif
       !  Exit if converged:
       if ( SCFconverged ) exit
    end do
    !! **end of SCF cycle**
#ifdef SIESTA__PEXSI
    if ( isolve == SOLVE_PEXSI ) then
       call pexsi_finalize_scfloop()
    end if
#endif
    if ( .not. SIESTA_worker ) return
    call end_of_cycle_save_operations()
    if ( .not. SCFconverged ) then
       if ( SCFMustConverge ) then
          call message('FATAL','SCF_NOT_CONV: SCF did not converge' // &
               ' in maximum number of steps (required).')
          write(tmp_str,"(2(i5,tr1),f12.6)") istep, iscf, prevDmax
          call message(' (info)',"Geom step, scf iteration, dmax:"//trim(tmp_str))
          call timer( 'all', 2 ) ! New call to close the tree
          call timer( 'all', 3 )
          call barrier()
          call die('ABNORMAL_TERMINATION')
       else if ( .not. harrisfun ) then
          call message('WARNING', &
               'SCF_NOT_CONV: SCF did not converge  in maximum number of steps.')
          write(tmp_str,"(2(i5,tr1),f12.6)") istep, iscf, prevDmax
          call message(' (info)',"Geom step, scf iteration, dmax:"//trim(tmp_str))
       end if
    end if
    ! To write the initial wavefunctions to be used in a
    ! consequent TDDFT run.
    if ( writetdwf ) then
       istpp = 0
       call initwf(istpp,totime)
    end if
    if ( TSmode.and.TSinit.and.(.not. SCFConverged) ) then
       ! Signal that the DM hasn't converged, so we cannot
       ! continue to the transiesta routines
       call die('ABNORMAL_TERMINATION')
    end if
    ! Clean-up here to limit memory usage
    call mixers_scf_history_init( )
    ! End of standard SCF loop.
    ! Do one more pass to compute forces and stresses
    ! Note that this call will no longer overwrite H while computing the
    ! final energies, forces and stresses...
    if ( fdf_get("compute-forces",.true.) ) then
       call post_scf_work( istep, iscf , SCFconverged )
#ifdef SIESTA__PEXSI
       if (ionode) call memory_snapshot("after post_scf_work")
#endif
    end if
    ! ... so H at this point is the latest generator of the DM, except
    ! if mixing H beyond self-consistency or terminating the scf loop
    ! without convergence while mixing H
    call state_analysis( istep )
#ifdef SIESTA__PEXSI
    if (ionode) call memory_snapshot("after state_analysis")
#endif
    ! If siesta is running as a subroutine, send forces to master program
    if (siesta_server) &
         call forcesToMaster( na_u, Etot, cfa, cstress )
#ifdef DEBUG
    call write_debug( '    POS siesta_forces' )
#endif
  contains
    ! Read the Hamiltonian from a file
    subroutine get_H_from_file()
      use sparse_matrices, only: maxnh, numh, listh, listhptr
      use atomlist,        only: no_l
      use m_spin,          only: spin
      use m_iodm_old,      only: read_spmatrix
      logical :: found
      call read_spmatrix(maxnh, no_l, spin%H, numh, &
           listhptr, listh, H, found, userfile="H_IN")
      if (.not. found) call die("Could not find H_IN")
    end subroutine get_H_from_file
    ! Computes forces and stresses with the current DM_out
    subroutine compute_forces()
      use siesta_options, only: recompute_H_after_scf
      use m_final_H_f_stress, only: final_H_f_stress
      use write_subs
      real(dp), allocatable :: fa_old(:,:), Hsave(:,:)
      allocate(fa_old(size(fa,dim=1),size(fa,dim=2)))
      fa_old(:,:) = fa(:,:)
      if ( recompute_H_after_scf ) then
         allocate(Hsave(size(H,dim=1),size(H,dim=2)))
         Hsave(:,:) = H(:,:)
      end if
      call final_H_f_stress( istep , iscf , .false. )
      if ( recompute_H_after_scf ) then
         H(:,:) = Hsave(:,:)
         deallocate(Hsave)
      end if
      if (ionode) then
         print *, "Max diff in force (eV/Ang): ", &
              maxval(abs(fa-fa_old))*Ang/eV
         call siesta_write_forces(-1)
         call siesta_write_stress_pressure()
      endif
      deallocate(fa_old)
    end subroutine compute_forces
    ! Print out timings of the first SCF loop only
    subroutine print_timings(first_scf, first_md)
      use timer_options, only: use_tree_timer
      use m_ts_global_vars, only : TSrun
      logical, intent(in) :: first_scf, first_md
      character(len=20) :: routine
      ! If this is not the first iteration,
      ! we immediately return.
      if ( .not. first_scf ) return
      if ( .not. first_md ) return
      routine = 'IterSCF'
      if ( TSrun ) then
         ! with Green function generation
         ! The tree-timer requires direct
         ! children of the routine to be
         ! queried.
         ! This is not obeyed in the TS case... :(
         if ( .not. use_tree_timer ) then
            routine = 'TS'
         end if
      endif
      call timer( routine, 3 )
    end subroutine print_timings
    ! Depending on various conditions, save the DMin
    ! or the DMout, and possibly keep a copy of H
    ! NOTE: Only if the scf cycle converged before exit it
    ! is guaranteed that the DM is "pure out" and that
    ! we can recover the right H if mixing H.
    !
    subroutine end_of_cycle_save_operations()
      logical :: DM_write, H_write
      ! Depending on the option we should overwrite the
      ! Hamiltonian
      if ( mixH .and. .not. mix_after_convergence ) then
         ! Make sure that we keep the H actually used
         ! to generate the last DM, if needed.
         H = Hold
      end if
      DM_write = write_DM_at_end_of_cycle .and. &
           .not. writeDM
      H_write = write_H_at_end_of_cycle .and. &
           .not. writeH
      if ( mix_after_convergence ) then
         ! If we have been saving them, there is no point in doing
         ! it one more time
         if ( mixH ) then
            call save_density_matrix(file="DM_OUT", when=DM_write)
            call write_spmatrix(H,file="H_MIXED", when=H_write)
         else
            call save_density_matrix(file="DM_MIXED", when=DM_write)
            call write_spmatrix(H,file="H_DMGEN", when=H_write)
         end if
      else
         call save_density_matrix(file="DM_OUT", when=DM_write)
         call write_spmatrix(H,file="H_DMGEN", when=H_write)
      end if
    end subroutine end_of_cycle_save_operations
    subroutine transiesta_switch()
      use precision,             only: dp
      use parallel,              only: IONode
      use class_dSpData2D
      use class_Fstack_dData1D
      use densematrix, only: resetDenseMatrix
      use siesta_options,        only: fire_mix, broyden_maxit
      use siesta_options,        only: dDtol, dHtol
      use sparse_matrices, only : DM_2D, EDM_2D
      use atomlist, only: lasto
      use siesta_geom, only: nsc, isc_off, na_u, xa, ucell
      use m_energies, only : Ef
      use m_mixing, only: mixers_history_init
      use m_mixing_scf, only: scf_mix, scf_mixs
      use m_rhog, only: resetRhoG
      use m_ts_global_vars,      only: TSinit, TSrun
      use m_ts_global_vars,      only: ts_print_transiesta
      use m_ts_method
      use m_ts_options,          only: N_Elec, Elecs
      use m_ts_options,          only: DM_bulk
      use m_ts_options,          only: val_swap
      use m_ts_options,          only: ts_Dtol, ts_Htol
      use m_ts_options,          only: ts_hist_keep
      use m_ts_options,          only: ts_siesta_stop
      use m_ts_options,          only: ts_scf_mixs
      use m_ts_electype
      integer :: iEl, na_a
      integer, allocatable :: allowed_a(:)
      real(dp), pointer :: DM(:,:), EDM(:,:)
      ! We are done with the initial diagon run
      ! Now we start the TRANSIESTA (Green functions) run
      if ( .not. TSmode ) return
      if ( .not. TSinit ) return
      ! whether we are in siesta initialization step
      TSinit = .false.
      ! whether transiesta is running
      TSrun  = .true.
      ! If transiesta should stop immediately
      if ( ts_siesta_stop ) then
         if ( IONode ) then
            write(*,'(a)') 'ts: Stopping transiesta (user option)!'
         end if
         return
      end if
      ! Reduce memory requirements
      call resetDenseMatrix()
      ! Signal to continue...
      ! These two variables are from the top-level
      ! routine (siesta_forces)
      SCFconverged = .false.
      iscf = 0
      ! DANGER (when/if going back to the DIAGON run, we should
      ! re-instantiate the original mixing value)
      call val_swap(dDtol, ts_Dtol)
      call val_swap(dHtol, ts_Htol)
      ! Clean up mixing history
      if ( mix_charge ) then
        call resetRhoG(.true.)
      else
        if ( associated(ts_scf_mixs, target=scf_mixs) ) then
          do iel = 1 , size(scf_mix%stack)
            call reset(scf_mix%stack(iel), -ts_hist_keep)
            ! Reset iteration count as certain
            ! mixing schemes require this for consistency
            scf_mix%cur_itt = n_items(scf_mix%stack(iel))
          end do
        else
          call mixers_history_init(scf_mixs)
        end if
      end if
      ! Transfer scf_mixing to the transiesta mixing routine
      scf_mix => ts_scf_mixs(1)
#ifdef SIESTA__FLOOK
      if ( .not. mix_charge ) then
         call dict_variable_add('SCF.Mixer.Weight',scf_mix%w)
         call dict_variable_add('SCF.Mixer.Restart',scf_mix%restart)
         call dict_variable_add('SCF.Mixer.Iterations',scf_mix%n_itt)
      end if
#endif
      call ts_print_transiesta()
      ! In case of transiesta and DM_bulk.
      ! In case we ask for initialization of the DM in bulk
      ! we read in the DM files from the electrodes and
      ! initialize the bulk to those values
      if ( DM_bulk > 0 ) then
         if ( IONode ) then
            write(*,'(/,2a)') 'transiesta: ', &
                 'Initializing bulk DM in electrodes.'
         end if
         na_a = 0
         do iEl = 1 , na_u
            if ( .not. a_isDev(iEl) ) na_a = na_a + 1
         end do
         allocate(allowed_a(na_a))
         na_a = 0
         do iEl = 1 , na_u
            ! We allow the buffer atoms as well (this will even out the
            ! potential around the back of the electrode)
            if ( .not. a_isDev(iEl) ) then
               na_a = na_a + 1
               allowed_a(na_a) = iEl
            end if
         end do
         do iEl = 1 , N_Elec
            if ( IONode ) then
               write(*,'(/,2a)') 'transiesta: ', &
                    'Reading in electrode TSDE for '// &
                    trim(Elecs(iEl)%Name)
            end if
            ! Copy over the DM in the lead
            ! Notice that the EDM matrix that is copied over
            ! will be equivalent at Ef == 0
            call copy_DM(Elecs(iEl),na_u,xa,lasto,nsc,isc_off, &
                 ucell, DM_2D, EDM_2D, na_a, allowed_a)
         end do
         ! Clean-up
         deallocate(allowed_a)
         if ( IONode ) then
            write(*,*) ! new-line
         end if
         ! The electrode EDM is aligned at Ef == 0
         ! We need to align the energy matrix
         DM  => val(DM_2D)
         EDM => val(EDM_2D)
         iEl =  size(DM)
         call daxpy(iEl,Ef,DM(1,1),1,EDM(1,1),1)
      end if
    end subroutine transiesta_switch
  end subroutine siesta_forces
Call graph
siesta_forces calls state_init, scfconvergence_test, set_tolerance, fdf_get, message, mixers_scf_history_init, compute_max_diff, write_spmatrix, bye, save_density_matrix, state_analysis, compute_charge_diff, mixing_scf_converged, dm_charge, setup_hamiltonian, post_scf_work, check_walltime, barrier, compute_dm, compute_energies, initwf, reset, mixer, mix_rhog, transiesta, die, timer
state_init calls fdf_get, bye, timer, volcel, mscell, re_alloc, newddata2d, superc, ioxv, setup_ts_kpoint_scf, setup_ordern_indexes, setup_dmhs_netcdf_file, new_dm, exact_sc_ag, cmladdproperty, sporb_to_spatom, newzspdata2d, siesta_write_positions, write_debug, domaindecom, globalize_or, crtsparsity_sc, proximity_check, overlap, cmlendpropertylist, newdspdata1d, newsparsity, kpoint_nullify, hsparse, outcoor, cmlstartpropertylist, isc_off, setup_dm_netcdf_file, nsc, mixers_history_init, chess_init, iotdxv, file_exist, val, attach, sp_to_spglobal, init_val, dict_repopulate_md, kpoint_delete, get_chess_parameter, ts_tri_analyze, ucell, nscold, delete, escf, time_io, check_cohp, listhptr, xij_offset, setup_kpoint_scf, ts_sparse_init, normalize_dm, die, globalize_sum, newdspdata2d, message, madelung, numh, write_zmatrix, ts_write_tshs, fname_tshs
mixers_scf_history_init calls mixers_history_init
compute_max_diff calls compute_max_diff_2d, compute_max_diff_1d
bye calls mpi_finalize, pxfflush, cmlfinishfile
state_analysis calls timer, volcel, moments, cartesianforce_to_zmatforce, print_spin, siesta_write_stress_pressure, slua_call, update_freeeharris, update_freee, born_charge, cmladdproperty, mulliken, eggbox, cmlendmodule, write_debug, fixed, kin_stress, cmlstartmodule, amass, va, siesta_write_forces, wallclock, remove_intramol_pressure
compute_charge_diff calls fdf_get
mixing_scf_converged calls reset
setup_hamiltonian calls bye, timer, re_alloc, h, dhscf, write_hsx, hubbard_term, val, hold, de_alloc, dimag, update_e0, die, globalize_sum, dscf
compute_dm calls bye, transiesta, timer, zminim, write_orb_indx, eold, write_dmh_netcdf, dminim, ordern, diagon, val, dold, pexsi_solver, escf, chess_wrapper, normalize_dm, compute_ebs_shift, mpi_bcast, dscf, write_hs_formatted
compute_energies calls fdf_get, update_freee, update_dena, update_etot
mix_rhog calls fdf_get, n_items, diis
compute_max_diff_2d calls die
dhscf calls bye, timer, volcel, re_alloc, write_debug, de_alloc, die, elecs, forhar, ts_voltage, mpi_barrier, ts_hartree_fix, ddot, jms_setmeshdistr, mpitrace_restart, bsc_cellxc, write_grid_netcdf, setmeshdistr, rhoofdsp, get_field_from_dipole, vmatsp, add_potential_from_field, hartree_add, dfscf, reord, compute_partial_charges, write_tdrho, partialcoreonmesh, mymeshbox, neutralatomonmesh, distmeshdata, vmat, mpi_allreduce, vacuum_level, localchargeonmesh, rhoofd, write_rho
mixers_history_init calls delete, current_itt, new
compute_max_diff_1d calls die
check_cohp calls message
die calls pxfflush, cmlfinishfile, mpi_abort, io_close, io_assign, pxfabort
message calls pxfflush, io_close, io_assign
forhar calls re_alloc, de_alloc, jms_setmeshdistr, bsc_cellxc, setmeshdistr, mymeshbox, distmeshdata
dfscf calls timer, re_alloc, de_alloc, die, indxuo, listsc, endpht, listp2, needdscfl, listdlptr, matrixotom, lstpht, globaltolocalorb, numdl, rcut, alloc_default, dscfl, listdl
reord calls timer, re_alloc, de_alloc
distmeshdata calls distmeshdata_rea, distmeshdata_int
vmat calls timer, re_alloc, de_alloc, matrixmtoo, phi, indxuo, listsc, endpht, listp2, needdscfl, listdlptr, lstpht, globaltolocalorb, numdl, rcut, listdl
rhoofd calls timer, re_alloc, de_alloc, die, phi, indxuo, listsc, endpht, listp2, needdscfl, listdlptr, matrixotom, lstpht, globaltolocalorb, numdl, rcut, dscfl, listdl
write_rho calls write_debug, de_alloc, mpi_barrier, io_close, io_assign, mpi_wait, mpi_irecv
distmeshdata_rea calls timer, re_alloc, write_debug, de_alloc, die, mpi_barrier, reord, mpitrace_event, boxintersection
distmeshdata_int calls re_alloc, de_alloc, die, boxintersection
rcut calls chk
chk calls die