splitwload – SIESTA
splitwload Subroutine
90 statements
Source File
private subroutine splitwload(Nodes, Node, nm, wload, iDistr, oDistr)
Uses
mpi_siesta
Compute the limits of a new distribution, trying to split the load of the array wload. We use the nested disection algorithm in order to split the mesh in the 3 dimensions.
We use the nested disection algorithm to split the load associated to the vector wload among all the processes. The problem is that every process have a different part of wload. Every time that we want to split a piece of the mesh, we should find which processors have that information.
wload is a 3D array. In every iteration of the algorithm we should decide the direction of the cut. Then we should made a reduction of this 3-D array to a 1-D array (according to the selected direction).
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Nodes
Total number of nodes
integer, intent(in) :: Node
Current process ID (from 1 to Node)
integer, intent(in) :: nm(3)
Number of mesh sub-divisions in each direction
integer, intent(in) :: wload(*)
Weights of every point of the mesh.
type(meshDisType), intent(in) :: iDistr
Input distribution
type(meshDisType), intent(out) :: oDistr
Output distribution
Calls
Contents
Source Code
splitwload
Source Code
      subroutine splitwload( Nodes, Node, nm, wload, iDistr, oDistr )
!! Compute the limits of a new distribution, trying to split the load
!! of the array `wload`. We use the nested disection algorithm in
!! order to split the mesh in the 3 dimensions.
!!
!! We use the nested disection algorithm to split the load associated
!! to the vector `wload` among all the processes. The problem is that
!! every process have a different part of wload. Every time that we want
!! to split a piece of the mesh, we should find which processors have that
!! information.
!!
!! `wload` is a 3D array. In every iteration of the algorithm we should
!! decide the direction of the cut. Then we should made a reduction of
!! this 3-D array to a 1-D array (according to the selected direction).
      use mpi_siesta
      implicit none
      integer,      intent(in)      :: Nodes
        !! Total number of nodes
      integer,      intent(in)      :: Node
        !! Current process ID (from 1 to Node)
      integer,      intent(in)      :: nm(3)
        !! Number of mesh sub-divisions in each direction
      integer,      intent(in)      :: wload(*)
        !! Weights of every point of the mesh.
      type(meshDisType),intent(in)  :: iDistr
        !! Input distribution
      type(meshDisType),intent(out) :: oDistr
        !! Output distribution
!     Local variables
      character(len=*), parameter :: myName = moduName//'splitwload '
      character(len=*), parameter :: errMsg = myName//'ERROR: '
      integer                     :: PP, Lbox(2,3), Ldim,
     &                               QQ, P1, P2, POS, ini
      integer(i8b),          pointer :: lwload(:), gwload(:), recvB(:)
      logical                     :: found, inters
      integer                     :: mGdim, mLdim, nAxis, nms(3)
      integer(i8b)                   :: h1, h2
      integer,            pointer :: PROCS(:)
      integer                     :: MPIerror, Status(MPI_Status_Size)
      call timer( 'SPLOAD', 1 )
!     At the begining of the algorithm all the mesh is assigned to the
!     first node:  oDistr%box(*,*,1) = nm
      oDistr%box(1,1,1) = 1
      oDistr%box(2,1,1) = nm(1)
      oDistr%box(1,2,1) = 1
      oDistr%box(2,2,1) = nm(2)
      oDistr%box(1,3,1) = 1
      oDistr%box(2,3,1) = nm(3)
      oDistr%box(1:2,1:3,2:Nodes) = 0
      nms = nm
!     Array PROCS will contain the number of processes that are associated to
!     every box. At the begining all the mesh is assigned to process 1, then
!     PROCS(1)=Nodes, while the rest are equal to zero
      nullify( PROCS, lwload, gwload, recvB )
      call re_alloc( PROCS, 1, Nodes, 'PROCS', 'moreMeshSubs' )
      PROCS(1)       = Nodes
      PROCS(2:Nodes) = 0
      found = .true.
      do while(found)
!       Choose the direction to cut the mesh
        nAxis = 3
        if (nms(2).gt.nms(nAxis)) nAxis = 2
        if (nms(1).gt.nms(nAxis)) nAxis = 1
        nms(nAxis) = (nms(nAxis)+1)/2
!       Check if we still have to keep cutting the mesh
        found = .false.
        do PP=Nodes, 1, -1
          if (PROCS(PP).GT.1) then
!           There are more than one processes associated to the mesh
!           of process PP. We are going to split the mesh in two parts
!           of p1 and p2 processors.
            p1 = PROCS(PP)/2
            p2 = PROCS(PP) - p1
            found = .true.
!           Check if the current partition has intersection with the piece of
!           mesh that we want to cut.
            call boxIntersection( oDistr%box(:,:,PP),
     &                            iDistr%box(:,:,Node),
     &                            Lbox, inters )
            if (Node.eq.PP) then
              mGdim = oDistr%box(2,nAxis,PP)-oDistr%box(1,nAxis,PP)+1
              call re_alloc( gwload, 1, mGdim, 'gwload','moreMeshSubs' )
              call re_alloc( recvB, 1, mGdim, 'recvB', 'moreMeshSubs' )
            endif
            if (inters) then
!             If there is an intersection I should reduce the intersected part
!             from a 3-D array to a 1-D array.
              mLdim = Lbox(2,nAxis) - Lbox(1,nAxis) + 1
              call re_alloc( lwload, 1, mLdim, 'lwload',
     &                       'moreMeshSubs' )
              call reduce3Dto1D( nAxis, iDistr%box(:,:,Node), Lbox,
     &                           wload, lwload )
            endif
            if (Node.eq.PP) then
!             If, I'm the process PP I should receive the information from other
!             processes
              gwload = 0
              do QQ= 1, Nodes
                call boxIntersection( oDistr%box(:,:,PP),
     &                                iDistr%box(:,:,QQ),
     &                                Lbox, inters )
                if (inters) then
                  Ldim = Lbox(2,nAxis) - Lbox(1,nAxis) + 1
                  ini  = Lbox(1,nAxis) - oDistr%box(1,nAxis,PP)
                  if (PP.eq.QQ) then
                    gwload(ini+1:ini+Ldim) =
     &              gwload(ini+1:ini+Ldim) + lwload(1:Ldim)
                  else
                    call mpi_recv( recvB, Ldim, MPI_INTEGER8, QQ-1, 1,
     &                             MPI_Comm_world, Status, MPIerror )
                    gwload(ini+1:ini+Ldim) =
     &              gwload(ini+1:ini+Ldim) + recvB(1:Ldim)
                  endif
                endif
              enddo
              call de_alloc( recvB, 'recvB', 'moreMeshSubs' )
!             Process PP computes where to cut the mesh
              call vecBisec( mGdim, gwload(1:mGdim),
     &                        PROCS(PP), POS, h1, h2 )
              call de_alloc(gwload, 'gwload', 'moreMeshSubs')
            else if (inters) then
!             If, I'm not the process PP I should send the information to
!             the process PP
              call MPI_Send( lwload, mLdim,
     &                       MPI_INTEGER8, PP-1, 1, MPI_Comm_World,
     &                       MPIerror )
            endif
            if (associated(lwload))
     &        call de_alloc(lwload, 'lwload', 'moreMeshSubs')
!           Process PP send the position of the cut to the rest of processes
            call MPI_Bcast( pos, 1, MPI_integer, PP-1,
     &                      MPI_Comm_World, MPIerror )
!           We have splitted the piece of mesh associated to process PP
!           in two parts. One would be stored in position PP and the other
!           would be stored in position PP+P1
            QQ                     = PP + P1
            oDistr%box(1:2,1:3,QQ) = oDistr%box(1:2,1:3,PP)
            pos                    = oDistr%box(1,naxis,QQ) + pos
            oDistr%box(1,naxis,QQ) = pos
            oDistr%box(2,naxis,PP) = pos - 1
!           We should actualize the numbers of processes associated to PP and QQ
            PROCS(PP)              = P1
            PROCS(QQ)              = P2
          endif
        enddo
      enddo
      call de_alloc( PROCS, 'PROCS', 'moreMeshSubs')
      call timer( 'SPLOAD', 2 )
      end subroutine splitwload
Call graph
splitwload calls boxintersection, mpi_bcast, re_alloc, mpi_recv, timer, de_alloc, reduce3dto1d, mpi_send