stack_check – SIESTA
stack_check Function
12 statements
Source File
private function stack_check(stack, n) result(check)
Arguments
Type Intent Optional Attributes Name
type(Fstack_dData1D), intent(inout) :: stack
integer, intent(in) :: n
Return Value logical
Calls
Called by
Source Code
stack_check
Source Code
  function stack_check(stack,n) result(check)
    type(Fstack_dData1D), intent(inout) :: stack
    integer, intent(in) :: n
    logical :: check
    ! Local arrays
    type(dData1D), pointer :: dD1
    if ( n_items(stack) == 0 ) then
       check = .true.
    else
       ! Check that the stack stored arrays are
       ! of same size...
       dD1 => get_pointer(stack,1)
       check = n == size(dD1)
    end if
  end function stack_check
All Procedures
compute_dm current_itt getstackval inverse is_next mix_method mix_method_variant mixer_init mixers_history_init mixers_init mixers_print mixers_print_block mixers_reset mixers_scf_history_init mixers_scf_init mixers_scf_print mixers_scf_print_block mixers_scf_reset mixing mixing_1d mixing_2d mixing_calc_next mixing_coeff mixing_finalize mixing_init mixing_ncoeff mixing_scf_converged mixing_step norm push_diff push_F push_stack_data setup_H0 setup_hamiltonian siesta_analysis siesta_forces stack_check state_analysis state_init svd update_F
Call graph
stack_check calls n_items, get_pointer
update_f calls stack_check, push_f
push_stack_data calls stack_check
push_f calls stack_check