SYMFIO – SIESTA
SYMFIO Function
34 statements
Source File
public function SYMFIO(is, io) result(symfio)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
integer, intent(in) :: io
Return Value character(len=20)
Calls
Contents
Source Code
SYMFIO
Source Code
      FUNCTION SYMFIO (IS,IO)
      character(len=20) symfio
      integer, intent(in) :: is    ! Species index
      integer, intent(in) :: io    ! Orbital index (within atom)
C Returns a label describing the symmetry of the
C   basis orbital or Kleynman-Bylander projector.
C    INTEGER  IO   : Orbital index (within atom)
C                    IO > 0 => Basis orbitals
C                    IO < 0 => Kleynman-Bylander projectors
C   INTEGER SYMFIO  : Symmetry of the orbital or KB projector
C  2) Returns 's' for IO = 0
      integer ilm, i, lorb, morb
      integer, parameter  :: lmax_sym=4
      character(len=11)  sym_label((lmax_sym+1)*(lmax_sym+1))
      data  sym_label(1)
     .  / 's' /
      data (sym_label(i),i=2,4)
     .  / 'py', 'pz', 'px' /
      data (sym_label(i),i=5,9)
     .  / 'dxy', 'dyz', 'dz2', 'dxz', 'dx2-y2' /
      data (sym_label(i),i=10,16)
     .  / 'fy(3x2-y2)', 'fxyz', 'fz2y', 'fz3',
     .    'fz2x', 'fz(x2-y2)', 'fx(x2-3y2)' /
      data (sym_label(i),i=17,25)
     .  / 'gxy(x2-y2)', 'gzy(3x2-y2)', 'gz2xy', 'gz3y', 'gz4',
     .    'gz3x', 'gz2(x2-y2)', 'gzx(x2-3y2)', 'gx4+y4' /
      call chk('rcut',is)
      spp => species(is)
      if (io.gt.0) then
         if (io.gt.spp%norbs)  call die("symfio: No such orbital")
      else if (io.lt.0) then
         if (-io.gt.spp%nprojs)  call die("symfio: No such projector")
      else
         symfio = 's'
      endif
      lorb=lofio(is,io)
      morb=mofio(is,io)
      if(lorb.gt.lmax_sym ) then
         symfio=' '
      else
         ilm=lorb*lorb+lorb+morb+1
         if(pol(is,io)) then
            symfio='P'//sym_label(ilm)
         else
            symfio=sym_label(ilm)
         endif
      endif
      end function symfio
Call graph
symfio calls chk, lofio, mofio, pol
chk calls die
lofio calls chk
mofio calls chk
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush