update_F – SIESTA
update_F Subroutine
19 statements
Source File
private subroutine update_F(s_F, n, F)
Arguments
Type Intent Optional Attributes Name
type(Fstack_dData1D), intent(inout) :: s_F
integer, intent(in) :: n
real(kind=dp), intent(in) :: F(n)
Calls
Source Code
update_F
Source Code
  subroutine update_F(s_F,n,F)
    type(Fstack_dData1D), intent(inout) :: s_F
    integer, intent(in) :: n
    real(dp), intent(in) :: F(n)
    type(dData1D), pointer :: dD1
    real(dp), pointer :: FF(:)
    integer :: in
    if ( .not. stack_check(s_F,n) ) then
       call die('mixing: history has changed size...')
    end if
    in = n_items(s_F)
    if ( in == 0 ) then
       ! We need to add it as it does not exist
       call push_F(s_F,n,F)
    else
       ! we have an entry, update the latest
       dD1 => get_pointer(s_F,in)
       FF => val(dD1)
       call dcopy(n, F, 1, FF, 1)
    end if
  end subroutine update_F
All Procedures
compute_dm compute_max_diff compute_max_diff_1d compute_max_diff_2d current_itt getstackval inverse is_next mix_method mix_method_variant mixer_init mixers_history_init mixers_init mixers_print mixers_print_block mixers_reset mixers_scf_history_init mixers_scf_init mixers_scf_print mixers_scf_print_block mixers_scf_reset mixing mixing_1d mixing_2d mixing_calc_next mixing_coeff mixing_finalize mixing_init mixing_ncoeff mixing_scf_converged mixing_step norm push_diff push_F push_stack_data setup_H0 setup_hamiltonian siesta_analysis siesta_forces stack_check state_analysis state_init svd update_F
Call graph
update_f calls val, n_items, dcopy, die, push_f, stack_check, get_pointer
push_f calls val, n_items, dcopy, die, stack_check, push, get, newddata1d, max_size, delete
stack_check calls n_items, get_pointer