vna_gindex – SIESTA
vna_gindex Function
6 statements
Source File
public function vna_gindex(is)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
Return Value integer
Calls
Contents
Source Code
vna_gindex
Source Code
      FUNCTION vna_gindex (IS)
      integer vna_gindex
      integer, intent(in) :: is    ! Species index
C Returns the global index for a Vna function
      call chk('vna_gindex',is)
      vna_gindex = species(is)%vna_gindex
      end function vna_gindex
Call graph
vna_gindex calls chk
chk calls die
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush