write_rho – SIESTA
write_rho Subroutine
J.Soler
July 1997
104 statements
Source File
public subroutine write_rho(fname, cell, mesh, nsm, maxp, nspin, rho)
Writes the electron density or potential at the mesh points.
Parallel modifications added, while maintaining independence of density matrix on disk from parallel distribution. Uses a block distribution for density matrix. It is important to remember that the density matrix is divided so that all sub-points reside on the same node.
Modified by J.D.Gale March 1999.
Note
In order to achieve a consistent format of the disk file each record in the unformatted file corresponds to one pair of Y and Z values. Hence there will be a total of mesh(2) x mesh(3) records.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fname
File name
real(kind=dp), intent(in) :: cell(3,3)
integer, intent(in) :: mesh(3)
Number of mesh divisions of each lattice vector
integer, intent(in) :: nsm
Number of sub-mesh points per mesh point
(not used in this version)
integer, intent(in) :: maxp
integer, intent(in) :: nspin
real(kind=grid_p), intent(in) :: rho(maxp,nspin)
Calls
Called by
Contents
Source Code
write_rho
Source Code
      subroutine write_rho( fname, cell, mesh, nsm, maxp, nspin, rho)
      !! author: J.Soler
      !! date: July 1997
      !!
      !! Writes the electron density or potential at the mesh points.
      !!
      !! Parallel modifications added, while maintaining independence
      !! of density matrix on disk from parallel distribution. Uses a
      !! block distribution for density matrix. It is important to
      !! remember that the density matrix is divided so that all
      !! sub-points reside on the same node.
      !!
      !! Modified by J.D.Gale March 1999.
      !!
!!@note
!! In order to achieve a consistent format of the disk file
!! each record in the unformatted file corresponds to one pair of
!! Y and Z values. Hence there will be a total of mesh(2) x mesh(3)
!! records.
!!@endnote
      character(len=*), intent(in) ::     fname
        !! File name
      integer, intent(in)          ::     nsm
        !! Number of sub-mesh points per mesh point
        !! (not used in this version)
      integer, intent(in)          ::     mesh(3)
        !! Number of mesh divisions of each lattice vector
      integer, intent(in)          ::     maxp
      integer, intent(in)          ::     nspin
      real(grid_p), intent(in)     ::     rho(maxp,nspin)
      real(dp), intent(in)         ::     cell(3,3)
      external          io_assign, io_close, memory
      ! Internal variables and arrays
      integer    i, ip, iu, is, j, np,
     .           BlockSizeY, BlockSizeZ, ProcessorZ,
     .           meshnsm(3), NRemY, NRemZ,
     .           iy, iz, izm, Ind, ir
#ifdef MPI
      integer    Ind2, MPIerror, Request,
     .           Status(MPI_Status_Size), BNode, NBlock
      real(grid_p), pointer :: bdens(:) => null()
#endif
      real(sp),     pointer :: temp(:) => null()
#ifdef MPI
#ifdef DEBUG
        call write_debug( 'ERROR: write_rho not ready yet' )
        call write_debug( fname )
#endif
! Work out density block dimensions
      if (mod(Nodes,ProcessorY).gt.0)
     $     call die('ERROR: ProcessorY must be a factor of the' //
     $     ' number of processors!')
      ProcessorZ = Nodes/ProcessorY
      BlockSizeY = ((((mesh(2)/nsm)-1)/ProcessorY) + 1)*nsm
      call re_alloc(bdens, 1, BlockSizeY*mesh(1), 'bdens', 'write_rho')
#else
      ProcessorZ = 1
#endif
      call re_alloc( temp, 1, mesh(1), 'temp', 'write_rho' )
! Open file
      if (Node.eq.0) then
        call io_assign( iu )
        open( iu, file=fname, form=fform, status='unknown' )
      endif
      np = mesh(1) * mesh(2) * mesh(3)
      meshnsm(1) = mesh(1)/nsm
      meshnsm(2) = mesh(2)/nsm
      meshnsm(3) = mesh(3)/nsm
! Write data
      if (Node.eq.0) then
        if (fform .eq. 'formatted') then
          do i = 1,3
            write(iu,*) (cell(j,i),j=1,3)
          enddo
          write(iu,*) mesh, nspin
        else
          write(iu) cell
          write(iu) mesh, nspin
        endif
      endif
! Outer loop over spins
        do is = 1,nspin
          Ind = 0
! Loop over Z dimension of processor grid
          do iz = 1,ProcessorZ
            BlockSizeZ = (meshnsm(3)/ProcessorZ)
            NRemZ = meshnsm(3) - BlockSizeZ*ProcessorZ
            if (iz-1.lt.NRemZ) BlockSizeZ = BlockSizeZ + 1
            BlockSizeZ = BlockSizeZ*nsm
! Loop over local Z mesh points
            do izm = 1,BlockSizeZ
! Loop over blocks in Y mesh direction
              do iy = 1,ProcessorY
! Work out size of density sub-matrix to be transfered
                BlockSizeY = (meshnsm(2)/ProcessorY)
                NRemY = meshnsm(2) - BlockSizeY*ProcessorY
                if (iy-1.lt.NRemY) BlockSizeY = BlockSizeY + 1
                BlockSizeY = BlockSizeY*nsm
#ifdef MPI
                NBlock = BlockSizeY*mesh(1)
! Work out which node block is stored on
                BNode = (iy-1)*ProcessorZ + iz - 1
                if (BNode.eq.0.and.Node.eq.BNode) then
#endif
! If density sub-matrix is local Node 0 then just write it out
                  if (fform .eq. 'formatted') then
                    do ir = 1,BlockSizeY
                      write(iu,'(e15.6)') (rho(Ind+ip,is),
     .                  ip=1,mesh(1))
                      Ind = Ind + mesh(1)
                    enddo
                  else
!AG**
                    do ir = 1,BlockSizeY
                      temp(1:mesh(1)) =
     $                      real(rho(Ind+1:Ind+mesh(1),is),kind=sp)
                      write(iu) temp(1:mesh(1))
                      Ind = Ind + mesh(1)
                    enddo
                  endif
#ifdef MPI
                elseif (Node.eq.0) then
! If this is Node 0 then recv and write density sub-matrix
                  call MPI_IRecv(bdens,NBlock,MPI_grid_real,BNode,1,
     .              MPI_Comm_World,Request,MPIerror)
                  call MPI_Wait(Request,Status,MPIerror)
                elseif (Node.eq.BNode) then
! If this is the Node where the density sub-matrix is, then send
                  call MPI_ISend(rho(Ind+1,is),NBlock,MPI_grid_real,0,1,
     .              MPI_Comm_World,Request,MPIerror)
                  call MPI_Wait(Request,Status,MPIerror)
                  Ind = Ind + NBlock
                endif
                if (BNode.ne.0) then
                  call MPI_Barrier(MPI_Comm_World,MPIerror)
                  if (Node.eq.0) then
                    Ind2 = 0
                    if (fform .eq. 'formatted') then
                      do ir = 1,BlockSizeY
                        write(iu,'(e15.6)') (bdens(Ind2+ip),ip=1,
     .                    mesh(1))
                        Ind2 = Ind2 + mesh(1)
                      enddo
                    else
!AG**
                      do ir = 1,BlockSizeY
                      temp(1:mesh(1)) =
     $                      real(bdens(Ind2+1:Ind2+mesh(1)),kind=sp)
                        write(iu) temp(1:mesh(1))
                        Ind2 = Ind2 + mesh(1)
                      enddo
                    endif
                  endif
                endif
#endif
              enddo
            enddo
          enddo
        enddo
        if (Node.eq.0) then
! Close file
          call io_close( iu )
        endif
#ifdef MPI
C Deallocate density buffer memory
      call de_alloc( bdens, 'bdens', 'write_rho' )
#endif
      call de_alloc( temp, 'temp', 'write_rho' )
      end subroutine write_rho
Call graph
write_rho calls io_close, io_assign, mpi_wait, mpi_barrier, de_alloc, write_debug, mpi_irecv
dhscf calls write_rho
siesta_analysis calls dhscf
setup_hamiltonian calls dhscf
siesta_forces calls setup_hamiltonian