ZVALFIS – SIESTA
ZVALFIS Function
6 statements
Source File
public function ZVALFIS(is) result(zvalfis)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
Species index
Return Value real(kind=dp)
Valence charge
Calls
Contents
Source Code
ZVALFIS
Source Code
      FUNCTION ZVALFIS( IS )
        real(dp) :: zvalfis
          !! Valence charge
        integer, intent(in) :: is
          !! Species index
      call chk('zvalfis',is)
      zvalfis= species(is)%zval
      end function zvalfis
Call graph
zvalfis calls chk
chk calls die
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush