distMeshData – SIESTA
distMeshData Interface
3 statements
Source File
public interface distMeshData
Move data from vector fsrc, that uses distribution iDistr, to vector fdst, that uses distribution oDistr. It also re-orders a clustered data array into a sequential one and viceversa. If this is a sequencial execution, it only reorders the data.
Note
There are two subroutines: one to deal with real data and the other with integers. Both are called using the same interface.
Note
AG: Note that the integer version does NOT have the exact functionality of the real version. In particular, the integer version has no provision for a "serial fallback", and so this case has been trapped.
Check the communications that this process should do to move data from iDistr to oDistr. We have 3 kind of communications (send, receive and keep on the same node). We have 3 kind of reorderings (clustered to sequential, sequential to clustered and keep the same ordering).
For the sequencial code we call subroutine reord
INPUT
iDistr : Distribution index of the input vector.
fsrc : Input vector.
oDistr : Distribution index of the output vector.
itr : TRanslation-direction switch:
itr=+1 => From clustered to sequential
itr=-1 => From sequential to clustered
itr=0 => Keep the status
OUTPUT
fdst : Output vector.
Calls
Called by
Contents
Module Procedures
distMeshData_rea distMeshData_int
Module Procedures
private subroutine distMeshData_rea(iDistr, fsrc, oDistr, fdst, itr)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iDistr
real(kind=grid_p), intent(in) :: fsrc(*)
integer, intent(in) :: oDistr
real(kind=grid_p), intent(out) :: fdst(*)
integer, intent(in) :: itr
private subroutine distMeshData_int(iDistr, fsrc, oDistr, fdst, itr)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iDistr
integer, intent(in) :: fsrc(*)
integer, intent(in) :: oDistr
integer, intent(out) :: fdst(*)
integer, intent(in) :: itr
Call graph
distmeshdata calls distmeshdata_rea, distmeshdata_int
distmeshdata_rea calls mpitrace_event, boxintersection, reord, re_alloc, timer, mpi_barrier, de_alloc, write_debug, die
distmeshdata_int calls boxintersection, re_alloc, de_alloc, die
reord calls re_alloc, timer, de_alloc
die calls io_close, cmlfinishfile, io_assign, pxfabort, mpi_abort, pxfflush
dhscf_init calls distmeshdata
dhscf calls distmeshdata, forhar
forhar calls distmeshdata
siesta_analysis calls dhscf
setup_hamiltonian calls dhscf
setup_h0 calls dhscf_init
siesta_forces calls setup_hamiltonian