mixing – SIESTA
mixing Interface
3 statements
Source File
public interface mixing
Calls
Module Procedures
mixing_1d mixing_2d
Module Procedures
private subroutine mixing_1d(mix, n, xin, F, xnext, nsub)
Arguments
Type Intent Optional Attributes Name
type(tMixer), pointer :: mix
integer, intent(in) :: n
real(kind=dp), intent(in) :: xin(n)
real(kind=dp), intent(in) :: F(n)
real(kind=dp), intent(inout) :: xnext(n)
integer, intent(in), optional :: nsub
private subroutine mixing_2d(mix, n1, n2, xin, F, xnext, nsub)
Arguments
Type Intent Optional Attributes Name
type(tMixer), pointer :: mix
integer, intent(in) :: n1
integer, intent(in) :: n2
real(kind=dp), intent(in) :: xin(n1,n2)
real(kind=dp), intent(in) :: F(n1,n2)
real(kind=dp), intent(inout) :: xnext(n1,n2)
integer, intent(in), optional :: nsub
All Procedures
compute_dm compute_max_diff compute_max_diff_1d compute_max_diff_2d current_itt getstackval inverse is_next mix_method mix_method_variant mixer_init mixers_history_init mixers_init mixers_print mixers_print_block mixers_reset mixers_scf_history_init mixers_scf_init mixers_scf_print mixers_scf_print_block mixers_scf_reset mixing mixing_1d mixing_2d mixing_calc_next mixing_coeff mixing_finalize mixing_init mixing_ncoeff mixing_scf_converged mixing_step norm push_diff push_F push_stack_data setup_H0 setup_hamiltonian siesta_analysis siesta_forces stack_check state_analysis state_init svd update_F
Call graph
mixing calls mixing_2d, mixing_1d
mixing_1d calls mixing_coeff, mixing_finalize, mixing_init, mixing_calc_next, mixing_ncoeff
mixing_coeff calls mixing_ncoeff
mixing_finalize calls n_items, current_itt, mixing_step, reset
mixing_init calls norm, current_itt
mixing_ncoeff calls n_items
mixing_step calls n_items, reset, get_pointer, push